CREATE DISTRIBUTION ds1 COLUMN TYPES integer;
CREATE KEY RANGE krid1 FROM 1 TO 10 ROUTE TO sh1 FOR DISTRIBUTION ds1;
CREATE KEY RANGE krid2 FROM 11 TO 20 ROUTE TO sh1 FOR DISTRIBUTION ds1;

SHOW key_ranges;

DROP KEY RANGE krid1;

CREATE KEY RANGE krid2 FROM 11 TO 20 ROUTE TO sh2 FOR DISTRIBUTION ds1;

SHOW key_ranges;

CREATE KEY RANGE krid2 FROM 33 TO 44 ROUTE TO nonexistentshard FOR DISTRIBUTION ds1;

DROP DISTRIBUTION ALL CASCADE;
DROP KEY RANGE ALL;
