ADD SHARDING RULE rule1 COLUMNS id FOR DATASPACE ds1;
ADD SHARDING RULE rule2 COLUMNS id FOR DATASPACE ds2;

ADD KEY RANGE krid1 FROM 1 TO 11 ROUTE TO sh1 FOR DATASPACE ds1;
ADD KEY RANGE krid2 FROM 11 TO 31 ROUTE TO sh2 FOR DATASPACE ds1;

ADD KEY RANGE krid3 FROM 11 TO 31 ROUTE TO sh2 FOR DATASPACE ds2;

DROP DATASPACE ds1;

SHOW dataspaces;

DROP DATASPACE ALL CASCADE;

SHOW dataspaces;
SHOW key_ranges;
SHOW sharding_rules;