CREATE DATASPACE ds1;
CREATE DATASPACE ds2;

CREATE SHARDING RULE rule1 COLUMNS id FOR DATASPACE ds1;
CREATE SHARDING RULE rule2 COLUMNS id FOR DATASPACE ds2;

CREATE KEY RANGE krid1 FROM 1 ROUTE TO sh1 FOR DATASPACE ds1;
CREATE KEY RANGE krid2 FROM 11 ROUTE TO sh2 FOR DATASPACE ds1;

CREATE KEY RANGE krid3 FROM 11 ROUTE TO sh2 FOR DATASPACE ds2;

DROP DATASPACE ds1 CASCADE;

SHOW dataspaces;

DROP DATASPACE ALL CASCADE;

SHOW dataspaces;
SHOW key_ranges;
SHOW sharding_rules;