ADD KEY RANGE krid1 FROM 1 TO 10 ROUTE TO sh1;
ADD KEY RANGE krid2 FROM 11 TO 20 ROUTE TO sh1;

ADD SHARDING RULE rule1 COLUMNS id;
ADD SHARDING RULE rule1 COLUMNS id;
ADD SHARDING RULE rule2 COLUMNS id;

SHOW key_ranges;
SHOW sharding_rules;

DROP KEY RANGE ALL;
DROP SHARDING RULE wrong;
DROP SHARDING RULE ALL;

SHOW key_ranges;
SHOW sharding_rules;
