CREATE DISTRIBUTION ds1 COLUMN TYPES integer;
CREATE SHARDING RULE hash1 COLUMNS col1 HASH FUNCTION IDENT FOR DISTRIBUTION ds1;
CREATE SHARDING RULE hash2 COLUMNS col2 HASH FUNCTION IDENTITY FOR DISTRIBUTION ds1;
CREATE SHARDING RULE hash3 COLUMNS col3 HASH FUNCTION MURMUR FOR DISTRIBUTION ds1;
CREATE SHARDING RULE hash4 COLUMNS col4 HASH FUNCTION CITY FOR DISTRIBUTION ds1;

SHOW sharding_rules;

DROP DISTRIBUTION ALL CASCADE;
DROP SHARDING RULE ALL;
DROP KEY RANGE ALL;