CREATE SHARDING RULE hash1 COLUMNS col1 HASH FUNCTION IDENT;
CREATE SHARDING RULE hash2 COLUMNS col2 HASH FUNCTION IDENTITY;
CREATE SHARDING RULE hash3 COLUMNS col3 HASH FUNCTION MURMUR HASH;
CREATE SHARDING RULE hash4 COLUMNS col4 HASH FUNCTION CITY HASH;


DROP DISTRIBUTION ALL CASCADE;
DROP SHARDING RULE ALL;
DROP KEY RANGE ALL;