CREATE REFERENCE TABLE zz;

CREATE REFERENCE TABLE zz2 ON sh3, sh4;

CREATE REFERENCE RELATION zz2;

SYNC REFERENCE TABLES ON sh1;

DROP REFERENCE RELATION zz2;
--should fail
DROP REFERENCE RELATION zz2;

DROP DISTRIBUTION ALL CASCADE;
DROP KEY RANGE ALL;
