CREATE REFERENCE TABLE zz;

CREATE REFERENCE TABLE zz2 ON sh3, sh4;

CREATE REFERENCE RELATION zz2;

-- Test SYNC REFERENCE commands (all fail on router, but parser should work)
SYNC REFERENCE TABLES ON sh1;
SYNC REFERENCE TABLE zz2 ON sh1;

ALTER DISTRIBUTION 'REPLICATED' ALTER RELATION zz2 SCHEMA my_schema;
ALTER DISTRIBUTION 'REPLICATED' ALTER RELATION zz2 DISTRIBUTION KEY id;

DROP REFERENCE RELATION zz2;
--should fail
DROP REFERENCE RELATION zz2;

DROP DISTRIBUTION ALL CASCADE;
DROP KEY RANGE ALL;
