CREATE DISTRIBUTION ds1 COLUMN TYPES int hash;
ALTER DISTRIBUTION ds1 ATTACH RELATION table1
  DISTRIBUTION KEY murmur [entity_type varchar, entity_id uinteger];
SHOW RELATIONS;
DROP DISTRIBUTION ALL CASCADE;
