CREATE REPLICATED DISTRIBUTION;
ALTER REPLICATED DISTRIBUTION ATTACH RELATION t AUTO INCREMENT id;

CREATE REFERENCE TABLE t1 AUTO INCREMENT id;
SHOW SEQUENCES;

DROP SEQUENCE t1_id;

ALTER REPLICATED DISTRIBUTION DETACH RELATION t1;
DROP SEQUENCE t1_id;

CREATE DISTRIBUTION ds COLUMN TYPES integer;
ALTER DISTRIBUTION ds ATTACH RELATION t2 DISTRIBUTION KEY id AUTO INCREMENT id1;

DROP DISTRIBUTION ALL CASCADE;
DROP KEY RANGE ALL;
