CREATE DISTRIBUTION ds1 COLUMN TYPES integer;
CREATE SHARDING RULE rule1 COLUMNS id FOR DISTRIBUTION ds1;
CREATE SHARDING RULE rule2 COLUMNS idx FOR DISTRIBUTION ds1;
CREATE SHARDING RULE rule3 COLUMNS idy FOR DISTRIBUTION ds1;

SHOW sharding_rules;

DROP DISTRIBUTION ALL CASCADE;
DROP SHARDING RULE ALL;
DROP KEY RANGE ALL;