CREATE SHARDING RULE rule1 COLUMNS id;
CREATE SHARDING RULE rule2 COLUMNS idx;
CREATE SHARDING RULE rule3 COLUMNS idy;

SHOW sharding_rules;

DROP DISTRIBUTION ALL CASCADE;
DROP SHARDING RULE ALL;
DROP KEY RANGE ALL;