CREATE DISTRIBUTION ds1 COLUMN TYPES integer;
CREATE DISTRIBUTION ds2 COLUMN TYPES varchar, integer;
CREATE DISTRIBUTION ds3 COLUMN TYPES varchar;
ALTER DISTRIBUTION ds1 ATTACH RELATION a DISTRIBUTION KEY a_id;
ALTER DISTRIBUTION ds1 ATTACH RELATION b DISTRIBUTION KEY b_id HASH FUNCTION MURMUR;
ALTER DISTRIBUTION ds2 ATTACH RELATION c DISTRIBUTION KEY c_id_1 HASH FUNCTION IDENT,
                                                          c_id_2 HASH FUNCTION CITY;
ALTER DISTRIBUTION ds3 ATTACH RELATION d DISTRIBUTION KEY d_id HASH FUNCTION CITY;


SHOW relations;
SHOW relations WHERE distribution_id = 'ds1';
SHOW relations WHERE unknown_param = 'ds1';

DROP DISTRIBUTION ALL CASCADE;
DROP KEY RANGE ALL;
