CREATE DISTRIBUTION ds1 COLUMN TYPES integer;
CREATE DISTRIBUTION ds2 COLUMN TYPES varchar, integer;
CREATE DISTRIBUTION ds3 COLUMN TYPES integer hash DEFAULT SHARD sh1;

SHOW distributions;

DROP DISTRIBUTION ALL CASCADE;
DROP KEY RANGE ALL;
