CREATE DISTRIBUTION ds1 COLUMN TYPES integer;
CREATE KEY RANGE krid2 FROM 40 ROUTE TO sh1 FOR DISTRIBUTION ds1;
CREATE KEY RANGE krid1 FROM 30 ROUTE TO sh1 FOR DISTRIBUTION ds1;

SHOW key_ranges;

CREATE DISTRIBUTION ds2 COLUMN TYPES integer;
CREATE KEY RANGE krid22 FROM 11 ROUTE TO sh1 FOR DISTRIBUTION ds2;
CREATE KEY RANGE krid21 FROM 1 ROUTE TO sh1 FOR DISTRIBUTION ds2;

SHOW key_ranges;

CREATE KEY RANGE krid4 FROM 20 ROUTE TO sh3 FOR DISTRIBUTION ds1;
CREATE KEY RANGE krid3 FROM 10 ROUTE TO sh4 FOR DISTRIBUTION ds1;

SHOW key_ranges ORDER BY "lower_bound" ASC;
SHOW key_ranges ORDER BY "lower_bound" DESC;

SHOW key_ranges WHERE distribution_id = 'ds1';

SHOW key_ranges WHERE shard_id = 'sh3';

SHOW key_ranges VERBOSE;

SHOW key_ranges VERBOSE WHERE distribution_id = 'ds1';

SHOW key_ranges VERBOSE ORDER BY "lower_bound" ASC;

DROP DISTRIBUTION ALL CASCADE;
DROP KEY RANGE ALL;