CREATE DISTRIBUTION ds1 COLUMN TYPES integer;
CREATE DISTRIBUTION ds2 COLUMN TYPES varchar hash, integer hash;
CREATE DISTRIBUTION ds3 COLUMN TYPES integer hash;
ALTER DISTRIBUTION ds1 ATTACH RELATION a DISTRIBUTION KEY a_id;
ALTER DISTRIBUTION ds3 ATTACH RELATION b DISTRIBUTION KEY b_id HASH FUNCTION MURMUR;
ALTER DISTRIBUTION ds2 ATTACH RELATION c DISTRIBUTION KEY c_id_1 HASH FUNCTION IDENT,
                                                          c_id_2 HASH FUNCTION CITY;
ALTER DISTRIBUTION ds1 ATTACH RELATION d DISTRIBUTION KEY d_id;

CREATE REFERENCE RELATION z_rf;

SHOW relations;
SHOW relations WHERE "Distribution ID" = 'ds1';
SHOW relations WHERE unknown_param = 'ds1';

SHOW reference_relations;

DROP DISTRIBUTION ALL CASCADE;
DROP KEY RANGE ALL;
