
CREATE DISTRIBUTION ds1 COLUMN TYPES integer;
CREATE KEY RANGE kr1 FROM 100 ROUTE TO sh1 FOR DISTRIBUTION ds1;
CREATE KEY RANGE kr2 FROM 0 ROUTE TO sh1 FOR DISTRIBUTION ds1;

BEGIN;

CREATE RELATION test (id) IN ds1;
RENAME KEY RANGE kr1 TO kr1_new;

COMMIT;

SHOW DISTRIBUTIONS;
SHOW RELATIONS;
SHOW KEY_RANGES;

BEGIN;

DROP DISTRIBUTION ALL CASCADE;

ROLLBACK;

SHOW DISTRIBUTIONS;
SHOW RELATIONS;
SHOW KEY_RANGES;

DROP DISTRIBUTION ALL CASCADE;
