CREATE DISTRIBUTION ds1 COLUMN TYPES integer;
ALTER DISTRIBUTION ds1 ATTACH RELATION t DISTRIBUTION KEY id;

CREATE UNIQUE INDEX ui1 ON t COLUMN col_uniq TYPE integer;
CREATE UNIQUE INDEX ui_same_col ON t COLUMN col_uniq TYPE integer;
CREATE UNIQUE INDEX ui2 ON t COLUMN col_uniq_2 TYPE integer;

SHOW unique_indexes;

DROP UNIQUE INDEX ui1;

SHOW unique_indexes;

DROP UNIQUE INDEX ui2;

DROP DISTRIBUTION ds1 CASCADE;

