DROP DISTRIBUTION ALL;

CREATE DISTRIBUTION ds1 COLUMN TYPES integer;

CREATE KEY RANGE krid2 FROM 50001 ROUTE TO sh2 FOR DISTRIBUTION ds1;
CREATE KEY RANGE krid1 FROM 1 ROUTE TO sh1 FOR DISTRIBUTION ds1;
    
ALTER DISTRIBUTION ds1 ATTACH RELATION pgbench_accounts DISTRIBUTION KEY aid;
