DROP DISTRIBUTION ALL;
DROP KEY RANGE ALL;
DROP SHARDING RULE ALL;

CREATE DISTRIBUTION ds1 COLUMN TYPES integer;

ADD KEY RANGE krid1 FROM 1 TO 50000 ROUTE TO sh1 FOR DISTRIBUTION ds1;
ADD KEY RANGE krid2 FROM 50001 TO 100000 ROUTE TO sh2 FOR DISTRIBUTION ds1;
    
ALTER DISTRIBUTION ds1 ATTACH RELATION pgbench_accounts DISTRIBUTION KEY aid;
