\c spqr-console

CREATE DISTRIBUTION ds1;
CREATE DISTRIBUTION ds2;

CREATE SHARDING RULE r1 COLUMNS w_id FOR DISTRIBUTION ds1;
CREATE SHARDING RULE r2 COLUMNS w_id FOR DISTRIBUTION ds2;

CREATE KEY RANGE krid1 FROM 1 ROUTE TO sh1 FOR DISTRIBUTION ds1;
CREATE KEY RANGE krid2 FROM 11 ROUTE TO sh2 FOR DISTRIBUTION ds1;
CREATE KEY RANGE krid3 FROM 11 ROUTE TO sh2 FOR DISTRIBUTION ds2;

CREATE KEY RANGE FROM 1 ROUTE TO sh2 FOR DISTRIBUTION ds2;

ATTACH TABLE xx TO DISTRIBUTION ds1;
ATTACH TABLE yy TO DISTRIBUTION ds2;

DROP DISTRIBUTION ALL CASCADE;
DROP SHARDING RULE ALL;
DROP KEY RANGE ALL;