
\c spqr-console

CREATE DISTRIBUTION ds1 COLUMN TYPES integer;

CREATE KEY RANGE FROM 301 ROUTE TO sh4 FOR DISTRIBUTION ds1;
CREATE KEY RANGE FROM 201 ROUTE TO sh3 FOR DISTRIBUTION ds1;

CREATE KEY RANGE FROM 101 ROUTE TO sh2 FOR DISTRIBUTION ds1;
CREATE KEY RANGE FROM 1 ROUTE TO sh1 FOR DISTRIBUTION ds1;

ALTER DISTRIBUTION ds1 ATTACH RELATION table1 DISTRIBUTION KEY id;

\c regress

CREATE TABLE table1(id INT PRIMARY KEY);

COPY table1 (id) FROM STDIN;
1
2
3
100
101
102
103
200
201
202
300
301
302
\.

-- should fail
BEGIN;
DELETE FROM table1;
ROLLBACK;

BEGIN;
DELETE FROM table1 /* __spqr__engine_v2: true  */; 
SELECT id FROM table1 ORDER BY id;
ROLLBACK;

SELECT id FROM table1 ORDER BY id;

DROP TABLE table1 CASCADE;

\c spqr-console
DROP DISTRIBUTION ALL CASCADE;
DROP KEY RANGE ALL;

