
\c spqr-console

CREATE DISTRIBUTION ds1 COLUMN TYPES integer;

CREATE KEY RANGE FROM 301 ROUTE TO sh4 FOR DISTRIBUTION ds1;
CREATE KEY RANGE FROM 201 ROUTE TO sh3 FOR DISTRIBUTION ds1;

CREATE KEY RANGE FROM 101 ROUTE TO sh2 FOR DISTRIBUTION ds1;
CREATE KEY RANGE FROM 1 ROUTE TO sh1 FOR DISTRIBUTION ds1;

ALTER DISTRIBUTION ds1 ATTACH RELATION table1 DISTRIBUTION KEY id;

\c regress

CREATE TABLE table1(id INT PRIMARY KEY);

COPY table1 (id) FROM STDIN;
1
2
3
100
101
102
103
200
201
202
300
301
302
\.

-- should fail

SET __spqr__engine_v2 TO false;
BEGIN;
DELETE FROM table1; 
ROLLBACK;

BEGIN;
DELETE FROM table1 /* __spqr__engine_v2: off */;
ROLLBACK;

-- should succeed
BEGIN;
DELETE FROM table1 /* __spqr__engine_v2: on  */; 
SELECT id FROM table1 ORDER BY id;
ROLLBACK;


-- should fail
BEGIN;
DELETE FROM table1; 
ROLLBACK;

-- now success
SET __spqr__engine_v2 TO true;
BEGIN;
DELETE FROM table1; 
ROLLBACK;

SELECT id FROM table1 ORDER BY id;

-- should all succeed
INSERT INTO table1 (id) VALUES(50),(51);
INSERT INTO table1 (id) VALUES(150),(151);
INSERT INTO table1 (id) VALUES(250),(251);
INSERT INTO table1 (id) VALUES(350),(351);
WITH a AS (SELECT 1) INSERT INTO table1 (id) VALUES(52),(53);

TRUNCATE table1;


-- disable v1 logic, now CTE fails
SET __spqr__preferred_engine to 'v2';

INSERT INTO table1 (id) VALUES(50),(51);
INSERT INTO table1 (id) VALUES(150),(151);
INSERT INTO table1 (id) VALUES(250),(251);
INSERT INTO table1 (id) VALUES(350),(351);
WITH a AS (SELECT 1) INSERT INTO table1 (id) VALUES(52),(53);

DROP TABLE table1 CASCADE;

\c spqr-console
DROP DISTRIBUTION ALL CASCADE;
DROP KEY RANGE ALL;

