\c spqr-console

CREATE DISTRIBUTION ds1 COLUMN TYPES integer;

CREATE KEY RANGE FROM 301 ROUTE TO sh4 FOR DISTRIBUTION ds1;
CREATE KEY RANGE FROM 201 ROUTE TO sh3 FOR DISTRIBUTION ds1;

CREATE KEY RANGE FROM 101 ROUTE TO sh2 FOR DISTRIBUTION ds1;
CREATE KEY RANGE FROM 1 ROUTE TO sh1 FOR DISTRIBUTION ds1;

CREATE REFERENCE TABLE ref_rel_1;

ALTER DISTRIBUTION ds1 ATTACH RELATION table1 DISTRIBUTION KEY i;

\c regress

CREATE TABLE table1(i INT PRIMARY KEY);
CREATE TABLE ref_rel_1(i int, j int);

SELECT * FROM (SELECT * FROM table1 WHERE i = 1) AS a;
SELECT * FROM (SELECT * FROM (SELECT * FROM table1 WHERE i = 1) AS a) AS b;

-- should dispatch to sh3
SELECT 1, (SELECT i FROM table1 WHERE i = 201);

-- should dispatch to sh3 and sh4 (TODO: parallel processing)
SELECT 1, (SELECT i FROM table1 WHERE i = 201), (SELECT i FROM table1 WHERE i = 301);

-- should dispatch to sh3
SELECT i FROM table1 WHERE i = 201 AND NOT (SELECT false);

DROP TABLE table1;
DROP TABLE ref_rel_1;

\c spqr-console
DROP DISTRIBUTION ALL CASCADE;
