\c spqr-console
DROP DATASPACE ALL CASCADE;

CREATE DATASPACE ds1;
CREATE DATASPACE ds2;

ADD SHARDING RULE r1 COLUMNS w_id FOR DATASPACE ds1;
ADD SHARDING RULE r2 COLUMNS w_id FOR DATASPACE ds2;

ADD KEY RANGE krid1 FROM 1 TO 11 ROUTE TO sh1 FOR DATASPACE ds1;
ADD KEY RANGE krid2 FROM 11 TO 31 ROUTE TO sh2 FOR DATASPACE ds1;

ADD KEY RANGE krid3 FROM 11 TO 31 ROUTE TO sh2 FOR DATASPACE ds2;

\c regress

SET __spqr__DATASPACE = ds1;

CREATE TABLE xx (w_id int);

INSERT INTO xx(w_id) VALUES(5);

INSERT INTO xx(w_id) VALUES(20);

SELECT * FROM xx WHERE w_id=5;

SET __spqr__DATASPACE = ds2;

SELECT * FROM xx WHERE w_id=5;
