\c spqr-console
CREATE DISTRIBUTION d COLUMN TYPES INT HASH;

CREATE RELATION r (i HASH murmur);

CREATE UNIQUE INDEX ui ON r COLUMN j TYPE integer;

CREATE KEY RANGE k4 FROM 3221225472 ROUTE TO sh4;
CREATE KEY RANGE k3 FROM 2147483648 ROUTE TO sh3;
CREATE KEY RANGE k2 FROM 1073741824 ROUTE TO sh2;
CREATE KEY RANGE k1 FROM 0 ROUTE TO sh1;

\c regress

CREATE TABLE r(i int);

-- unique index is actually a reverse index (just another table)
CREATE TABLE ui(j int);
CREATE UNIQUE INDEX ON ui USING btree(j);

DROP TABLE r;
DROP TABLE ui;

\c spqr-console
DROP DISTRIBUTION ALL CASCADE;