# Simple SPQR Router Configuration
# This is a minimal public example configuration
# Adjust hosts, credentials, and settings for your environment

host: 'spqr-router'
router_port: '5432'
admin_console_port: '7432'
grpc_api_port: '7000'

router_mode: PROXY
log_level: info

# Enable SSL/TLS for client connections
frontend_tls:
  key_file: /etc/spqr/ssl/server.key
  cert_file: /etc/spqr/ssl/server.crt
  sslmode: allow

# Frontend rules - database and user mapping
frontend_rules:
  - usr: postgres
    db: postgres
    pool_default: true
    pool_mode: TRANSACTION
    pool_prepared_statement: false
    auth_rule:
      auth_method: ok

# Backend shard configuration
shards:
  shard1:
    db: postgres
    usr: postgres
    pwd: postgres
    type: DATA
    hosts:
      - 'localhost:5433'
    tls:
      sslmode: disable

# Backend pool rules
backend_rules:
  - usr: postgres
    db: postgres
    connection_limit: 100
    pool_discard: true
    pool_rollback: true

schema_cache_backend_rule:
  usr: postgres
  db: postgres
  pool_discard: true
  pool_rollback: true

world_shard_fallback: true
