// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/backend_connections.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListBackendConntionsReply struct {
	Conns                []*BackendConnectionsInfo `protobuf:"bytes,1,rep,name=conns,proto3" json:"conns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListBackendConntionsReply) Reset()         { *m = ListBackendConntionsReply{} }
func (m *ListBackendConntionsReply) String() string { return proto.CompactTextString(m) }
func (*ListBackendConntionsReply) ProtoMessage()    {}
func (*ListBackendConntionsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf0bfc666d274120, []int{0}
}

func (m *ListBackendConntionsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBackendConntionsReply.Unmarshal(m, b)
}
func (m *ListBackendConntionsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBackendConntionsReply.Marshal(b, m, deterministic)
}
func (m *ListBackendConntionsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBackendConntionsReply.Merge(m, src)
}
func (m *ListBackendConntionsReply) XXX_Size() int {
	return xxx_messageInfo_ListBackendConntionsReply.Size(m)
}
func (m *ListBackendConntionsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBackendConntionsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListBackendConntionsReply proto.InternalMessageInfo

func (m *ListBackendConntionsReply) GetConns() []*BackendConnectionsInfo {
	if m != nil {
		return m.Conns
	}
	return nil
}

type BackendConnectionsInfo struct {
	BackendConnectionId  uint64   `protobuf:"varint,1,opt,name=backend_connection_id,json=backendConnectionId,proto3" json:"backend_connection_id,omitempty"`
	ShardKeyName         string   `protobuf:"bytes,2,opt,name=shard_key_name,json=shardKeyName,proto3" json:"shard_key_name,omitempty"`
	Hostname             string   `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	User                 string   `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Dbname               string   `protobuf:"bytes,5,opt,name=dbname,proto3" json:"dbname,omitempty"`
	Sync                 int64    `protobuf:"varint,6,opt,name=sync,proto3" json:"sync,omitempty"`
	TxServed             int64    `protobuf:"varint,7,opt,name=tx_served,json=txServed,proto3" json:"tx_served,omitempty"`
	TxStatus             int64    `protobuf:"varint,8,opt,name=tx_status,json=txStatus,proto3" json:"tx_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackendConnectionsInfo) Reset()         { *m = BackendConnectionsInfo{} }
func (m *BackendConnectionsInfo) String() string { return proto.CompactTextString(m) }
func (*BackendConnectionsInfo) ProtoMessage()    {}
func (*BackendConnectionsInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf0bfc666d274120, []int{1}
}

func (m *BackendConnectionsInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackendConnectionsInfo.Unmarshal(m, b)
}
func (m *BackendConnectionsInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackendConnectionsInfo.Marshal(b, m, deterministic)
}
func (m *BackendConnectionsInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackendConnectionsInfo.Merge(m, src)
}
func (m *BackendConnectionsInfo) XXX_Size() int {
	return xxx_messageInfo_BackendConnectionsInfo.Size(m)
}
func (m *BackendConnectionsInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BackendConnectionsInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BackendConnectionsInfo proto.InternalMessageInfo

func (m *BackendConnectionsInfo) GetBackendConnectionId() uint64 {
	if m != nil {
		return m.BackendConnectionId
	}
	return 0
}

func (m *BackendConnectionsInfo) GetShardKeyName() string {
	if m != nil {
		return m.ShardKeyName
	}
	return ""
}

func (m *BackendConnectionsInfo) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *BackendConnectionsInfo) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *BackendConnectionsInfo) GetDbname() string {
	if m != nil {
		return m.Dbname
	}
	return ""
}

func (m *BackendConnectionsInfo) GetSync() int64 {
	if m != nil {
		return m.Sync
	}
	return 0
}

func (m *BackendConnectionsInfo) GetTxServed() int64 {
	if m != nil {
		return m.TxServed
	}
	return 0
}

func (m *BackendConnectionsInfo) GetTxStatus() int64 {
	if m != nil {
		return m.TxStatus
	}
	return 0
}

func init() {
	proto.RegisterType((*ListBackendConntionsReply)(nil), "spqr.ListBackendConntionsReply")
	proto.RegisterType((*BackendConnectionsInfo)(nil), "spqr.BackendConnectionsInfo")
}

func init() { proto.RegisterFile("protos/backend_connections.proto", fileDescriptor_cf0bfc666d274120) }

var fileDescriptor_cf0bfc666d274120 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4f, 0xc2, 0x40,
	0x10, 0xc5, 0x2d, 0x14, 0x84, 0x91, 0x78, 0x58, 0x63, 0xb3, 0x80, 0x89, 0x0d, 0xf1, 0xd0, 0x53,
	0x49, 0xea, 0x37, 0xc0, 0x78, 0x20, 0x1a, 0x4d, 0xca, 0xcd, 0x4b, 0xd3, 0x3f, 0x03, 0x34, 0xc0,
	0x6e, 0xed, 0x6e, 0x0d, 0xfd, 0x06, 0x7e, 0x6c, 0xd3, 0x69, 0x21, 0x06, 0xf4, 0xd4, 0x9d, 0xf7,
	0x7e, 0xfb, 0xba, 0x99, 0x07, 0x76, 0x96, 0x4b, 0x2d, 0xd5, 0x34, 0x0a, 0xe3, 0x0d, 0x8a, 0x24,
	0x88, 0xa5, 0x10, 0x18, 0xeb, 0x54, 0x0a, 0xe5, 0x92, 0xc5, 0x4c, 0x95, 0x7d, 0xe6, 0xa3, 0xf1,
	0x4a, 0xca, 0xd5, 0x16, 0xa7, 0xa4, 0x45, 0xc5, 0x72, 0x8a, 0xbb, 0x4c, 0x97, 0x35, 0x32, 0x79,
	0x87, 0xe1, 0x6b, 0xaa, 0xf4, 0xac, 0xce, 0x78, 0x92, 0x42, 0x50, 0x80, 0x8f, 0xd9, 0xb6, 0x64,
	0x1e, 0x74, 0xaa, 0x50, 0xc5, 0x0d, 0xbb, 0xed, 0x5c, 0x79, 0x77, 0x6e, 0x95, 0xe7, 0xfe, 0x62,
	0x9b, 0xdf, 0xcd, 0xc5, 0x52, 0xfa, 0x35, 0x3a, 0xf9, 0x6e, 0x81, 0xf5, 0x37, 0xc1, 0x3c, 0xb8,
	0x3d, 0x7f, 0x6b, 0x90, 0x26, 0xdc, 0xb0, 0x0d, 0xc7, 0xf4, 0x6f, 0xa2, 0xd3, 0x6b, 0xf3, 0x84,
	0x3d, 0xc0, 0xb5, 0x5a, 0x87, 0x79, 0x12, 0x6c, 0xb0, 0x0c, 0x44, 0xb8, 0x43, 0xde, 0xb2, 0x0d,
	0xa7, 0xef, 0x0f, 0x48, 0x7d, 0xc1, 0xf2, 0x2d, 0xdc, 0x21, 0x1b, 0x41, 0x6f, 0x2d, 0x95, 0x26,
	0xbf, 0x4d, 0xfe, 0x71, 0x66, 0x0c, 0xcc, 0x42, 0x61, 0xce, 0x4d, 0xd2, 0xe9, 0xcc, 0x2c, 0xe8,
	0x26, 0x11, 0xd1, 0x1d, 0x52, 0x9b, 0xa9, 0x62, 0x55, 0x29, 0x62, 0xde, 0xb5, 0x0d, 0xa7, 0xed,
	0xd3, 0x99, 0x8d, 0xa1, 0xaf, 0xf7, 0x81, 0xc2, 0xfc, 0x0b, 0x13, 0x7e, 0x49, 0x46, 0x4f, 0xef,
	0x17, 0x34, 0x1f, 0x4c, 0x1d, 0xea, 0x42, 0xf1, 0xde, 0xd1, 0xa4, 0xd9, 0xcb, 0x60, 0x78, 0xbe,
	0x89, 0xea, 0x62, 0x1a, 0x23, 0x5b, 0x80, 0x75, 0xb2, 0xf8, 0x06, 0x60, 0x96, 0x5b, 0x17, 0xe6,
	0x1e, 0x0a, 0x73, 0x9f, 0xab, 0xc2, 0x46, 0xf7, 0xf5, 0xfa, 0xff, 0xad, 0x6b, 0x72, 0x31, 0x1b,
	0x7c, 0x40, 0xc5, 0x34, 0x55, 0x77, 0xe9, 0xf3, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff, 0xc9, 0xe6,
	0x43, 0xcb, 0x29, 0x02, 0x00, 0x00,
}
