// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: protos/distrinution.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Distribution struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Distribution) Reset() {
	*x = Distribution{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_distrinution_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Distribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Distribution) ProtoMessage() {}

func (x *Distribution) ProtoReflect() protoreflect.Message {
	mi := &file_protos_distrinution_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Distribution.ProtoReflect.Descriptor instead.
func (*Distribution) Descriptor() ([]byte, []int) {
	return file_protos_distrinution_proto_rawDescGZIP(), []int{0}
}

func (x *Distribution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddDistributionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Distributions []*Distribution `protobuf:"bytes,1,rep,name=distributions,proto3" json:"distributions,omitempty"`
}

func (x *AddDistributionRequest) Reset() {
	*x = AddDistributionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_distrinution_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDistributionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDistributionRequest) ProtoMessage() {}

func (x *AddDistributionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_distrinution_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDistributionRequest.ProtoReflect.Descriptor instead.
func (*AddDistributionRequest) Descriptor() ([]byte, []int) {
	return file_protos_distrinution_proto_rawDescGZIP(), []int{1}
}

func (x *AddDistributionRequest) GetDistributions() []*Distribution {
	if x != nil {
		return x.Distributions
	}
	return nil
}

type AddDistributionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddDistributionReply) Reset() {
	*x = AddDistributionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_distrinution_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDistributionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDistributionReply) ProtoMessage() {}

func (x *AddDistributionReply) ProtoReflect() protoreflect.Message {
	mi := &file_protos_distrinution_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDistributionReply.ProtoReflect.Descriptor instead.
func (*AddDistributionReply) Descriptor() ([]byte, []int) {
	return file_protos_distrinution_proto_rawDescGZIP(), []int{2}
}

type ListDistributionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListDistributionRequest) Reset() {
	*x = ListDistributionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_distrinution_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDistributionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDistributionRequest) ProtoMessage() {}

func (x *ListDistributionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_distrinution_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDistributionRequest.ProtoReflect.Descriptor instead.
func (*ListDistributionRequest) Descriptor() ([]byte, []int) {
	return file_protos_distrinution_proto_rawDescGZIP(), []int{3}
}

type ListDistributionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Distributions []*Distribution `protobuf:"bytes,1,rep,name=distributions,proto3" json:"distributions,omitempty"`
}

func (x *ListDistributionReply) Reset() {
	*x = ListDistributionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_distrinution_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDistributionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDistributionReply) ProtoMessage() {}

func (x *ListDistributionReply) ProtoReflect() protoreflect.Message {
	mi := &file_protos_distrinution_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDistributionReply.ProtoReflect.Descriptor instead.
func (*ListDistributionReply) Descriptor() ([]byte, []int) {
	return file_protos_distrinution_proto_rawDescGZIP(), []int{4}
}

func (x *ListDistributionReply) GetDistributions() []*Distribution {
	if x != nil {
		return x.Distributions
	}
	return nil
}

type DropDistributionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *DropDistributionRequest) Reset() {
	*x = DropDistributionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_distrinution_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropDistributionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropDistributionRequest) ProtoMessage() {}

func (x *DropDistributionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_distrinution_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropDistributionRequest.ProtoReflect.Descriptor instead.
func (*DropDistributionRequest) Descriptor() ([]byte, []int) {
	return file_protos_distrinution_proto_rawDescGZIP(), []int{5}
}

func (x *DropDistributionRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DropDistributionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DropDistributionReply) Reset() {
	*x = DropDistributionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_distrinution_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropDistributionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropDistributionReply) ProtoMessage() {}

func (x *DropDistributionReply) ProtoReflect() protoreflect.Message {
	mi := &file_protos_distrinution_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropDistributionReply.ProtoReflect.Descriptor instead.
func (*DropDistributionReply) Descriptor() ([]byte, []int) {
	return file_protos_distrinution_proto_rawDescGZIP(), []int{6}
}

type AlterDistributionAttachRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table     string     `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Distribution *Distribution `protobuf:"bytes,2,opt,name=distrinution,proto3" json:"distrinution,omitempty"`
}

func (x *AlterDistributionAttachRequest) Reset() {
	*x = AlterDistributionAttachRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_distrinution_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlterDistributionAttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterDistributionAttachRequest) ProtoMessage() {}

func (x *AlterDistributionAttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_distrinution_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterDistributionAttachRequest.ProtoReflect.Descriptor instead.
func (*AlterDistributionAttachRequest) Descriptor() ([]byte, []int) {
	return file_protos_distrinution_proto_rawDescGZIP(), []int{7}
}

func (x *AlterDistributionAttachRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *AlterDistributionAttachRequest) GetDistribution() *Distribution {
	if x != nil {
		return x.Distribution
	}
	return nil
}

type AlterDistributionAttachReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AlterDistributionAttachReply) Reset() {
	*x = AlterDistributionAttachReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_distrinution_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlterDistributionAttachReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterDistributionAttachReply) ProtoMessage() {}

func (x *AlterDistributionAttachReply) ProtoReflect() protoreflect.Message {
	mi := &file_protos_distrinution_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterDistributionAttachReply.ProtoReflect.Descriptor instead.
func (*AlterDistributionAttachReply) Descriptor() ([]byte, []int) {
	return file_protos_distrinution_proto_rawDescGZIP(), []int{8}
}

type GetDistributionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table string `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
}

func (x *GetDistributionRequest) Reset() {
	*x = GetDistributionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_distrinution_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDistributionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistributionRequest) ProtoMessage() {}

func (x *GetDistributionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_distrinution_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistributionRequest.ProtoReflect.Descriptor instead.
func (*GetDistributionRequest) Descriptor() ([]byte, []int) {
	return file_protos_distrinution_proto_rawDescGZIP(), []int{9}
}

func (x *GetDistributionRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

type GetDistributionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Distribution *Distribution `protobuf:"bytes,1,opt,name=distrinution,proto3" json:"distrinution,omitempty"`
}

func (x *GetDistributionReply) Reset() {
	*x = GetDistributionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_distrinution_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDistributionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistributionReply) ProtoMessage() {}

func (x *GetDistributionReply) ProtoReflect() protoreflect.Message {
	mi := &file_protos_distrinution_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistributionReply.ProtoReflect.Descriptor instead.
func (*GetDistributionReply) Descriptor() ([]byte, []int) {
	return file_protos_distrinution_proto_rawDescGZIP(), []int{10}
}

func (x *GetDistributionReply) GetDistribution() *Distribution {
	if x != nil {
		return x.Distribution
	}
	return nil
}

var File_protos_distrinution_proto protoreflect.FileDescriptor

var file_protos_distrinution_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x70, 0x71, 0x72, 0x22, 0x1b,
	0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x46, 0x0a, 0x13, 0x41,
	0x64, 0x64, 0x44, 0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2f, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x70, 0x71, 0x72, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x44, 0x61, 0x74, 0x61, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x45, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2f, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x70, 0x71,
	0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x0a, 0x64, 0x61, 0x74,
	0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x22, 0x28, 0x0a, 0x14, 0x44, 0x72, 0x6f, 0x70, 0x44,
	0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64,
	0x73, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x72, 0x6f, 0x70, 0x44, 0x61, 0x74, 0x61, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x5f, 0x0a, 0x18, 0x41, 0x74, 0x74, 0x61, 0x63,
	0x68, 0x54, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x64, 0x61, 0x74,
	0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73,
	0x70, 0x71, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x09, 0x64,
	0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x18, 0x0a, 0x16, 0x41, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x54, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x2b, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x22,
	0x42, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x2d, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x70, 0x71, 0x72, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x32, 0x85, 0x03, 0x0a, 0x10, 0x44, 0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x44,
	0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x19, 0x2e, 0x73, 0x70, 0x71, 0x72, 0x2e,
	0x41, 0x64, 0x64, 0x44, 0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x70, 0x71, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x47,
	0x0a, 0x0d, 0x44, 0x72, 0x6f, 0x70, 0x44, 0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12,
	0x1a, 0x2e, 0x73, 0x70, 0x71, 0x72, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x44, 0x61, 0x74, 0x61, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x70,
	0x71, 0x72, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x44, 0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x1a, 0x2e, 0x73, 0x70, 0x71, 0x72, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x70, 0x71, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x53, 0x0a, 0x11, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x54, 0x6f, 0x44, 0x61, 0x74, 0x61,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x1e, 0x2e, 0x73, 0x70, 0x71, 0x72, 0x2e, 0x41, 0x74, 0x74,
	0x61, 0x63, 0x68, 0x54, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x70, 0x71, 0x72, 0x2e, 0x41, 0x74, 0x74,
	0x61, 0x63, 0x68, 0x54, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x19, 0x2e, 0x73, 0x70, 0x71, 0x72, 0x2e, 0x47, 0x65, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x73, 0x70, 0x71, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x73,
	0x70, 0x71, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protos_distrinution_proto_rawDescOnce sync.Once
	file_protos_distrinution_proto_rawDescData = file_protos_distrinution_proto_rawDesc
)

func file_protos_distrinution_proto_rawDescGZIP() []byte {
	file_protos_distrinution_proto_rawDescOnce.Do(func() {
		file_protos_distrinution_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_distrinution_proto_rawDescData)
	})
	return file_protos_distrinution_proto_rawDescData
}

var file_protos_distrinution_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_protos_distrinution_proto_goTypes = []interface{}{
	(*Distribution)(nil),                // 0: spqr.Distribution
	(*AddDistributionRequest)(nil),      // 1: spqr.AddDistributionRequest
	(*AddDistributionReply)(nil),        // 2: spqr.AddDistributionReply
	(*ListDistributionRequest)(nil),     // 3: spqr.ListDistributionRequest
	(*ListDistributionReply)(nil),       // 4: spqr.ListDistributionReply
	(*DropDistributionRequest)(nil),     // 5: spqr.DropDistributionRequest
	(*DropDistributionReply)(nil),       // 6: spqr.DropDistributionReply
	(*AlterDistributionAttachRequest)(nil), // 7: spqr.AlterDistributionAttachRequest
	(*AlterDistributionAttachReply)(nil),   // 8: spqr.AlterDistributionAttachReply
	(*GetDistributionRequest)(nil),      // 9: spqr.GetDistributionRequest
	(*GetDistributionReply)(nil),        // 10: spqr.GetDistributionReply
}
var file_protos_distrinution_proto_depIdxs = []int32{
	0,  // 0: spqr.AddDistributionRequest.distributions:type_name -> spqr.Distribution
	0,  // 1: spqr.ListDistributionReply.distributions:type_name -> spqr.Distribution
	0,  // 2: spqr.AlterDistributionAttachRequest.distrinution:type_name -> spqr.Distribution
	0,  // 3: spqr.GetDistributionReply.distrinution:type_name -> spqr.Distribution
	1,  // 4: spqr.DistributionService.AddDistribution:input_type -> spqr.AddDistributionRequest
	5,  // 5: spqr.DistributionService.DropDistribution:input_type -> spqr.DropDistributionRequest
	3,  // 6: spqr.DistributionService.ListDistribution:input_type -> spqr.ListDistributionRequest
	7,  // 7: spqr.DistributionService.AlterDistributionAttach:input_type -> spqr.AlterDistributionAttachRequest
	9,  // 8: spqr.DistributionService.GetDistribution:input_type -> spqr.GetDistributionRequest
	2,  // 9: spqr.DistributionService.AddDistribution:output_type -> spqr.AddDistributionReply
	6,  // 10: spqr.DistributionService.DropDistribution:output_type -> spqr.DropDistributionReply
	4,  // 11: spqr.DistributionService.ListDistribution:output_type -> spqr.ListDistributionReply
	8,  // 12: spqr.DistributionService.AlterDistributionAttach:output_type -> spqr.AlterDistributionAttachReply
	10, // 13: spqr.DistributionService.GetDistribution:output_type -> spqr.GetDistributionReply
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_protos_distrinution_proto_init() }
func file_protos_distrinution_proto_init() {
	if File_protos_distrinution_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_distrinution_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Distribution); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_distrinution_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDistributionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_distrinution_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDistributionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_distrinution_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDistributionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_distrinution_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDistributionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_distrinution_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropDistributionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_distrinution_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropDistributionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_distrinution_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlterDistributionAttachRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_distrinution_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlterDistributionAttachReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_distrinution_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDistributionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_distrinution_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDistributionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_distrinution_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_distrinution_proto_goTypes,
		DependencyIndexes: file_protos_distrinution_proto_depIdxs,
		MessageInfos:      file_protos_distrinution_proto_msgTypes,
	}.Build()
	File_protos_distrinution_proto = out.File
	file_protos_distrinution_proto_rawDesc = nil
	file_protos_distrinution_proto_goTypes = nil
	file_protos_distrinution_proto_depIdxs = nil
}
