// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: protos/pools.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPoolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pools         []*PoolInfo            `protobuf:"bytes,1,rep,name=pools,proto3" json:"pools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoolsResponse) Reset() {
	*x = ListPoolsResponse{}
	mi := &file_protos_pools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoolsResponse) ProtoMessage() {}

func (x *ListPoolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoolsResponse.ProtoReflect.Descriptor instead.
func (*ListPoolsResponse) Descriptor() ([]byte, []int) {
	return file_protos_pools_proto_rawDescGZIP(), []int{0}
}

func (x *ListPoolsResponse) GetPools() []*PoolInfo {
	if x != nil {
		return x.Pools
	}
	return nil
}

type PoolInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	DB            string                 `protobuf:"bytes,2,opt,name=DB,proto3" json:"DB,omitempty"`
	Usr           string                 `protobuf:"bytes,3,opt,name=Usr,proto3" json:"Usr,omitempty"`
	Host          string                 `protobuf:"bytes,4,opt,name=Host,proto3" json:"Host,omitempty"`
	ConnCount     int64                  `protobuf:"varint,5,opt,name=ConnCount,proto3" json:"ConnCount,omitempty"`
	IdleConnCount int64                  `protobuf:"varint,6,opt,name=IdleConnCount,proto3" json:"IdleConnCount,omitempty"`
	QueueSize     int64                  `protobuf:"varint,7,opt,name=QueueSize,proto3" json:"QueueSize,omitempty"`
	RouterName    string                 `protobuf:"bytes,8,opt,name=RouterName,proto3" json:"RouterName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolInfo) Reset() {
	*x = PoolInfo{}
	mi := &file_protos_pools_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolInfo) ProtoMessage() {}

func (x *PoolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pools_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolInfo.ProtoReflect.Descriptor instead.
func (*PoolInfo) Descriptor() ([]byte, []int) {
	return file_protos_pools_proto_rawDescGZIP(), []int{1}
}

func (x *PoolInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PoolInfo) GetDB() string {
	if x != nil {
		return x.DB
	}
	return ""
}

func (x *PoolInfo) GetUsr() string {
	if x != nil {
		return x.Usr
	}
	return ""
}

func (x *PoolInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *PoolInfo) GetConnCount() int64 {
	if x != nil {
		return x.ConnCount
	}
	return 0
}

func (x *PoolInfo) GetIdleConnCount() int64 {
	if x != nil {
		return x.IdleConnCount
	}
	return 0
}

func (x *PoolInfo) GetQueueSize() int64 {
	if x != nil {
		return x.QueueSize
	}
	return 0
}

func (x *PoolInfo) GetRouterName() string {
	if x != nil {
		return x.RouterName
	}
	return ""
}

var File_protos_pools_proto protoreflect.FileDescriptor

const file_protos_pools_proto_rawDesc = "" +
	"\n" +
	"\x12protos/pools.proto\x12\x04spqr\x1a\x1bgoogle/protobuf/empty.proto\"9\n" +
	"\x11ListPoolsResponse\x12$\n" +
	"\x05pools\x18\x01 \x03(\v2\x0e.spqr.PoolInfoR\x05pools\"\xd2\x01\n" +
	"\bPoolInfo\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x0e\n" +
	"\x02DB\x18\x02 \x01(\tR\x02DB\x12\x10\n" +
	"\x03Usr\x18\x03 \x01(\tR\x03Usr\x12\x12\n" +
	"\x04Host\x18\x04 \x01(\tR\x04Host\x12\x1c\n" +
	"\tConnCount\x18\x05 \x01(\x03R\tConnCount\x12$\n" +
	"\rIdleConnCount\x18\x06 \x01(\x03R\rIdleConnCount\x12\x1c\n" +
	"\tQueueSize\x18\a \x01(\x03R\tQueueSize\x12\x1e\n" +
	"\n" +
	"RouterName\x18\b \x01(\tR\n" +
	"RouterName2M\n" +
	"\vPoolService\x12>\n" +
	"\tListPools\x12\x16.google.protobuf.Empty\x1a\x17.spqr.ListPoolsResponse\"\x00B\fZ\n" +
	"spqr/protob\x06proto3"

var (
	file_protos_pools_proto_rawDescOnce sync.Once
	file_protos_pools_proto_rawDescData []byte
)

func file_protos_pools_proto_rawDescGZIP() []byte {
	file_protos_pools_proto_rawDescOnce.Do(func() {
		file_protos_pools_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_pools_proto_rawDesc), len(file_protos_pools_proto_rawDesc)))
	})
	return file_protos_pools_proto_rawDescData
}

var file_protos_pools_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_pools_proto_goTypes = []any{
	(*ListPoolsResponse)(nil), // 0: spqr.ListPoolsResponse
	(*PoolInfo)(nil),          // 1: spqr.PoolInfo
	(*emptypb.Empty)(nil),     // 2: google.protobuf.Empty
}
var file_protos_pools_proto_depIdxs = []int32{
	1, // 0: spqr.ListPoolsResponse.pools:type_name -> spqr.PoolInfo
	2, // 1: spqr.PoolService.ListPools:input_type -> google.protobuf.Empty
	0, // 2: spqr.PoolService.ListPools:output_type -> spqr.ListPoolsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_pools_proto_init() }
func file_protos_pools_proto_init() {
	if File_protos_pools_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_pools_proto_rawDesc), len(file_protos_pools_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_pools_proto_goTypes,
		DependencyIndexes: file_protos_pools_proto_depIdxs,
		MessageInfos:      file_protos_pools_proto_msgTypes,
	}.Build()
	File_protos_pools_proto = out.File
	file_protos_pools_proto_goTypes = nil
	file_protos_pools_proto_depIdxs = nil
}
