// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/shard.proto

package proto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Shard struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hosts                []string `protobuf:"bytes,2,rep,name=hosts,proto3" json:"hosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Shard) Reset()         { *m = Shard{} }
func (m *Shard) String() string { return proto.CompactTextString(m) }
func (*Shard) ProtoMessage()    {}
func (*Shard) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbd61f9541009b59, []int{0}
}

func (m *Shard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shard.Unmarshal(m, b)
}
func (m *Shard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shard.Marshal(b, m, deterministic)
}
func (m *Shard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shard.Merge(m, src)
}
func (m *Shard) XXX_Size() int {
	return xxx_messageInfo_Shard.Size(m)
}
func (m *Shard) XXX_DiscardUnknown() {
	xxx_messageInfo_Shard.DiscardUnknown(m)
}

var xxx_messageInfo_Shard proto.InternalMessageInfo

func (m *Shard) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Shard) GetHosts() []string {
	if m != nil {
		return m.Hosts
	}
	return nil
}

type ShardInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hosts                []string `protobuf:"bytes,2,rep,name=hosts,proto3" json:"hosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardInfo) Reset()         { *m = ShardInfo{} }
func (m *ShardInfo) String() string { return proto.CompactTextString(m) }
func (*ShardInfo) ProtoMessage()    {}
func (*ShardInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbd61f9541009b59, []int{1}
}

func (m *ShardInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardInfo.Unmarshal(m, b)
}
func (m *ShardInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardInfo.Marshal(b, m, deterministic)
}
func (m *ShardInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardInfo.Merge(m, src)
}
func (m *ShardInfo) XXX_Size() int {
	return xxx_messageInfo_ShardInfo.Size(m)
}
func (m *ShardInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ShardInfo proto.InternalMessageInfo

func (m *ShardInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ShardInfo) GetHosts() []string {
	if m != nil {
		return m.Hosts
	}
	return nil
}

type ShardInfoReply struct {
	ShardInfo            *ShardInfo `protobuf:"bytes,1,opt,name=shard_info,json=shardInfo,proto3" json:"shard_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ShardInfoReply) Reset()         { *m = ShardInfoReply{} }
func (m *ShardInfoReply) String() string { return proto.CompactTextString(m) }
func (*ShardInfoReply) ProtoMessage()    {}
func (*ShardInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbd61f9541009b59, []int{2}
}

func (m *ShardInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardInfoReply.Unmarshal(m, b)
}
func (m *ShardInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardInfoReply.Marshal(b, m, deterministic)
}
func (m *ShardInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardInfoReply.Merge(m, src)
}
func (m *ShardInfoReply) XXX_Size() int {
	return xxx_messageInfo_ShardInfoReply.Size(m)
}
func (m *ShardInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_ShardInfoReply proto.InternalMessageInfo

func (m *ShardInfoReply) GetShardInfo() *ShardInfo {
	if m != nil {
		return m.ShardInfo
	}
	return nil
}

type ListShardsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListShardsRequest) Reset()         { *m = ListShardsRequest{} }
func (m *ListShardsRequest) String() string { return proto.CompactTextString(m) }
func (*ListShardsRequest) ProtoMessage()    {}
func (*ListShardsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbd61f9541009b59, []int{3}
}

func (m *ListShardsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListShardsRequest.Unmarshal(m, b)
}
func (m *ListShardsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListShardsRequest.Marshal(b, m, deterministic)
}
func (m *ListShardsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListShardsRequest.Merge(m, src)
}
func (m *ListShardsRequest) XXX_Size() int {
	return xxx_messageInfo_ListShardsRequest.Size(m)
}
func (m *ListShardsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListShardsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListShardsRequest proto.InternalMessageInfo

type ShardRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardRequest) Reset()         { *m = ShardRequest{} }
func (m *ShardRequest) String() string { return proto.CompactTextString(m) }
func (*ShardRequest) ProtoMessage()    {}
func (*ShardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbd61f9541009b59, []int{4}
}

func (m *ShardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardRequest.Unmarshal(m, b)
}
func (m *ShardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardRequest.Marshal(b, m, deterministic)
}
func (m *ShardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardRequest.Merge(m, src)
}
func (m *ShardRequest) XXX_Size() int {
	return xxx_messageInfo_ShardRequest.Size(m)
}
func (m *ShardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShardRequest proto.InternalMessageInfo

func (m *ShardRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListShardsReply struct {
	Shards               []*Shard `protobuf:"bytes,1,rep,name=shards,proto3" json:"shards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListShardsReply) Reset()         { *m = ListShardsReply{} }
func (m *ListShardsReply) String() string { return proto.CompactTextString(m) }
func (*ListShardsReply) ProtoMessage()    {}
func (*ListShardsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbd61f9541009b59, []int{5}
}

func (m *ListShardsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListShardsReply.Unmarshal(m, b)
}
func (m *ListShardsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListShardsReply.Marshal(b, m, deterministic)
}
func (m *ListShardsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListShardsReply.Merge(m, src)
}
func (m *ListShardsReply) XXX_Size() int {
	return xxx_messageInfo_ListShardsReply.Size(m)
}
func (m *ListShardsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListShardsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListShardsReply proto.InternalMessageInfo

func (m *ListShardsReply) GetShards() []*Shard {
	if m != nil {
		return m.Shards
	}
	return nil
}

type AddShardRequest struct {
	Shard                *Shard   `protobuf:"bytes,1,opt,name=shard,proto3" json:"shard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddShardRequest) Reset()         { *m = AddShardRequest{} }
func (m *AddShardRequest) String() string { return proto.CompactTextString(m) }
func (*AddShardRequest) ProtoMessage()    {}
func (*AddShardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbd61f9541009b59, []int{6}
}

func (m *AddShardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddShardRequest.Unmarshal(m, b)
}
func (m *AddShardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddShardRequest.Marshal(b, m, deterministic)
}
func (m *AddShardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddShardRequest.Merge(m, src)
}
func (m *AddShardRequest) XXX_Size() int {
	return xxx_messageInfo_AddShardRequest.Size(m)
}
func (m *AddShardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddShardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddShardRequest proto.InternalMessageInfo

func (m *AddShardRequest) GetShard() *Shard {
	if m != nil {
		return m.Shard
	}
	return nil
}

type AddShardReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddShardReply) Reset()         { *m = AddShardReply{} }
func (m *AddShardReply) String() string { return proto.CompactTextString(m) }
func (*AddShardReply) ProtoMessage()    {}
func (*AddShardReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbd61f9541009b59, []int{7}
}

func (m *AddShardReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddShardReply.Unmarshal(m, b)
}
func (m *AddShardReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddShardReply.Marshal(b, m, deterministic)
}
func (m *AddShardReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddShardReply.Merge(m, src)
}
func (m *AddShardReply) XXX_Size() int {
	return xxx_messageInfo_AddShardReply.Size(m)
}
func (m *AddShardReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddShardReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddShardReply proto.InternalMessageInfo

type AddWorldShardRequest struct {
	Shard                *Shard   `protobuf:"bytes,1,opt,name=shard,proto3" json:"shard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddWorldShardRequest) Reset()         { *m = AddWorldShardRequest{} }
func (m *AddWorldShardRequest) String() string { return proto.CompactTextString(m) }
func (*AddWorldShardRequest) ProtoMessage()    {}
func (*AddWorldShardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbd61f9541009b59, []int{8}
}

func (m *AddWorldShardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddWorldShardRequest.Unmarshal(m, b)
}
func (m *AddWorldShardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddWorldShardRequest.Marshal(b, m, deterministic)
}
func (m *AddWorldShardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddWorldShardRequest.Merge(m, src)
}
func (m *AddWorldShardRequest) XXX_Size() int {
	return xxx_messageInfo_AddWorldShardRequest.Size(m)
}
func (m *AddWorldShardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddWorldShardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddWorldShardRequest proto.InternalMessageInfo

func (m *AddWorldShardRequest) GetShard() *Shard {
	if m != nil {
		return m.Shard
	}
	return nil
}

func init() {
	proto.RegisterType((*Shard)(nil), "spqr.Shard")
	proto.RegisterType((*ShardInfo)(nil), "spqr.ShardInfo")
	proto.RegisterType((*ShardInfoReply)(nil), "spqr.ShardInfoReply")
	proto.RegisterType((*ListShardsRequest)(nil), "spqr.ListShardsRequest")
	proto.RegisterType((*ShardRequest)(nil), "spqr.ShardRequest")
	proto.RegisterType((*ListShardsReply)(nil), "spqr.ListShardsReply")
	proto.RegisterType((*AddShardRequest)(nil), "spqr.AddShardRequest")
	proto.RegisterType((*AddShardReply)(nil), "spqr.AddShardReply")
	proto.RegisterType((*AddWorldShardRequest)(nil), "spqr.AddWorldShardRequest")
}

func init() { proto.RegisterFile("protos/shard.proto", fileDescriptor_fbd61f9541009b59) }

var fileDescriptor_fbd61f9541009b59 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x5d, 0xe7, 0x06, 0x7d, 0xab, 0x2b, 0x66, 0x13, 0x4b, 0x0f, 0x52, 0xe3, 0xa5, 0x17,
	0x3b, 0xac, 0x22, 0x28, 0x22, 0x76, 0x08, 0x22, 0x78, 0xea, 0x0e, 0x82, 0x17, 0xa9, 0x26, 0x63,
	0x85, 0xb2, 0x74, 0x4d, 0x14, 0xf6, 0x3f, 0xf8, 0x47, 0x4b, 0x93, 0xb8, 0x76, 0x2d, 0x82, 0x9e,
	0xda, 0xbc, 0xef, 0xfd, 0x5e, 0xbe, 0xaf, 0x7d, 0x80, 0xf2, 0x82, 0x09, 0xc6, 0x27, 0x7c, 0x91,
	0x14, 0x24, 0x90, 0x07, 0xb4, 0xcb, 0xf3, 0x55, 0x81, 0x4f, 0xa1, 0x37, 0x2b, 0x8b, 0x68, 0x08,
	0x46, 0x4a, 0x9c, 0x8e, 0xd7, 0xf1, 0xcd, 0xd8, 0x48, 0x09, 0x1a, 0x43, 0x6f, 0xc1, 0xb8, 0xe0,
	0x8e, 0xe1, 0x75, 0x7d, 0x33, 0x56, 0x07, 0x7c, 0x06, 0xa6, 0x6c, 0x7f, 0x5c, 0xce, 0xd9, 0x1f,
	0x91, 0x3b, 0x18, 0x6e, 0x90, 0x98, 0xe6, 0xd9, 0x1a, 0x05, 0x00, 0xd2, 0xc8, 0x6b, 0xba, 0x9c,
	0x33, 0xc9, 0x0f, 0x42, 0x3b, 0x28, 0xed, 0x04, 0x55, 0xa7, 0xc9, 0x7f, 0x5e, 0xf1, 0x08, 0xf6,
	0x9f, 0x52, 0x2e, 0xa4, 0xc6, 0x63, 0xba, 0xfa, 0xa0, 0x5c, 0xe0, 0x23, 0xb0, 0x64, 0x41, 0x9f,
	0x9b, 0x66, 0xf0, 0x25, 0xd8, 0x75, 0xa8, 0xbc, 0xf7, 0x04, 0xfa, 0x72, 0x28, 0x77, 0x3a, 0x5e,
	0xd7, 0x1f, 0x84, 0x83, 0xda, 0x9d, 0xb1, 0x96, 0xf0, 0x05, 0xd8, 0x11, 0x21, 0x5b, 0xa3, 0x8f,
	0xa1, 0x27, 0x45, 0x6d, 0x75, 0x0b, 0x53, 0x0a, 0xb6, 0x61, 0xaf, 0xa2, 0xf2, 0x6c, 0x8d, 0xaf,
	0x60, 0x1c, 0x11, 0xf2, 0xcc, 0x8a, 0xec, 0xbf, 0xb3, 0xc2, 0x2f, 0x43, 0x47, 0x9b, 0xd1, 0xe2,
	0x33, 0x7d, 0xa7, 0xe8, 0x16, 0xa0, 0x8a, 0x82, 0x0e, 0x15, 0xd2, 0xfa, 0x22, 0xee, 0x41, 0x5b,
	0x28, 0x9d, 0xec, 0xa0, 0x1b, 0xb0, 0x22, 0x42, 0xee, 0x13, 0x91, 0xa8, 0x5f, 0xad, 0x1b, 0x1b,
	0x31, 0xdd, 0x51, 0xb3, 0xac, 0xe8, 0xa9, 0x8c, 0x56, 0x25, 0x41, 0xee, 0xa6, 0xaf, 0x15, 0xef,
	0xb7, 0x19, 0xd7, 0x60, 0x3d, 0x50, 0x51, 0x6d, 0x0e, 0xaa, 0xc7, 0xd6, 0xe8, 0xb8, 0xb9, 0x01,
	0x8a, 0x9d, 0x5a, 0x2f, 0x50, 0x0a, 0x13, 0xb9, 0xb5, 0x6f, 0x7d, 0xf9, 0x38, 0xff, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0xd5, 0xe9, 0xb4, 0x7b, 0xd2, 0x02, 0x00, 0x00,
}
