// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: protos/sharding_rules.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShardingRulesService_AddShardingRules_FullMethodName  = "/spqr.ShardingRulesService/AddShardingRules"
	ShardingRulesService_DropShardingRules_FullMethodName = "/spqr.ShardingRulesService/DropShardingRules"
	ShardingRulesService_ListShardingRules_FullMethodName = "/spqr.ShardingRulesService/ListShardingRules"
)

// ShardingRulesServiceClient is the client API for ShardingRulesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShardingRulesServiceClient interface {
	// Deprecated: Do not use.
	AddShardingRules(ctx context.Context, in *AddShardingRuleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Deprecated: Do not use.
	DropShardingRules(ctx context.Context, in *DropShardingRuleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Deprecated: Do not use.
	ListShardingRules(ctx context.Context, in *ListShardingRuleRequest, opts ...grpc.CallOption) (*ListShardingRuleReply, error)
}

type shardingRulesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShardingRulesServiceClient(cc grpc.ClientConnInterface) ShardingRulesServiceClient {
	return &shardingRulesServiceClient{cc}
}

// Deprecated: Do not use.
func (c *shardingRulesServiceClient) AddShardingRules(ctx context.Context, in *AddShardingRuleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ShardingRulesService_AddShardingRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *shardingRulesServiceClient) DropShardingRules(ctx context.Context, in *DropShardingRuleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ShardingRulesService_DropShardingRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *shardingRulesServiceClient) ListShardingRules(ctx context.Context, in *ListShardingRuleRequest, opts ...grpc.CallOption) (*ListShardingRuleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShardingRuleReply)
	err := c.cc.Invoke(ctx, ShardingRulesService_ListShardingRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShardingRulesServiceServer is the server API for ShardingRulesService service.
// All implementations must embed UnimplementedShardingRulesServiceServer
// for forward compatibility.
type ShardingRulesServiceServer interface {
	// Deprecated: Do not use.
	AddShardingRules(context.Context, *AddShardingRuleRequest) (*emptypb.Empty, error)
	// Deprecated: Do not use.
	DropShardingRules(context.Context, *DropShardingRuleRequest) (*emptypb.Empty, error)
	// Deprecated: Do not use.
	ListShardingRules(context.Context, *ListShardingRuleRequest) (*ListShardingRuleReply, error)
	mustEmbedUnimplementedShardingRulesServiceServer()
}

// UnimplementedShardingRulesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShardingRulesServiceServer struct{}

func (UnimplementedShardingRulesServiceServer) AddShardingRules(context.Context, *AddShardingRuleRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddShardingRules not implemented")
}
func (UnimplementedShardingRulesServiceServer) DropShardingRules(context.Context, *DropShardingRuleRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropShardingRules not implemented")
}
func (UnimplementedShardingRulesServiceServer) ListShardingRules(context.Context, *ListShardingRuleRequest) (*ListShardingRuleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListShardingRules not implemented")
}
func (UnimplementedShardingRulesServiceServer) mustEmbedUnimplementedShardingRulesServiceServer() {}
func (UnimplementedShardingRulesServiceServer) testEmbeddedByValue()                              {}

// UnsafeShardingRulesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShardingRulesServiceServer will
// result in compilation errors.
type UnsafeShardingRulesServiceServer interface {
	mustEmbedUnimplementedShardingRulesServiceServer()
}

func RegisterShardingRulesServiceServer(s grpc.ServiceRegistrar, srv ShardingRulesServiceServer) {
	// If the following call pancis, it indicates UnimplementedShardingRulesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShardingRulesService_ServiceDesc, srv)
}

func _ShardingRulesService_AddShardingRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddShardingRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardingRulesServiceServer).AddShardingRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardingRulesService_AddShardingRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardingRulesServiceServer).AddShardingRules(ctx, req.(*AddShardingRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardingRulesService_DropShardingRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropShardingRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardingRulesServiceServer).DropShardingRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardingRulesService_DropShardingRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardingRulesServiceServer).DropShardingRules(ctx, req.(*DropShardingRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardingRulesService_ListShardingRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShardingRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardingRulesServiceServer).ListShardingRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardingRulesService_ListShardingRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardingRulesServiceServer).ListShardingRules(ctx, req.(*ListShardingRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShardingRulesService_ServiceDesc is the grpc.ServiceDesc for ShardingRulesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShardingRulesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spqr.ShardingRulesService",
	HandlerType: (*ShardingRulesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddShardingRules",
			Handler:    _ShardingRulesService_AddShardingRules_Handler,
		},
		{
			MethodName: "DropShardingRules",
			Handler:    _ShardingRulesService_DropShardingRules_Handler,
		},
		{
			MethodName: "ListShardingRules",
			Handler:    _ShardingRulesService_ListShardingRules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/sharding_rules.proto",
}
