// Code generated by goyacc -o gram.go -p yy gram.y. DO NOT EDIT.

//line gram.y:3
package spqrparser

import __yyfmt__ "fmt"

//line gram.y:3

import (
	"fmt"

	"crypto/rand"
	"encoding/binary"
	"encoding/hex"
	"github.com/pg-sharding/lyx/lyx"
	"github.com/pg-sharding/spqr/qdb"
	"github.com/pg-sharding/spqr/router/rfqn"
	"math"
	"strings"
)

const SIGNED_INT_RANGE_ERROR string = "the Signed Value should be at the range of [-9223372036854775808, 9223372036854775807]."

func randomHex(n int) (string, error) {
	bytes := make([]byte, n)
	if _, err := rand.Read(bytes); err != nil {
		return "", err
	}
	return hex.EncodeToString(bytes), nil
}

//line gram.y:31
type yySymType struct {
	yys          int
	str          string
	strlist      []string
	byte         byte
	bytes        []byte
	integer      int
	uinteger     uint
	uintegerlist []uint
	bool         bool
	empty        struct{}

	set       *Set
	statement Statement
	show      *Show

	drop   *Drop
	create *Create

	kill   *Kill
	lock   *Lock
	unlock *Unlock

	krbound *KeyRangeBound

	qname         *rfqn.RelationFQN
	ds            *DistributionDefinition
	kr            *KeyRangeDefinition
	shard         *ShardDefinition
	sharding_rule *ShardingRuleDefinition

	register_router   *RegisterRouter
	unregister_router *UnregisterRouter

	split *SplitKeyRange
	move  *MoveKeyRange
	unite *UniteKeyRange

	redistribute *RedistributeKeyRange

	invalidate            *Invalidate
	sync_reference_tables *SyncReferenceTables

	shutdown *Shutdown
	listen   *Listen

	trace     *TraceStmt
	stoptrace *StopTraceStmt

	distribution *DistributionDefinition

	alter                *Alter
	alter_distribution   *AlterDistribution
	distributed_relation *DistributedRelation
	alter_default_shard  *AlterDefaultShard

	relations    []*DistributedRelation
	relation     *DistributedRelation
	entrieslist  []ShardingRuleEntry
	dEntrieslist []DistributionKeyEntry

	shruleEntry ShardingRuleEntry

	distrKeyEntry DistributionKeyEntry
	aiEntry       *AutoIncrementEntry

	sharding_rule_selector *ShardingRuleSelector
	key_range_selector     *KeyRangeSelector
	distribution_selector  *DistributionSelector
	aiEntrieslist          []*AutoIncrementEntry

	colref     ColumnRef
	colreflist []ColumnRef
	where      lyx.Node
	expr       lyx.Node

	order_clause OrderClause
	opt_asc_desc OptAscDesc

	group_clause GroupByClause

	retryMoveTaskGroup *RetryMoveTaskGroup
	stopMoveTaskGroup  *StopMoveTaskGroup

	typedColRef TypedColRef
	routingExpr []TypedColRef

	alter_relation *AlterRelationV2
}

const IDENT = 57346
const COMMAND = 57347
const SHOW = 57348
const KILL = 57349
const WHERE = 57350
const OR = 57351
const AND = 57352
const TEQ = 57353
const TCOMMA = 57354
const TDOT = 57355
const SCONST = 57356
const ICONST = 57357
const INVALID_ICONST = 57358
const TSEMICOLON = 57359
const TMINUS = 57360
const TPLUS = 57361
const TMUL = 57362
const TLESS = 57363
const TGREATER = 57364
const TOPENBR = 57365
const TCLOSEBR = 57366
const TOPENSQBR = 57367
const TCLOSESQBR = 57368
const NOT = 57369
const SHUTDOWN = 57370
const LISTEN = 57371
const REGISTER = 57372
const UNREGISTER = 57373
const ROUTER = 57374
const ROUTE = 57375
const CREATE = 57376
const ADD = 57377
const DROP = 57378
const LOCK = 57379
const UNLOCK = 57380
const SPLIT = 57381
const MOVE = 57382
const COMPOSE = 57383
const SET = 57384
const CASCADE = 57385
const ATTACH = 57386
const ALTER = 57387
const DETACH = 57388
const REDISTRIBUTE = 57389
const REFERENCE = 57390
const CHECK = 57391
const APPLY = 57392
const SHARDING = 57393
const COLUMN = 57394
const TABLE = 57395
const TABLES = 57396
const RELATIONS = 57397
const BACKENDS = 57398
const HASH = 57399
const FUNCTION = 57400
const KEY = 57401
const RANGE = 57402
const DISTRIBUTION = 57403
const RELATION = 57404
const REPLICATED = 57405
const AUTO = 57406
const INCREMENT = 57407
const SEQUENCE = 57408
const SCHEMA = 57409
const SHARDS = 57410
const KEY_RANGES = 57411
const ROUTERS = 57412
const SHARD = 57413
const HOST = 57414
const SHARDING_RULES = 57415
const RULE = 57416
const COLUMNS = 57417
const VERSION = 57418
const HOSTS = 57419
const SEQUENCES = 57420
const IS_READ_ONLY = 57421
const MOVE_STATS = 57422
const BY = 57423
const FROM = 57424
const TO = 57425
const WITH = 57426
const UNITE = 57427
const ALL = 57428
const ADDRESS = 57429
const FOR = 57430
const CLIENT = 57431
const BATCH = 57432
const SIZE = 57433
const INVALIDATE = 57434
const CACHE = 57435
const SYNC = 57436
const RETRY = 57437
const DISTRIBUTED = 57438
const IN = 57439
const ON = 57440
const DEFAULT = 57441
const IDENTITY = 57442
const MURMUR = 57443
const CITY = 57444
const START = 57445
const STOP = 57446
const TRACE = 57447
const MESSAGES = 57448
const TASK = 57449
const GROUP = 57450
const VARCHAR = 57451
const INTEGER = 57452
const INT = 57453
const TYPES = 57454
const UUID = 57455
const OP = 57456
const ASC = 57457
const DESC = 57458
const ORDER = 57459

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"COMMAND",
	"SHOW",
	"KILL",
	"WHERE",
	"OR",
	"AND",
	"TEQ",
	"TCOMMA",
	"TDOT",
	"SCONST",
	"ICONST",
	"INVALID_ICONST",
	"TSEMICOLON",
	"TMINUS",
	"TPLUS",
	"TMUL",
	"TLESS",
	"TGREATER",
	"TOPENBR",
	"TCLOSEBR",
	"TOPENSQBR",
	"TCLOSESQBR",
	"NOT",
	"SHUTDOWN",
	"LISTEN",
	"REGISTER",
	"UNREGISTER",
	"ROUTER",
	"ROUTE",
	"CREATE",
	"ADD",
	"DROP",
	"LOCK",
	"UNLOCK",
	"SPLIT",
	"MOVE",
	"COMPOSE",
	"SET",
	"CASCADE",
	"ATTACH",
	"ALTER",
	"DETACH",
	"REDISTRIBUTE",
	"REFERENCE",
	"CHECK",
	"APPLY",
	"SHARDING",
	"COLUMN",
	"TABLE",
	"TABLES",
	"RELATIONS",
	"BACKENDS",
	"HASH",
	"FUNCTION",
	"KEY",
	"RANGE",
	"DISTRIBUTION",
	"RELATION",
	"REPLICATED",
	"AUTO",
	"INCREMENT",
	"SEQUENCE",
	"SCHEMA",
	"SHARDS",
	"KEY_RANGES",
	"ROUTERS",
	"SHARD",
	"HOST",
	"SHARDING_RULES",
	"RULE",
	"COLUMNS",
	"VERSION",
	"HOSTS",
	"SEQUENCES",
	"IS_READ_ONLY",
	"MOVE_STATS",
	"BY",
	"FROM",
	"TO",
	"WITH",
	"UNITE",
	"ALL",
	"ADDRESS",
	"FOR",
	"CLIENT",
	"BATCH",
	"SIZE",
	"INVALIDATE",
	"CACHE",
	"SYNC",
	"RETRY",
	"DISTRIBUTED",
	"IN",
	"ON",
	"DEFAULT",
	"IDENTITY",
	"MURMUR",
	"CITY",
	"START",
	"STOP",
	"TRACE",
	"MESSAGES",
	"TASK",
	"GROUP",
	"VARCHAR",
	"INTEGER",
	"INT",
	"TYPES",
	"UUID",
	"OP",
	"ASC",
	"DESC",
	"ORDER",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line gram.y:1436

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 445

var yyAct = [...]int{

	303, 371, 276, 301, 368, 175, 139, 311, 302, 346,
	238, 236, 305, 223, 284, 230, 237, 229, 222, 119,
	172, 166, 128, 374, 375, 257, 256, 254, 247, 277,
	278, 279, 214, 280, 250, 249, 251, 252, 253, 220,
	322, 116, 66, 192, 181, 158, 133, 125, 106, 257,
	256, 254, 89, 77, 109, 157, 71, 114, 250, 249,
	251, 252, 253, 124, 69, 179, 73, 123, 64, 365,
	219, 76, 210, 110, 131, 132, 74, 134, 306, 307,
	308, 209, 176, 111, 296, 61, 273, 225, 54, 216,
	156, 177, 326, 264, 105, 88, 55, 207, 53, 146,
	147, 121, 170, 131, 122, 104, 110, 65, 56, 67,
	226, 110, 75, 165, 168, 107, 111, 145, 228, 135,
	235, 111, 360, 176, 341, 110, 182, 184, 186, 180,
	255, 103, 177, 63, 189, 111, 190, 184, 110, 110,
	193, 178, 144, 203, 204, 205, 206, 143, 111, 111,
	160, 171, 142, 187, 255, 188, 309, 262, 248, 215,
	225, 217, 110, 127, 112, 54, 33, 34, 227, 306,
	307, 308, 111, 55, 212, 53, 274, 268, 242, 369,
	87, 267, 245, 226, 82, 56, 115, 221, 36, 35,
	41, 42, 297, 185, 27, 26, 30, 31, 32, 37,
	38, 349, 91, 169, 328, 43, 239, 39, 120, 117,
	329, 213, 90, 92, 208, 271, 93, 272, 118, 136,
	183, 148, 241, 244, 265, 102, 287, 288, 282, 266,
	126, 269, 113, 356, 270, 83, 283, 300, 79, 338,
	281, 286, 299, 335, 130, 40, 289, 293, 85, 312,
	334, 333, 44, 239, 46, 45, 167, 84, 117, 161,
	162, 243, 164, 28, 29, 108, 344, 118, 327, 324,
	325, 110, 72, 129, 330, 331, 290, 99, 290, 52,
	323, 111, 152, 153, 98, 352, 51, 336, 387, 385,
	48, 154, 155, 150, 50, 283, 140, 339, 347, 291,
	292, 49, 388, 141, 348, 110, 340, 60, 343, 379,
	312, 342, 350, 195, 59, 111, 101, 353, 351, 380,
	167, 173, 58, 201, 202, 240, 349, 197, 196, 57,
	357, 174, 200, 355, 91, 358, 198, 258, 259, 260,
	294, 261, 361, 363, 90, 92, 290, 354, 93, 332,
	359, 138, 298, 372, 337, 312, 362, 159, 367, 366,
	377, 62, 376, 47, 347, 1, 232, 381, 68, 23,
	386, 384, 383, 382, 22, 389, 231, 233, 370, 263,
	234, 19, 18, 17, 390, 16, 15, 14, 372, 391,
	313, 314, 315, 316, 317, 318, 319, 320, 321, 12,
	78, 80, 13, 8, 9, 191, 94, 95, 96, 97,
	373, 246, 218, 295, 163, 275, 151, 211, 149, 24,
	21, 100, 25, 20, 285, 224, 304, 364, 345, 6,
	5, 4, 3, 7, 11, 10, 86, 81, 70, 2,
	378, 310, 194, 199, 137,
}
var yyPact = [...]int{

	160, -1000, 273, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 114, 37, -37, 2,
	5, 179, 179, 180, 91, 330, -1000, 179, 179, 179,
	179, 252, 245, 164, 38, 8, 217, -1000, -1000, -1000,
	-1000, -1000, -1000, 301, 90, 172, 102, -1000, -1000, -1000,
	-1000, 156, 146, -1000, 15, -39, -44, -61, -1000, 170,
	-1000, 89, 230, 158, 301, -62, 301, 156, -1000, 159,
	-1000, 343, -1000, -1000, -1000, -1000, 281, -1000, -1000, -1000,
	-1000, -1000, -1000, 288, 70, 64, 59, 33, 301, 135,
	-1000, 247, 301, -1000, -3, -1000, -52, -63, 205, 210,
	-1000, -1000, 267, 121, 18, 74, 317, -1000, -1000, -6,
	317, -41, 281, -1000, -64, 301, 134, 107, -1000, -1000,
	230, -1000, 230, 301, -1000, 301, 301, -65, 309, -1000,
	-1000, -1000, 301, 301, 301, 301, 10, -1000, -1000, -1000,
	152, -1000, -18, -27, 146, 149, -1000, -76, 301, -9,
	301, -1000, -1000, -29, -73, 203, 108, 301, 36, 362,
	43, 330, 142, 312, -1000, -1000, 161, 301, 200, -1000,
	-1000, 301, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -89, 77, 40, -1000, -1000, 309, 309, 309, -1000,
	309, -1000, -1000, 76, -1000, 3, -1000, 330, 317, 110,
	106, 146, -1000, 317, 301, -1000, 301, -12, -1000, 105,
	-80, 108, 35, -1000, 184, 301, 301, -1000, 362, 266,
	-1000, -1000, -1000, -1000, 285, 330, 328, -1000, -14, 127,
	348, 301, -1000, 178, 69, -1000, -1000, 75, 301, 309,
	309, 309, 309, 309, 309, 309, 309, 309, 40, 40,
	40, 16, 362, 220, 1, -1000, -1000, 301, -1000, -1000,
	143, -1000, -1000, 301, 301, 337, -1000, 194, 193, 186,
	-1000, 35, -1000, -1000, -1000, -1000, 181, -1000, -1000, 264,
	362, 41, -1000, 328, 330, -1000, 198, 301, -1000, -1000,
	69, 189, -1000, 184, -1000, 260, -1000, -1000, -1000, 301,
	335, -1000, -1000, 40, 40, 40, 40, 40, 40, 40,
	40, 40, -1000, 334, -1000, -1000, 281, -1000, 174, 301,
	-1000, -1000, -80, -1000, -1000, -1000, -1000, -22, -1000, 39,
	-1000, 301, -1000, 328, 330, 331, -1000, -34, 189, 69,
	112, -1000, 301, -92, 301, -1000, 69, -1000, -1000, -1000,
	305, -6, 328, 301, -1000, 281, 112, -1000, 265, 301,
	276, -1000, -80, -1000, -1000, -1000, -1000, 314, -6, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 301, -1000, -1000,
	-1000, -1000,
}
var yyPgo = [...]int{

	0, 444, 443, 140, 442, 15, 17, 7, 441, 16,
	0, 440, 6, 439, 438, 368, 272, 437, 436, 435,
	434, 433, 432, 431, 430, 429, 20, 301, 294, 286,
	279, 18, 3, 10, 428, 427, 13, 4, 5, 8,
	426, 9, 21, 425, 14, 424, 12, 423, 422, 421,
	420, 419, 418, 417, 19, 416, 415, 414, 11, 413,
	2, 22, 412, 411, 410, 405, 404, 403, 402, 399,
	387, 386, 385, 383, 382, 381, 379, 1, 378, 374,
	369, 365, 363, 41, 361, 357, 354,
}
var yyR1 = [...]int{

	0, 81, 82, 82, 13, 13, 13, 13, 13, 13,
	13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
	13, 13, 13, 13, 13, 13, 13, 12, 9, 9,
	9, 9, 10, 10, 11, 11, 26, 26, 26, 7,
	8, 8, 2, 2, 4, 4, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	1, 1, 17, 17, 17, 17, 18, 18, 61, 61,
	21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
	22, 22, 22, 22, 24, 24, 25, 47, 49, 49,
	49, 49, 49, 32, 32, 77, 78, 78, 40, 39,
	39, 54, 54, 33, 33, 34, 34, 41, 35, 35,
	37, 37, 53, 53, 52, 55, 55, 84, 84, 83,
	83, 85, 85, 59, 59, 59, 23, 23, 23, 23,
	23, 38, 38, 38, 48, 64, 64, 64, 63, 63,
	65, 65, 19, 67, 27, 57, 57, 56, 56, 60,
	60, 60, 60, 60, 60, 60, 62, 62, 28, 28,
	31, 31, 36, 42, 42, 43, 43, 46, 46, 46,
	86, 86, 45, 44, 44, 5, 5, 5, 5, 6,
	6, 29, 29, 30, 30, 58, 58, 66, 14, 15,
	16, 70, 20, 71, 72, 72, 72, 76, 76, 73,
	69, 68, 50, 50, 50, 51, 51, 74, 75, 75,
	79, 79, 80, 80,
}
var yyR2 = [...]int{

	0, 2, 0, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 2, 1, 1, 1, 1, 1, 1, 3, 1,
	3, 1, 1, 1, 1, 3, 1, 1, 2, 2,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 2,
	0, 2, 1, 1, 1, 1, 1, 1, 1, 0,
	2, 4, 2, 4, 3, 4, 4, 4, 3, 4,
	2, 2, 2, 2, 4, 4, 3, 2, 2, 4,
	2, 5, 4, 3, 1, 2, 1, 3, 4, 2,
	1, 7, 7, 3, 0, 3, 1, 2, 2, 0,
	2, 0, 1, 2, 2, 6, 5, 1, 0, 1,
	1, 1, 1, 2, 3, 0, 2, 2, 2, 2,
	6, 3, 2, 0, 4, 1, 1, 0, 4, 0,
	3, 0, 5, 2, 4, 3, 0, 3, 1, 1,
	2, 1, 1, 2, 2, 1, 3, 0, 6, 5,
	1, 2, 2, 2, 0, 2, 2, 1, 1, 1,
	1, 0, 3, 1, 0, 1, 1, 1, 2, 1,
	3, 9, 8, 5, 4, 1, 3, 2, 3, 3,
	2, 6, 3, 4, 5, 6, 6, 3, 0, 4,
	2, 1, 2, 3, 2, 5, 6, 5, 3, 3,
	5, 4, 5, 4,
}
var yyChk = [...]int{

	-1000, -81, -13, -22, -23, -24, -25, -21, -67, -66,
	-19, -20, -69, -68, -70, -71, -72, -73, -74, -75,
	-47, -50, -79, -80, -51, -48, 35, 34, 103, 104,
	36, 37, 38, 6, 7, 29, 28, 39, 40, 47,
	85, 30, 31, 45, 92, 95, 94, -82, 17, -27,
	-28, -29, -30, 61, 51, 59, 71, -27, -28, -29,
	-30, 48, -84, 96, 105, 105, 40, 107, -15, 59,
	-14, 51, -16, 61, 71, 107, 66, 48, -15, 59,
	-15, -17, 4, 55, 77, 68, -18, 89, 4, -9,
	14, 4, 15, 18, -15, -15, -15, -15, 32, 32,
	-49, -16, 61, 93, 67, 56, 40, 107, 48, -10,
	4, 14, 74, 60, -10, 84, -83, 53, 62, -54,
	62, 86, 89, 106, 107, 108, 60, 74, -61, 43,
	86, -10, -10, 108, -10, -83, 60, -1, 8, -12,
	15, 15, 82, 83, 83, 84, -10, -10, 86, -52,
	46, -55, 35, 36, 44, 45, 93, 107, 108, -85,
	-83, 54, 55, -57, 52, -10, -42, 53, -10, 82,
	84, 77, -26, 4, 14, -38, 88, 97, -26, 106,
	-12, 108, -10, 86, -10, 86, -10, -61, -61, -10,
	-10, -65, 108, -3, -4, 4, 19, 18, 27, -2,
	23, 14, 15, -10, -10, -10, -10, 87, 62, 99,
	99, -53, -54, 62, 108, -10, 98, -10, -62, 99,
	112, -42, -31, -36, -43, 52, 75, -10, 82, -6,
	-5, 14, 4, 15, 18, 77, -58, -9, -33, 64,
	13, 61, -10, 61, 23, -10, -63, 117, 81, 19,
	18, 20, 21, 22, 11, 114, 10, 9, -3, -3,
	-3, -3, 81, -76, 90, -9, -26, 71, 71, -54,
	-26, -10, -10, 98, 71, -56, -60, 109, 110, 111,
	113, -31, -38, -36, -44, -45, 57, -10, -10, -6,
	12, 33, 15, -58, 12, -59, 98, 65, 4, -10,
	59, -32, -39, -10, -40, -46, 100, 101, 102, 81,
	-8, -7, -10, -3, -3, -3, -3, -3, -3, -3,
	-3, -3, 24, -6, 49, 50, 91, -10, 61, 67,
	-10, -10, 12, 57, 57, 57, -38, -86, 58, 33,
	-5, 83, -9, -58, 68, -34, -41, -10, -32, 12,
	-33, -44, 25, -7, 12, -12, 59, -10, -60, -46,
	83, -10, -58, 12, -35, 103, -33, -39, -37, 67,
	-78, -77, -10, -64, 115, 116, -7, -32, -11, 4,
	14, -38, -41, -12, -37, 24, -10, 12, 26, -60,
	-38, -77,
}
var yyDef = [...]int{

	0, -2, 2, 4, 5, 6, 7, 8, 9, 10,
	11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
	21, 22, 23, 24, 25, 26, 0, 118, 0, 0,
	0, 0, 0, 0, 0, 0, 201, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 1, 3, 80,
	81, 82, 83, 0, 0, 0, 0, 126, 127, 128,
	129, 0, 0, 117, 0, 0, 0, 0, 70, 0,
	72, 0, 69, 0, 0, 0, 0, 0, 143, 0,
	187, 60, 62, 63, 64, 65, 0, 66, 67, 200,
	28, 29, 30, 0, 0, 0, 0, 0, 0, 0,
	87, 0, 0, 202, 0, 204, 0, 0, 0, 146,
	32, 33, 164, 0, 0, 0, 0, 119, 120, 133,
	0, 0, 0, 86, 0, 0, 0, 0, 74, 68,
	69, 190, 69, 0, 78, 0, 0, 141, 0, 192,
	27, 31, 0, 0, 0, 0, 0, 208, 209, 88,
	0, 90, 0, 0, 0, 0, 203, 0, 0, 0,
	0, 121, 122, 157, 0, 164, 0, 0, 0, 0,
	0, 0, 104, 36, 37, 134, 0, 0, 0, 84,
	85, 0, 213, 71, 189, 73, 188, 75, 76, 77,
	79, 139, 0, 61, 46, 47, 0, 0, 0, 44,
	0, 42, 43, 0, 193, 198, 199, 0, 0, 0,
	0, 114, 112, 0, 0, 211, 0, 0, 144, 0,
	0, 0, 133, 160, 174, 0, 0, 163, 0, 0,
	179, 175, 176, 177, 0, 0, 184, 185, 125, 0,
	0, 0, 132, 0, 0, 212, 142, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 48, 49,
	59, 0, 0, 194, 0, 207, 89, 0, 92, 113,
	0, 210, 205, 0, 0, 145, 148, 149, 151, 152,
	155, 133, 159, 161, 162, 173, 171, 165, 166, 0,
	0, 0, 178, 183, 0, 130, 0, 0, 38, 131,
	0, 104, 94, 174, 100, 0, 167, 168, 169, 0,
	140, 41, 39, 50, 51, 52, 53, 54, 55, 56,
	57, 58, 45, 191, 195, 196, 0, 91, 0, 0,
	206, 156, 0, 150, 153, 154, 158, 0, 170, 0,
	180, 0, 186, 123, 0, 103, 106, 109, 104, 0,
	111, 99, 0, 137, 0, 197, 0, 116, 147, 172,
	0, 133, 124, 0, 107, 0, 111, 93, 0, 0,
	0, 96, 0, 138, 135, 136, 40, 115, 133, 34,
	35, 182, 105, 108, 101, 102, 110, 0, 98, 95,
	181, 97,
}
var yyTok1 = [...]int{

	1,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
	102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
	112, 113, 114, 115, 116, 117,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:303
		{
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:304
		{
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:309
		{
			setParseTree(yylex, yyDollar[1].create)
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:313
		{
			setParseTree(yylex, yyDollar[1].create)
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:317
		{
			setParseTree(yylex, yyDollar[1].trace)
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:321
		{
			setParseTree(yylex, yyDollar[1].stoptrace)
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:325
		{
			setParseTree(yylex, yyDollar[1].drop)
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:329
		{
			setParseTree(yylex, yyDollar[1].lock)
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:333
		{
			setParseTree(yylex, yyDollar[1].unlock)
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:337
		{
			setParseTree(yylex, yyDollar[1].show)
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:341
		{
			setParseTree(yylex, yyDollar[1].kill)
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:345
		{
			setParseTree(yylex, yyDollar[1].listen)
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:349
		{
			setParseTree(yylex, yyDollar[1].shutdown)
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:353
		{
			setParseTree(yylex, yyDollar[1].split)
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:357
		{
			setParseTree(yylex, yyDollar[1].move)
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:361
		{
			setParseTree(yylex, yyDollar[1].redistribute)
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:365
		{
			setParseTree(yylex, yyDollar[1].unite)
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:369
		{
			setParseTree(yylex, yyDollar[1].register_router)
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:373
		{
			setParseTree(yylex, yyDollar[1].unregister_router)
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:377
		{
			setParseTree(yylex, yyDollar[1].alter)
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:381
		{
			setParseTree(yylex, yyDollar[1].invalidate)
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:385
		{
			setParseTree(yylex, yyDollar[1].retryMoveTaskGroup)
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:389
		{
			setParseTree(yylex, yyDollar[1].stopMoveTaskGroup)
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:393
		{
			setParseTree(yylex, yyDollar[1].sync_reference_tables)
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:397
		{
			setParseTree(yylex, yyDollar[1].alter)
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:402
		{
			yyVAL.uinteger = uint(yyDollar[1].uinteger)
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:407
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:411
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:413
		{
			if yyDollar[1].uinteger > uint(math.MaxInt64) {
				yylex.Error(SIGNED_INT_RANGE_ERROR)
				return 1
			} else {
				buf := make([]byte, binary.MaxVarintLen64)
				binary.PutVarint(buf, int64(yyDollar[1].uinteger))
				yyVAL.str = string(buf)
			}
		}
	case 31:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:422
		{
			if yyDollar[2].uinteger > uint(-math.MinInt64) {
				yylex.Error(SIGNED_INT_RANGE_ERROR)
				return 1
			} else {
				buf := make([]byte, binary.MaxVarintLen64)
				binary.PutVarint(buf, int64(-yyDollar[2].uinteger))
				yyVAL.str = string(buf)
			}
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:434
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:437
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:443
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:446
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:452
		{
			yyVAL.qname = &rfqn.RelationFQN{RelationName: yyDollar[1].str}
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:456
		{
			yyVAL.qname = &rfqn.RelationFQN{RelationName: yyDollar[1].str}
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:460
		{
			yyVAL.qname = &rfqn.RelationFQN{RelationName: yyDollar[3].str, SchemaName: yyDollar[1].str}
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:465
		{
			yyVAL.colref = ColumnRef{
				ColName: yyDollar[1].str,
			}
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:473
		{
			yyVAL.colreflist = append(yyDollar[1].colreflist, yyDollar[3].colref)
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:475
		{
			yyVAL.colreflist = []ColumnRef{
				yyDollar[1].colref,
			}
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:486
		{
			yyVAL.expr = &lyx.AExprSConst{
				Value: yyDollar[1].str,
			}
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:491
		{
			yyVAL.expr = &lyx.AExprSConst{
				Value: fmt.Sprintf("%+v", yyDollar[1].uinteger),
			}
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:507
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:508
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:513
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:515
		{
			/* column ref */
			yyVAL.expr = &lyx.ColumnRef{
				TableAlias: "",
				ColName:    yyDollar[1].str,
			}
		}
	case 48:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:534
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 49:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:536
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:538
		{
			yyVAL.expr = &lyx.AExprOp{
				Left:  yyDollar[1].expr,
				Right: yyDollar[3].expr,
				Op:    yyDollar[2].str,
			}
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:546
		{
			yyVAL.expr = &lyx.AExprOp{
				Left:  yyDollar[1].expr,
				Right: yyDollar[3].expr,
				Op:    yyDollar[2].str,
			}
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:554
		{
			yyVAL.expr = &lyx.AExprOp{
				Left:  yyDollar[1].expr,
				Right: yyDollar[3].expr,
				Op:    yyDollar[2].str,
			}
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:563
		{
			yyVAL.expr = &lyx.AExprOp{
				Left:  yyDollar[1].expr,
				Right: yyDollar[3].expr,
				Op:    yyDollar[2].str,
			}
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:571
		{
			yyVAL.expr = &lyx.AExprOp{
				Left:  yyDollar[1].expr,
				Right: yyDollar[3].expr,
				Op:    yyDollar[2].str,
			}
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:579
		{
			yyVAL.expr = &lyx.AExprOp{
				Left:  yyDollar[1].expr,
				Right: yyDollar[3].expr,
				Op:    yyDollar[2].str,
			}
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:595
		{
			yyVAL.expr = &lyx.AExprOp{
				Left:  yyDollar[1].expr,
				Right: yyDollar[3].expr,
				Op:    yyDollar[2].str,
			}
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:604
		{
			yyVAL.expr = &lyx.AExprOp{
				Left:  yyDollar[1].expr,
				Right: yyDollar[3].expr,
				Op:    yyDollar[2].str,
			}
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:612
		{
			yyVAL.expr = &lyx.AExprOp{
				Left:  yyDollar[1].expr,
				Right: yyDollar[3].expr,
				Op:    yyDollar[2].str,
			}
		}
	case 59:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:620
		{
			yyVAL.expr = &lyx.AExprNot{Arg: yyDollar[2].expr}
		}
	case 60:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:627
		{
			yyVAL.where = &lyx.AExprEmpty{}
		}
	case 61:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:631
		{
			yyVAL.where = yyDollar[2].expr
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:638
		{
			switch v := strings.ToLower(string(yyDollar[1].str)); v {
			case DatabasesStr, RoutersStr, PoolsStr, InstanceStr, ShardsStr, BackendConnectionsStr, KeyRangesStr, ShardingRules, ClientsStr, StatusStr, DistributionsStr, CoordinatorAddrStr, VersionStr, ReferenceRelationsStr, TaskGroupStr, PreparedStatementsStr, QuantilesStr, SequencesStr, IsReadOnlyStr, MoveStatsStr, TsaCacheStr, Users, MoveTaskStr:
				yyVAL.str = v
			default:
				yyVAL.str = UnsupportedStr
			}
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:645
		{
			yyVAL.str = yyDollar[1].str
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:647
		{
			yyVAL.str = yyDollar[1].str
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:649
		{
			yyVAL.str = yyDollar[1].str
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:655
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:659
		{
			switch v := string(yyDollar[1].str); v {
			case BackendStr:
				yyVAL.str = v
			default:
				yyVAL.str = UnsupportedStr
			}
		}
	case 68:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:669
		{
			yyVAL.bool = true
		}
	case 69:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:669
		{
			yyVAL.bool = false
		}
	case 70:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:673
		{
			yyVAL.drop = &Drop{Element: yyDollar[2].key_range_selector}
		}
	case 71:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:677
		{
			yyVAL.drop = &Drop{Element: &KeyRangeSelector{KeyRangeID: `*`}}
		}
	case 72:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:681
		{
			yyVAL.drop = &Drop{Element: yyDollar[2].sharding_rule_selector}
		}
	case 73:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:685
		{
			yyVAL.drop = &Drop{Element: &ShardingRuleSelector{ID: `*`}}
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:689
		{
			yyVAL.drop = &Drop{Element: yyDollar[2].distribution_selector, CascadeDelete: yyDollar[3].bool}
		}
	case 75:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:693
		{
			yyVAL.drop = &Drop{Element: &DistributionSelector{ID: `*`}, CascadeDelete: yyDollar[4].bool}
		}
	case 76:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:697
		{
			yyVAL.drop = &Drop{Element: &ShardSelector{ID: yyDollar[3].str}, CascadeDelete: yyDollar[4].bool}
		}
	case 77:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:701
		{
			yyVAL.drop = &Drop{Element: &TaskGroupSelector{ID: yyDollar[4].str}}
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:705
		{
			yyVAL.drop = &Drop{Element: &SequenceSelector{Name: yyDollar[3].str}}
		}
	case 79:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:709
		{
			yyVAL.drop = &Drop{
				Element: &ReferenceRelationSelector{
					ID: yyDollar[4].str,
				},
			}
		}
	case 80:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:720
		{
			yyVAL.create = &Create{Element: yyDollar[2].ds}
		}
	case 81:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:725
		{
			yyVAL.create = &Create{Element: yyDollar[2].sharding_rule}
		}
	case 82:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:730
		{
			yyVAL.create = &Create{Element: yyDollar[2].kr}
		}
	case 83:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:734
		{
			yyVAL.create = &Create{Element: yyDollar[2].shard}
		}
	case 84:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:740
		{
			yyVAL.trace = &TraceStmt{All: true}
		}
	case 85:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:743
		{
			yyVAL.trace = &TraceStmt{
				Client: yyDollar[4].uinteger,
			}
		}
	case 86:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:751
		{
			yyVAL.stoptrace = &StopTraceStmt{}
		}
	case 87:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:757
		{
			yyVAL.alter = &Alter{Element: yyDollar[2].alter_distribution}
		}
	case 88:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:763
		{
			yyVAL.alter_distribution = &AlterDistribution{
				Distribution: yyDollar[1].distribution_selector,
				Element: &AttachRelation{
					Relations: yyDollar[2].relations,
				},
			}
		}
	case 89:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:772
		{
			yyVAL.alter_distribution = &AlterDistribution{
				Distribution: yyDollar[1].distribution_selector,
				Element: &DetachRelation{
					RelationName: yyDollar[4].qname,
				},
			}
		}
	case 90:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:781
		{
			yyVAL.alter_distribution = &AlterDistribution{
				Distribution: yyDollar[1].distribution_selector,
				Element:      yyDollar[2].alter_relation,
			}
		}
	case 91:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:788
		{
			yyVAL.alter_distribution = &AlterDistribution{
				Distribution: yyDollar[1].distribution_selector,
				Element: &AlterDefaultShard{
					Shard: yyDollar[5].str,
				},
			}
		}
	case 92:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:797
		{
			yyVAL.alter_distribution = &AlterDistribution{
				Distribution: yyDollar[1].distribution_selector,
				Element:      &DropDefaultShard{},
			}
		}
	case 93:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:807
		{
			yyVAL.dEntrieslist = append(yyDollar[1].dEntrieslist, yyDollar[3].distrKeyEntry)
		}
	case 94:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:809
		{
			yyVAL.dEntrieslist = []DistributionKeyEntry{
				yyDollar[1].distrKeyEntry,
			}
		}
	case 95:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:816
		{
			yyVAL.typedColRef = TypedColRef{
				Column: yyDollar[1].str,
				Type:   yyDollar[2].str,
			}
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:825
		{
			yyVAL.routingExpr = []TypedColRef{yyDollar[1].typedColRef}
		}
	case 97:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:827
		{
			yyVAL.routingExpr = append(yyDollar[1].routingExpr, yyDollar[3].typedColRef)
		}
	case 98:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:832
		{
			yyVAL.distrKeyEntry = DistributionKeyEntry{
				HashFunction: yyDollar[1].str,
				Expr:         yyDollar[3].routingExpr,
			}
		}
	case 99:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:841
		{
			yyVAL.distrKeyEntry = DistributionKeyEntry{
				Column:       yyDollar[1].str,
				HashFunction: yyDollar[2].str,
			}
		}
	case 100:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:846
		{
			yyVAL.distrKeyEntry = yyDollar[1].distrKeyEntry
		}
	case 101:
		yyDollar = yyS[yypt-7 : yypt+1]
//line gram.y:852
		{
			if len(yyDollar[2].qname.SchemaName) > 0 && len(yyDollar[7].str) > 0 {
				yylex.Error("it is forbidden to use both a qualified relation name and the keyword SCHEMA")
				return 1
			} else if len(yyDollar[2].qname.SchemaName) > 0 {
				yyVAL.distributed_relation = &DistributedRelation{
					Name:                 yyDollar[2].qname.RelationName,
					DistributionKey:      yyDollar[5].dEntrieslist,
					AutoIncrementEntries: yyDollar[6].aiEntrieslist,
					SchemaName:           yyDollar[2].qname.SchemaName,
				}
			} else {
				yyVAL.distributed_relation = &DistributedRelation{
					Name:                 yyDollar[2].qname.RelationName,
					DistributionKey:      yyDollar[5].dEntrieslist,
					AutoIncrementEntries: yyDollar[6].aiEntrieslist,
					SchemaName:           yyDollar[7].str,
				}
			}
		}
	case 102:
		yyDollar = yyS[yypt-7 : yypt+1]
//line gram.y:873
		{
			if len(yyDollar[2].qname.SchemaName) > 0 && len(yyDollar[7].str) > 0 {
				yylex.Error("it is forbidden to use both a qualified relation name and the keyword SCHEMA")
				return 1
			} else if len(yyDollar[2].qname.SchemaName) > 0 {
				yyVAL.distributed_relation = &DistributedRelation{
					Name:                 yyDollar[2].qname.RelationName,
					DistributionKey:      yyDollar[4].dEntrieslist,
					AutoIncrementEntries: yyDollar[5].aiEntrieslist,
					SchemaName:           yyDollar[2].qname.SchemaName,
				}
			} else {
				yyVAL.distributed_relation = &DistributedRelation{
					Name:                 yyDollar[2].qname.RelationName,
					DistributionKey:      yyDollar[4].dEntrieslist,
					AutoIncrementEntries: yyDollar[5].aiEntrieslist,
					SchemaName:           yyDollar[6].str,
				}
			}
		}
	case 103:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:895
		{
			yyVAL.aiEntrieslist = yyDollar[3].aiEntrieslist
		}
	case 104:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:897
		{
			yyVAL.aiEntrieslist = nil
		}
	case 105:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:903
		{
			yyVAL.aiEntrieslist = append(yyDollar[1].aiEntrieslist, yyDollar[3].aiEntry)
		}
	case 106:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:905
		{
			yyVAL.aiEntrieslist = []*AutoIncrementEntry{
				yyDollar[1].aiEntry,
			}
		}
	case 107:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:913
		{
			yyVAL.aiEntry = &AutoIncrementEntry{
				Column: yyDollar[1].str,
				Start:  uint64(yyDollar[2].uinteger),
			}
		}
	case 108:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:922
		{
			yyVAL.uinteger = yyDollar[2].uinteger
		}
	case 109:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:924
		{
			yyVAL.uinteger = 0
		}
	case 110:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:929
		{
			yyVAL.str = yyDollar[2].str
		}
	case 111:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:931
		{
			yyVAL.str = ""
		}
	case 112:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:936
		{
			yyVAL.relations = []*DistributedRelation{yyDollar[1].distributed_relation}
		}
	case 113:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:938
		{
			yyVAL.relations = append(yyDollar[1].relations, yyDollar[2].distributed_relation)
		}
	case 114:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:943
		{
			yyVAL.relations = yyDollar[2].relations
		}
	case 115:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:948
		{
			yyVAL.alter_relation = &AlterRelationV2{
				RelationName: yyDollar[3].qname.RelationName,
				Element: &AlterRelationDistributionKey{
					DistributionKey: yyDollar[6].dEntrieslist,
				},
			}
		}
	case 116:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:956
		{
			yyVAL.alter_relation = &AlterRelationV2{
				RelationName: yyDollar[3].qname.RelationName,
				Element: &AlterRelationSchema{
					SchemaName: yyDollar[5].str,
				},
			}
		}
	case 118:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:966
		{
		}
	case 119:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:969
		{
		}
	case 120:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:969
		{
		}
	case 121:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:972
		{
		}
	case 122:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:972
		{
		}
	case 123:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:976
		{
			yyVAL.strlist = yyDollar[2].strlist
		}
	case 124:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:977
		{
			yyVAL.strlist = yyDollar[3].strlist
		}
	case 125:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:977
		{
		}
	case 126:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:981
		{
			yyVAL.create = &Create{Element: yyDollar[2].ds}
		}
	case 127:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:986
		{
			yyVAL.create = &Create{Element: yyDollar[2].sharding_rule}
		}
	case 128:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:991
		{
			yyVAL.create = &Create{Element: yyDollar[2].kr}
		}
	case 129:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:996
		{
			yyVAL.create = &Create{Element: yyDollar[2].shard}
		}
	case 130:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:1001
		{
			yyVAL.create = &Create{
				Element: &ReferenceRelationDefinition{
					TableName:            yyDollar[4].qname,
					AutoIncrementEntries: yyDollar[5].aiEntrieslist,
					ShardIds:             yyDollar[6].strlist,
				},
			}
		}
	case 131:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1012
		{
			yyVAL.distribution_selector = &DistributionSelector{ID: yyDollar[3].str}
		}
	case 132:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1015
		{
			yyVAL.distribution_selector = &DistributionSelector{ID: yyDollar[2].str}
		}
	case 133:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1017
		{
			yyVAL.distribution_selector = &DistributionSelector{ID: "default"}
		}
	case 134:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:1023
		{
			yyVAL.alter = &Alter{
				Element: &AlterDistribution{
					Distribution: yyDollar[4].distribution_selector,
					Element: &AttachRelation{
						Relations: []*DistributedRelation{yyDollar[3].distributed_relation},
					},
				},
			}
		}
	case 135:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1035
		{
			yyVAL.opt_asc_desc = &SortByAsc{}
		}
	case 136:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1036
		{
			yyVAL.opt_asc_desc = &SortByDesc{}
		}
	case 137:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1037
		{
			yyVAL.opt_asc_desc = &SortByDefault{}
		}
	case 138:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:1041
		{
			yyVAL.order_clause = &Order{Col: yyDollar[3].colref, OptAscDesc: yyDollar[4].opt_asc_desc}
		}
	case 139:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1044
		{
			yyVAL.order_clause = OrderClause(nil)
		}
	case 140:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1049
		{
			yyVAL.group_clause = GroupBy{Col: yyDollar[3].colreflist}
		}
	case 141:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1052
		{
			yyVAL.group_clause = GroupByClauseEmpty{}
		}
	case 142:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:1057
		{
			yyVAL.show = &Show{Cmd: yyDollar[2].str, Where: yyDollar[3].where, GroupBy: yyDollar[4].group_clause, Order: yyDollar[5].order_clause}
		}
	case 143:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1063
		{
			yyVAL.lock = &Lock{KeyRangeID: yyDollar[2].key_range_selector.KeyRangeID}
		}
	case 144:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:1071
		{
			yyVAL.ds = &DistributionDefinition{
				ID:           yyDollar[2].str,
				ColTypes:     yyDollar[3].strlist,
				DefaultShard: yyDollar[4].str,
			}
		}
	case 145:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1080
		{
			yyVAL.strlist = yyDollar[3].strlist
		}
	case 146:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1082
		{
			/* empty column types should be prohibited */
			yyVAL.strlist = nil
		}
	case 147:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1088
		{
			yyVAL.strlist = append(yyDollar[1].strlist, yyDollar[3].str)
		}
	case 148:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1090
		{
			yyVAL.strlist = []string{
				yyDollar[1].str,
			}
		}
	case 149:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1097
		{
			yyVAL.str = qdb.ColumnTypeVarchar
		}
	case 150:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1099
		{
			yyVAL.str = qdb.ColumnTypeVarcharHashed
		}
	case 151:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1101
		{
			yyVAL.str = qdb.ColumnTypeInteger
		}
	case 152:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1103
		{
			yyVAL.str = qdb.ColumnTypeInteger
		}
	case 153:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1105
		{
			yyVAL.str = qdb.ColumnTypeUinteger
		}
	case 154:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1107
		{
			yyVAL.str = qdb.ColumnTypeUinteger
		}
	case 155:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1109
		{
			yyVAL.str = qdb.ColumnTypeUUID
		}
	case 156:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1114
		{
			yyVAL.str = yyDollar[3].str
		}
	case 157:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1116
		{
			yyVAL.str = ""
		}
	case 158:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:1122
		{
		}
	case 159:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:1126
		{
		}
	case 160:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1130
		{
			yyVAL.entrieslist = make([]ShardingRuleEntry, 0)
			yyVAL.entrieslist = append(yyVAL.entrieslist, yyDollar[1].shruleEntry)
		}
	case 161:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1136
		{
			yyVAL.entrieslist = append(yyDollar[1].entrieslist, yyDollar[2].shruleEntry)
		}
	case 162:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1142
		{
			yyVAL.shruleEntry = ShardingRuleEntry{
				Column:       yyDollar[1].str,
				HashFunction: yyDollar[2].str,
			}
		}
	case 163:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1151
		{
			yyVAL.str = yyDollar[2].str
		}
	case 164:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1154
		{
			yyVAL.str = ""
		}
	case 165:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1158
		{
			yyVAL.str = yyDollar[2].str
		}
	case 166:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1163
		{
			yyVAL.str = yyDollar[2].str
		}
	case 167:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1169
		{
			yyVAL.str = "identity"
		}
	case 168:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1171
		{
			yyVAL.str = "murmur"
		}
	case 169:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1173
		{
			yyVAL.str = "city"
		}
	case 170:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1178
		{
		}
	case 171:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1178
		{
		}
	case 172:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1182
		{
			yyVAL.str = yyDollar[3].str
		}
	case 173:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1187
		{
			yyVAL.str = yyDollar[1].str
		}
	case 174:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1189
		{
			yyVAL.str = ""
		}
	case 175:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1195
		{
			yyVAL.bytes = []byte(yyDollar[1].str)
		}
	case 176:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1199
		{
			yyVAL.bytes = []byte(yyDollar[1].str)
		}
	case 177:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1201
		{
			if yyDollar[1].uinteger > uint(math.MaxInt64) {
				yylex.Error(SIGNED_INT_RANGE_ERROR)
				return 1
			} else {
				buf := make([]byte, binary.MaxVarintLen64)
				binary.PutVarint(buf, int64(yyDollar[1].uinteger))
				yyVAL.bytes = buf
			}
		}
	case 178:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1210
		{
			if yyDollar[2].uinteger > uint(-math.MinInt64) {
				yylex.Error(SIGNED_INT_RANGE_ERROR)
				return 1
			} else {
				buf := make([]byte, binary.MaxVarintLen64)
				binary.PutVarint(buf, int64(-yyDollar[2].uinteger))
				yyVAL.bytes = buf
			}
		}
	case 179:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1222
		{
			yyVAL.krbound = &KeyRangeBound{
				Pivots: [][]byte{
					yyDollar[1].bytes,
				},
			}
		}
	case 180:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1229
		{
			yyVAL.krbound = &KeyRangeBound{
				Pivots: append(yyDollar[1].krbound.Pivots, yyDollar[3].bytes),
			}
		}
	case 181:
		yyDollar = yyS[yypt-9 : yypt+1]
//line gram.y:1238
		{
			yyVAL.kr = &KeyRangeDefinition{
				KeyRangeID:   yyDollar[3].str,
				LowerBound:   yyDollar[5].krbound,
				ShardID:      yyDollar[8].str,
				Distribution: yyDollar[9].distribution_selector,
			}
		}
	case 182:
		yyDollar = yyS[yypt-8 : yypt+1]
//line gram.y:1247
		{
			str, err := randomHex(6)
			if err != nil {
				panic(err)
			}
			yyVAL.kr = &KeyRangeDefinition{
				LowerBound:   yyDollar[4].krbound,
				ShardID:      yyDollar[7].str,
				Distribution: yyDollar[8].distribution_selector,
				KeyRangeID:   "kr" + str,
			}
		}
	case 183:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:1262
		{
			yyVAL.shard = &ShardDefinition{Id: yyDollar[2].str, Hosts: yyDollar[5].strlist}
		}
	case 184:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:1267
		{
			str, err := randomHex(6)
			if err != nil {
				panic(err)
			}
			yyVAL.shard = &ShardDefinition{Id: "shard" + str, Hosts: yyDollar[4].strlist}
		}
	case 185:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1277
		{
			yyVAL.strlist = []string{yyDollar[1].str}
		}
	case 186:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1282
		{
			yyVAL.strlist = append(yyDollar[1].strlist, yyDollar[3].str)
		}
	case 187:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1288
		{
			yyVAL.unlock = &Unlock{KeyRangeID: yyDollar[2].key_range_selector.KeyRangeID}
		}
	case 188:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1294
		{
			yyVAL.sharding_rule_selector = &ShardingRuleSelector{ID: yyDollar[3].str}
		}
	case 189:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1300
		{
			yyVAL.key_range_selector = &KeyRangeSelector{KeyRangeID: yyDollar[3].str}
		}
	case 190:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1306
		{
			yyVAL.distribution_selector = &DistributionSelector{ID: yyDollar[2].str}
		}
	case 191:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:1312
		{
			yyVAL.split = &SplitKeyRange{KeyRangeID: yyDollar[2].key_range_selector.KeyRangeID, KeyRangeFromID: yyDollar[4].str, Border: yyDollar[6].krbound}
		}
	case 192:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1318
		{
			yyVAL.kill = &Kill{Cmd: yyDollar[2].str, Target: yyDollar[3].uinteger}
		}
	case 193:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:1325
		{
			yyVAL.move = &MoveKeyRange{KeyRangeID: yyDollar[2].key_range_selector.KeyRangeID, DestShardID: yyDollar[4].str}
		}
	case 194:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:1331
		{
			yyVAL.redistribute = &RedistributeKeyRange{KeyRangeID: yyDollar[2].key_range_selector.KeyRangeID, DestShardID: yyDollar[4].str, BatchSize: yyDollar[5].integer, Check: true, Apply: true}
		}
	case 195:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:1333
		{
			yyVAL.redistribute = &RedistributeKeyRange{KeyRangeID: yyDollar[2].key_range_selector.KeyRangeID, DestShardID: yyDollar[4].str, BatchSize: yyDollar[5].integer, Check: true}
		}
	case 196:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:1335
		{
			yyVAL.redistribute = &RedistributeKeyRange{KeyRangeID: yyDollar[2].key_range_selector.KeyRangeID, DestShardID: yyDollar[4].str, BatchSize: yyDollar[5].integer, Apply: true}
		}
	case 197:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1339
		{
			yyVAL.integer = int(yyDollar[3].uinteger)
		}
	case 198:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1340
		{
			yyVAL.integer = -1
		}
	case 199:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:1344
		{
			yyVAL.unite = &UniteKeyRange{KeyRangeIDL: yyDollar[2].key_range_selector.KeyRangeID, KeyRangeIDR: yyDollar[4].str}
		}
	case 200:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1350
		{
			yyVAL.listen = &Listen{addr: yyDollar[2].str}
		}
	case 201:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1356
		{
			yyVAL.shutdown = &Shutdown{}
		}
	case 202:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1362
		{
			yyVAL.invalidate = &Invalidate{
				Target: SchemaCacheInvalidateTarget,
			}
		}
	case 203:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1367
		{
			yyVAL.invalidate = &Invalidate{
				Target: SchemaCacheInvalidateTarget,
			}
		}
	case 204:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1372
		{
			yyVAL.invalidate = &Invalidate{
				Target: BackendConnectionsInvalidateTarget,
			}
		}
	case 205:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:1380
		{
			yyVAL.sync_reference_tables = &SyncReferenceTables{
				ShardID:          yyDollar[5].str,
				RelationSelector: "*",
			}
		}
	case 206:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:1386
		{
			yyVAL.sync_reference_tables = &SyncReferenceTables{
				ShardID:          yyDollar[6].str,
				RelationSelector: yyDollar[4].str,
			}
		}
	case 207:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:1397
		{
			yyVAL.register_router = &RegisterRouter{ID: yyDollar[3].str, Addr: yyDollar[5].str}
		}
	case 208:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1403
		{
			yyVAL.unregister_router = &UnregisterRouter{ID: yyDollar[3].str}
		}
	case 209:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1408
		{
			yyVAL.unregister_router = &UnregisterRouter{ID: `*`}
		}
	case 210:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:1416
		{
			yyVAL.retryMoveTaskGroup = &RetryMoveTaskGroup{ID: yyDollar[5].str}
		}
	case 211:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:1421
		{
			yyVAL.retryMoveTaskGroup = &RetryMoveTaskGroup{ID: yyDollar[4].str}
		}
	case 212:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:1428
		{
			yyVAL.stopMoveTaskGroup = &StopMoveTaskGroup{ID: yyDollar[5].str}
		}
	case 213:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:1433
		{
			yyVAL.stopMoveTaskGroup = &StopMoveTaskGroup{ID: yyDollar[4].str}
		}
	}
	goto yystack /* stack new state and value */
}
