// Code generated by goyacc -o gram.go -p yy gram.y. DO NOT EDIT.

//line gram.y:3
package spqrparser

import __yyfmt__ "fmt"

//line gram.y:3

import (
	"fmt"
	"strconv"
	"time"

	"crypto/rand"
	"encoding/binary"
	"encoding/hex"
	"github.com/pg-sharding/lyx/lyx"
	"github.com/pg-sharding/spqr/qdb"
	"github.com/pg-sharding/spqr/router/rfqn"
	"math"
	"strings"
)

const SIGNED_INT_RANGE_ERROR string = "the Signed Value should be at the range of [-9223372036854775808, 9223372036854775807]."

func randomHex(n int) (string, error) {
	bytes := make([]byte, n)
	if _, err := rand.Read(bytes); err != nil {
		return "", err
	}
	return hex.EncodeToString(bytes), nil
}

//line gram.y:34
type yySymType struct {
	yys          int
	str          string
	strlist      []string
	byte         byte
	bytes        []byte
	integer      int
	uinteger     uint
	uintegerlist []uint
	bool         bool
	empty        struct{}

	set       *Set
	statement Statement
	show      *Show
	help      *Help

	drop   *Drop
	create *Create

	kill   *Kill
	lock   *Lock
	unlock *Unlock

	krbound *KeyRangeBound

	qname *rfqn.RelationFQN
	ds    *DistributionDefinition
	kr    *KeyRangeDefinition
	shard *ShardDefinition

	register_router   *RegisterRouter
	unregister_router *UnregisterRouter

	split *SplitKeyRange
	move  *MoveKeyRange
	unite *UniteKeyRange

	redistribute *RedistributeKeyRange

	invalidate                    *Invalidate
	sync_reference_tables         *SyncReferenceTables
	alter_reference_table_storage *AlterReferenceTableStorage

	shutdown *Shutdown
	listen   *Listen

	trace     *TraceStmt
	stoptrace *StopTraceStmt

	distribution *DistributionDefinition

	alter                *Alter
	alter_distribution   *AlterDistribution
	distributed_relation *DistributedRelation
	alter_default_shard  *AlterDefaultShard

	/* ICP */
	icp       *InstanceControlPoint
	icpAction *ICPointAction
	duration  time.Duration

	relations    []*DistributedRelation
	relation     *DistributedRelation
	dEntrieslist []DistributionKeyEntry

	distrKeyEntry DistributionKeyEntry
	aiEntry       *AutoIncrementEntry

	key_range_selector    *KeyRangeSelector
	distribution_selector *DistributionSelector
	aiEntrieslist         []*AutoIncrementEntry

	colref     *lyx.ColumnRef
	colreflist []*lyx.ColumnRef
	where      lyx.Node
	expr       lyx.Node

	order_clause lyx.Node
	opt_asc_desc int

	group_clause GroupByClause

	retryMoveTaskGroup *RetryMoveTaskGroup
	stopMoveTaskGroup  *StopMoveTaskGroup

	typedColRef TypedColRef
	routingExpr []TypedColRef

	alter_relation *AlterRelationV2
	alter_shard    *AlterShard
	option         GenericOption
	options        []GenericOption
}

const IDENT = 57346
const COMMAND = 57347
const HELP = 57348
const SHOW = 57349
const KILL = 57350
const WHERE = 57351
const OR = 57352
const AND = 57353
const TEQ = 57354
const TCOMMA = 57355
const TDOT = 57356
const SCONST = 57357
const ICONST = 57358
const INVALID_ICONST = 57359
const TSEMICOLON = 57360
const TMINUS = 57361
const TPLUS = 57362
const TMUL = 57363
const TLESS = 57364
const TGREATER = 57365
const TOPENBR = 57366
const TCLOSEBR = 57367
const TOPENSQBR = 57368
const TCLOSESQBR = 57369
const NOT = 57370
const SHUTDOWN = 57371
const LISTEN = 57372
const REGISTER = 57373
const UNREGISTER = 57374
const ROUTER = 57375
const ROUTE = 57376
const CREATE = 57377
const ADD = 57378
const DROP = 57379
const LOCK = 57380
const UNLOCK = 57381
const SPLIT = 57382
const MOVE = 57383
const COMPOSE = 57384
const SET = 57385
const CASCADE = 57386
const ATTACH = 57387
const ALTER = 57388
const DETACH = 57389
const REDISTRIBUTE = 57390
const REFERENCE = 57391
const CHECK = 57392
const APPLY = 57393
const UNIQUE = 57394
const RENAME = 57395
const COLUMN = 57396
const TABLE = 57397
const TABLES = 57398
const RELATIONS = 57399
const BACKENDS = 57400
const HASH = 57401
const FUNCTION = 57402
const KEY = 57403
const RANGE = 57404
const DISTRIBUTION = 57405
const RELATION = 57406
const REPLICATED = 57407
const AUTO = 57408
const INCREMENT = 57409
const SEQUENCE = 57410
const SCHEMA = 57411
const INDEX = 57412
const STORAGE = 57413
const SHARDS = 57414
const ROUTERS = 57415
const SHARD = 57416
const HOST = 57417
const RULE = 57418
const COLUMNS = 57419
const VERSION = 57420
const HOSTS = 57421
const SEQUENCES = 57422
const IS_READ_ONLY = 57423
const MOVE_STATS = 57424
const BY = 57425
const FROM = 57426
const TO = 57427
const WITH = 57428
const UNITE = 57429
const ALL = 57430
const ADDRESS = 57431
const FOR = 57432
const CLIENT = 57433
const BATCH = 57434
const SIZE = 57435
const NOWAIT = 57436
const INVALIDATE = 57437
const CACHE = 57438
const SYNC = 57439
const RETRY = 57440
const DISTRIBUTED = 57441
const IN = 57442
const ON = 57443
const DEFAULT = 57444
const STALE = 57445
const CLIENTS = 57446
const OPTIONS = 57447
const IDENTITY = 57448
const MURMUR = 57449
const CITY = 57450
const START = 57451
const STOP = 57452
const TRACE = 57453
const MESSAGES = 57454
const TASK = 57455
const GROUP = 57456
const SYSTEM = 57457
const RELOAD = 57458
const RESTART = 57459
const SECONDS = 57460
const WAIT = 57461
const PANIC = 57462
const SLEEP = 57463
const VARCHAR = 57464
const INTEGER = 57465
const INT = 57466
const TYPES = 57467
const UUID = 57468
const TYPE = 57469
const CONTROL = 57470
const POINT = 57471
const OP = 57472
const ASC = 57473
const DESC = 57474
const ORDER = 57475
const OPERATOR = 57476
const TSQOPENBR = 57477
const TSQCLOSEBR = 57478

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"COMMAND",
	"HELP",
	"SHOW",
	"KILL",
	"WHERE",
	"OR",
	"AND",
	"TEQ",
	"TCOMMA",
	"TDOT",
	"SCONST",
	"ICONST",
	"INVALID_ICONST",
	"TSEMICOLON",
	"TMINUS",
	"TPLUS",
	"TMUL",
	"TLESS",
	"TGREATER",
	"TOPENBR",
	"TCLOSEBR",
	"TOPENSQBR",
	"TCLOSESQBR",
	"NOT",
	"SHUTDOWN",
	"LISTEN",
	"REGISTER",
	"UNREGISTER",
	"ROUTER",
	"ROUTE",
	"CREATE",
	"ADD",
	"DROP",
	"LOCK",
	"UNLOCK",
	"SPLIT",
	"MOVE",
	"COMPOSE",
	"SET",
	"CASCADE",
	"ATTACH",
	"ALTER",
	"DETACH",
	"REDISTRIBUTE",
	"REFERENCE",
	"CHECK",
	"APPLY",
	"UNIQUE",
	"RENAME",
	"COLUMN",
	"TABLE",
	"TABLES",
	"RELATIONS",
	"BACKENDS",
	"HASH",
	"FUNCTION",
	"KEY",
	"RANGE",
	"DISTRIBUTION",
	"RELATION",
	"REPLICATED",
	"AUTO",
	"INCREMENT",
	"SEQUENCE",
	"SCHEMA",
	"INDEX",
	"STORAGE",
	"SHARDS",
	"ROUTERS",
	"SHARD",
	"HOST",
	"RULE",
	"COLUMNS",
	"VERSION",
	"HOSTS",
	"SEQUENCES",
	"IS_READ_ONLY",
	"MOVE_STATS",
	"BY",
	"FROM",
	"TO",
	"WITH",
	"UNITE",
	"ALL",
	"ADDRESS",
	"FOR",
	"CLIENT",
	"BATCH",
	"SIZE",
	"NOWAIT",
	"INVALIDATE",
	"CACHE",
	"SYNC",
	"RETRY",
	"DISTRIBUTED",
	"IN",
	"ON",
	"DEFAULT",
	"STALE",
	"CLIENTS",
	"OPTIONS",
	"IDENTITY",
	"MURMUR",
	"CITY",
	"START",
	"STOP",
	"TRACE",
	"MESSAGES",
	"TASK",
	"GROUP",
	"SYSTEM",
	"RELOAD",
	"RESTART",
	"SECONDS",
	"WAIT",
	"PANIC",
	"SLEEP",
	"VARCHAR",
	"INTEGER",
	"INT",
	"TYPES",
	"UUID",
	"TYPE",
	"CONTROL",
	"POINT",
	"OP",
	"ASC",
	"DESC",
	"ORDER",
	"OPERATOR",
	"TSQOPENBR",
	"TSQCLOSEBR",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line gram.y:1725

//line yacctab:1
var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 440,
	12, 0,
	22, 0,
	23, 0,
	-2, 57,
	-1, 441,
	12, 0,
	22, 0,
	23, 0,
	-2, 58,
}

const yyPrivate = 57344

const yyLast = 589

var yyAct = [...]int16{
	367, 478, 401, 236, 281, 435, 194, 369, 477, 423,
	294, 296, 400, 365, 366, 295, 288, 406, 354, 287,
	232, 172, 280, 179, 168, 501, 502, 384, 383, 381,
	377, 376, 378, 374, 224, 223, 377, 376, 378, 379,
	380, 381, 446, 282, 283, 284, 161, 285, 377, 376,
	378, 379, 380, 160, 279, 135, 384, 383, 381, 162,
	462, 166, 383, 381, 450, 377, 376, 378, 379, 380,
	377, 376, 378, 379, 380, 310, 182, 183, 82, 185,
	340, 341, 339, 213, 214, 81, 79, 309, 272, 80,
	242, 184, 149, 392, 218, 189, 188, 177, 73, 240,
	75, 176, 68, 71, 186, 78, 153, 470, 163, 269,
	156, 76, 370, 371, 372, 278, 355, 152, 217, 164,
	265, 155, 264, 237, 359, 337, 299, 273, 216, 407,
	324, 447, 448, 238, 393, 271, 93, 174, 134, 261,
	175, 382, 230, 201, 510, 202, 203, 382, 154, 463,
	77, 163, 163, 215, 182, 157, 163, 163, 151, 382,
	87, 416, 164, 164, 394, 200, 228, 164, 164, 199,
	286, 198, 235, 69, 205, 449, 382, 433, 375, 244,
	322, 382, 241, 425, 220, 247, 163, 249, 250, 251,
	252, 244, 64, 256, 239, 65, 293, 164, 231, 257,
	258, 259, 260, 163, 59, 245, 58, 246, 357, 248,
	370, 371, 372, 88, 164, 342, 163, 60, 329, 328,
	326, 274, 37, 36, 38, 133, 262, 164, 90, 193,
	187, 229, 171, 267, 398, 89, 335, 427, 360, 301,
	305, 243, 67, 304, 396, 40, 39, 45, 46, 297,
	397, 30, 29, 33, 34, 35, 41, 42, 173, 169,
	91, 51, 47, 52, 43, 268, 303, 137, 170, 263,
	204, 306, 455, 334, 336, 307, 300, 325, 136, 138,
	332, 59, 139, 58, 327, 190, 453, 181, 330, 331,
	297, 169, 221, 222, 60, 178, 165, 476, 167, 364,
	170, 363, 343, 44, 353, 302, 349, 84, 431, 348,
	347, 48, 346, 50, 49, 227, 485, 159, 70, 405,
	362, 389, 209, 210, 180, 31, 32, 350, 71, 395,
	145, 211, 212, 207, 350, 421, 144, 74, 409, 72,
	497, 474, 390, 412, 432, 226, 411, 497, 414, 57,
	413, 403, 404, 408, 498, 351, 56, 55, 402, 508,
	471, 424, 452, 419, 333, 192, 378, 415, 158, 54,
	420, 418, 417, 196, 83, 85, 436, 428, 426, 352,
	63, 140, 141, 142, 143, 150, 197, 62, 61, 385,
	386, 387, 312, 388, 377, 376, 378, 355, 454, 492,
	451, 298, 457, 318, 319, 458, 459, 314, 313, 504,
	427, 491, 317, 345, 456, 320, 315, 464, 195, 355,
	163, 461, 466, 481, 468, 344, 488, 321, 350, 137,
	196, 164, 467, 479, 436, 290, 345, 489, 472, 480,
	136, 138, 473, 254, 139, 405, 289, 291, 460, 361,
	292, 482, 437, 438, 439, 440, 441, 442, 443, 444,
	445, 276, 275, 483, 233, 475, 219, 484, 490, 424,
	486, 66, 479, 94, 53, 234, 98, 494, 493, 1,
	495, 410, 436, 496, 499, 338, 505, 503, 24, 23,
	391, 506, 323, 20, 19, 507, 18, 17, 479, 509,
	111, 112, 110, 16, 95, 15, 96, 104, 105, 106,
	108, 511, 13, 14, 118, 97, 119, 109, 117, 8,
	9, 129, 308, 500, 113, 114, 116, 373, 147, 399,
	99, 100, 101, 115, 465, 270, 356, 120, 277, 128,
	358, 103, 225, 102, 208, 255, 191, 266, 206, 26,
	25, 22, 28, 148, 146, 27, 107, 131, 21, 430,
	121, 429, 368, 469, 124, 123, 125, 422, 6, 5,
	4, 130, 3, 122, 7, 12, 92, 11, 10, 132,
	86, 2, 126, 127, 487, 434, 311, 316, 253,
}

var yyPact = [...]int16{
	216, -1000, 351, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 220,
	143, -9, 62, 37, 246, 246, 156, 469, 134, 425,
	-1000, 246, 246, 246, 246, 303, 297, 43, 52, 287,
	268, -75, -82, -1000, -1000, -1000, -1000, -1000, 416, 234,
	212, -1000, -1000, -1000, 204, 162, 194, -1000, 49, -11,
	-16, -1000, -1000, 233, 280, 199, 416, -23, 416, 204,
	160, -17, -18, -1000, 223, -1000, 341, -1000, -1000, -1000,
	-1000, -1000, 469, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 414, -1000, -1000, -1000, -1000, -1000, -1000, 370,
	87, 84, 80, 57, 416, 182, -1000, -1000, -1000, 204,
	286, -33, 416, 416, -1000, 32, -1000, 14, -19, 236,
	-94, -95, 291, -1000, -1000, 147, 56, 119, 460, -1000,
	-1000, 416, 33, 460, -13, 357, -1000, -24, 153, -1000,
	-1000, 280, -1000, 280, 416, 280, 416, 416, 416, 416,
	416, 434, 416, -1000, -1000, -1000, -1000, -1000, 416, 416,
	416, 416, 50, -1000, -1000, 460, -1000, 205, -1000, 20,
	18, 194, 201, -1000, -1000, 30, -1000, -1000, -26, 26,
	416, -1000, -1000, 458, 457, 13, -71, -79, 86, 431,
	117, 425, 183, 387, -1000, 25, -1000, 213, 416, 242,
	-1000, -1000, 152, -1000, -1000, -1000, -1000, 280, -1000, -1000,
	-1000, 280, -1000, -27, 388, 402, -1000, 97, -1000, 38,
	-1000, 425, 149, 460, 145, 144, 194, -1000, 460, 425,
	-1000, 340, 148, 416, 24, -39, -1000, -1000, 141, -79,
	400, -1000, 253, 251, 250, -1000, 431, 321, -1000, -1000,
	-1000, -1000, 363, 425, 103, -1000, 23, 171, 445, 460,
	416, -1000, 238, 104, -1000, -1000, -1000, -1000, -100, 95,
	46, -1000, -1000, 388, 388, 388, -1000, 388, -1000, -1000,
	416, -1000, 431, -20, 41, -1000, 79, -1000, 416, -1000,
	-1000, 181, 406, 315, 35, 35, -1000, 416, -1000, 357,
	-1000, -1000, 416, 423, -1000, -79, -1000, -1000, -1000, 314,
	431, 76, -1000, 103, -1000, 425, -1000, 339, -1000, 263,
	416, -1000, 106, -1000, 104, 224, -1000, 249, -1000, 318,
	-1000, -1000, -1000, -1000, 94, 416, 388, 388, 388, 388,
	388, 388, 388, 388, 388, 345, 345, 29, 17, -1000,
	415, 81, -50, 357, 338, -1000, 225, 416, 209, 389,
	-1000, -1000, 441, 441, 444, 425, -1000, -1000, -1000, -1000,
	-1000, -58, -1000, -1000, 64, -1000, 416, -1000, -1000, 441,
	406, 425, 411, -1000, -2, 336, 224, 104, 316, -1000,
	-1000, 237, 416, 416, 410, -1000, -1000, 345, 345, -1000,
	11, 11, 375, 375, 29, 51, -1000, -1000, -1000, -1000,
	416, -1000, 425, 104, -1000, 262, -1000, 315, -1000, -1000,
	-1000, -1000, -1000, 422, 33, 386, -1000, 406, 416, -1000,
	357, 416, -1000, -1000, -1000, 6, -1000, 327, -1000, -79,
	-106, 416, -1000, 384, 397, 416, -1000, 33, -1000, -1000,
	-1000, -1000, 441, -1000, -1000, 334, -1000, 416, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 59, -1000, -1000, -1000, -1000,
	416, -1000,
}

var yyPgo = [...]int16{
	0, 588, 587, 75, 586, 16, 19, 5, 585, 15,
	0, 584, 6, 581, 339, 337, 580, 579, 578, 577,
	576, 136, 575, 574, 572, 570, 569, 568, 20, 357,
	356, 349, 13, 11, 567, 563, 3, 14, 562, 9,
	561, 559, 7, 558, 555, 554, 553, 552, 551, 550,
	549, 548, 547, 21, 546, 545, 544, 22, 542, 10,
	540, 4, 23, 538, 536, 18, 535, 534, 529, 2,
	12, 528, 527, 523, 522, 520, 519, 513, 512, 505,
	503, 497, 496, 494, 493, 492, 490, 1, 8, 489,
	488, 17, 485, 481, 479, 474, 24, 471, 466, 465,
	318,
}

var yyR1 = [...]int8{
	0, 94, 95, 95, 13, 13, 13, 13, 13, 13,
	13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
	13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
	13, 12, 9, 9, 9, 9, 10, 10, 11, 11,
	28, 28, 28, 7, 8, 8, 2, 2, 4, 4,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 1, 1, 16, 16, 16, 16,
	16, 17, 17, 62, 62, 23, 23, 23, 23, 23,
	23, 23, 23, 23, 23, 23, 24, 24, 24, 26,
	26, 27, 71, 71, 43, 43, 43, 46, 46, 64,
	65, 65, 67, 67, 69, 66, 68, 68, 70, 70,
	70, 70, 45, 45, 45, 45, 45, 32, 32, 87,
	88, 88, 38, 37, 37, 53, 53, 33, 33, 34,
	34, 39, 35, 35, 52, 52, 51, 56, 56, 56,
	97, 97, 96, 96, 98, 98, 60, 60, 60, 25,
	25, 25, 25, 25, 36, 36, 36, 44, 73, 73,
	73, 72, 72, 74, 74, 55, 55, 54, 54, 18,
	19, 19, 20, 20, 21, 21, 21, 21, 21, 21,
	21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
	21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
	21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
	21, 21, 76, 29, 58, 58, 58, 57, 57, 61,
	61, 61, 61, 61, 61, 61, 63, 63, 42, 42,
	42, 99, 99, 41, 40, 40, 5, 5, 5, 5,
	6, 6, 30, 30, 31, 31, 59, 59, 75, 14,
	15, 79, 22, 22, 80, 86, 86, 81, 81, 81,
	81, 85, 85, 82, 78, 77, 48, 48, 48, 48,
	49, 49, 50, 83, 84, 84, 89, 89, 91, 91,
	90, 90, 100, 100, 93, 93, 92, 92, 92, 92,
	47, 47,
}

var yyR2 = [...]int8{
	0, 2, 0, 1, 0, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
	1, 1, 3, 1, 3, 1, 1, 1, 1, 3,
	1, 1, 2, 2, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 2, 0, 2, 1, 1, 1, 1,
	1, 1, 1, 1, 0, 2, 4, 3, 4, 4,
	5, 4, 4, 4, 5, 4, 2, 2, 2, 4,
	4, 3, 2, 2, 2, 2, 2, 4, 3, 4,
	1, 0, 1, 3, 2, 4, 1, 3, 1, 2,
	2, 2, 2, 4, 2, 5, 4, 3, 1, 2,
	1, 3, 4, 2, 1, 6, 6, 3, 0, 3,
	1, 2, 2, 0, 1, 2, 2, 6, 5, 9,
	1, 0, 1, 1, 1, 1, 2, 3, 0, 2,
	2, 2, 6, 10, 3, 2, 0, 4, 1, 1,
	0, 4, 0, 3, 0, 1, 3, 0, 3, 6,
	1, 2, 1, 2, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 2, 4, 3, 3, 0, 3, 1, 1,
	2, 1, 1, 2, 2, 1, 3, 0, 1, 1,
	1, 1, 0, 3, 1, 0, 1, 1, 1, 2,
	1, 3, 9, 8, 6, 5, 1, 3, 2, 3,
	2, 6, 3, 3, 4, 3, 0, 6, 7, 7,
	7, 3, 0, 4, 2, 1, 2, 3, 2, 3,
	5, 6, 9, 5, 3, 3, 6, 6, 1, 0,
	5, 5, 1, 0, 2, 0, 2, 1, 1, 0,
	5, 4,
}

var yyChk = [...]int16{
	-1000, -94, -13, -24, -25, -26, -27, -23, -76, -75,
	-18, -19, -22, -78, -77, -79, -80, -81, -82, -83,
	-84, -43, -48, -89, -90, -49, -50, -44, -47, 36,
	35, 109, 110, 37, 38, 39, 7, 6, 8, 30,
	29, 40, 41, 48, 87, 31, 32, 46, 95, 98,
	97, 45, 47, -95, 18, -29, -30, -31, 63, 61,
	74, -29, -30, -31, 49, 52, -97, 99, 111, 111,
	-100, 41, -14, 61, -15, 63, 74, 113, 68, 49,
	52, 48, 41, -14, 61, -14, -16, 4, 57, 79,
	72, 104, -20, -21, 4, 35, 37, 46, 7, 61,
	62, 63, 74, 72, 38, 39, 40, 87, 41, 48,
	33, 31, 32, 55, 56, 64, 57, 49, 45, 47,
	68, 91, 104, 96, 95, 97, 113, 114, 70, 52,
	102, 88, -17, 91, 4, -9, 15, 4, 16, 19,
	-14, -14, -14, -14, 33, 33, -45, -71, -46, 49,
	-15, 115, 74, 63, 96, 69, 58, 103, -100, 49,
	128, 128, -10, 4, 15, 62, -10, 86, -96, 55,
	64, 70, -53, 64, 88, 91, 112, 113, 62, -62,
	44, 88, -10, -10, 114, -10, -96, 70, 113, 113,
	62, -54, 24, -21, -12, 4, 16, 16, 84, 85,
	85, 86, -10, -10, 88, -96, -51, 47, -56, 36,
	37, 45, 46, 116, 117, -10, 96, 104, 113, -98,
	-96, 56, 57, 129, 129, -58, 54, 24, -10, 84,
	86, 79, -28, 4, 15, -10, -36, 90, 100, -28,
	112, -12, 114, 88, -10, -62, -62, -10, -62, -10,
	-10, -10, -10, -1, 9, -55, -10, -10, -10, -10,
	-10, 89, -28, 64, 102, 102, -52, -53, 64, 79,
	-66, 105, 114, 101, -10, 4, 4, -63, 102, 125,
	-57, -61, 122, 123, 124, 126, 84, -6, -5, 15,
	4, 16, 19, 79, -59, -9, -33, 66, 14, 101,
	63, -10, 63, 24, -10, 88, -62, -62, -74, 114,
	-3, -4, 4, 20, 19, 28, -2, 24, 15, 16,
	13, 25, 83, -85, 92, -9, 71, -28, 74, 74,
	-53, -28, -59, 24, -10, 88, -10, 101, -92, 121,
	119, 120, 74, -57, 25, 13, 59, 59, 59, -6,
	13, 34, 16, -59, -65, 13, -64, 105, -60, 101,
	67, 4, -28, -10, 61, -32, -37, -10, -38, -42,
	106, 107, 108, -72, 133, 83, 20, 19, 21, 22,
	23, 12, 130, 11, 10, -3, -3, -3, -3, -10,
	-6, -86, 113, 93, 85, -10, 63, 69, 53, -68,
	-70, -69, 43, 36, 37, 4, -91, 94, -91, -10,
	-93, -12, -10, -61, 34, -5, 85, -65, -9, 24,
	-59, 72, -34, -39, -10, 77, -32, 13, -33, -40,
	-41, 59, 26, 83, -8, -7, -10, -3, -3, -3,
	-3, -3, -3, -3, -3, -3, 25, 50, 51, 94,
	114, -12, 24, 61, -10, 63, 25, 13, -69, -69,
	4, -9, 118, 85, -10, -67, -69, -59, 13, -35,
	109, 24, -33, -37, 25, -99, 60, -88, -87, -10,
	-7, 13, -10, -59, -32, 54, -70, -11, 4, 15,
	-36, 25, 13, -39, -12, -88, -42, 13, 27, -61,
	-73, 131, 132, -7, 25, -10, -36, -69, 25, -87,
	85, -10,
}

var yyDef = [...]int16{
	4, -2, 2, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 0,
	141, 0, 283, 0, 0, 0, 0, 170, 0, 0,
	265, 0, 0, 0, 0, 0, 0, 0, 0, 283,
	0, 0, 0, 1, 3, 86, 87, 88, 0, 0,
	0, 149, 150, 151, 0, 0, 0, 140, 0, 0,
	0, 282, 75, 0, 74, 0, 0, 0, 0, 0,
	0, 0, 0, 212, 0, 248, 167, 66, 67, 68,
	69, 70, 171, 172, 174, 175, 176, 177, 178, 179,
	180, 181, 182, 183, 184, 185, 186, 187, 188, 189,
	190, 191, 192, 193, 194, 195, 196, 197, 198, 199,
	200, 201, 202, 203, 204, 205, 206, 207, 208, 209,
	210, 211, 0, 71, 72, 264, 32, 33, 34, 0,
	0, 0, 0, 0, 0, 0, 94, 95, 96, 0,
	0, 0, 0, 0, 266, 0, 268, 0, 0, 0,
	0, 0, 216, 36, 37, 0, 0, 0, 0, 142,
	143, 0, 156, 0, 0, 0, 91, 0, 0, 77,
	73, 74, 250, 74, 0, 74, 0, 0, 0, 0,
	0, 64, 0, 173, 252, 253, 31, 35, 0, 0,
	0, 0, 0, 274, 275, 0, 112, 0, 114, 0,
	0, 0, 0, 92, 93, 0, 267, 269, 0, 0,
	0, 144, 145, 0, 0, 227, 0, 0, 0, 0,
	0, 0, 128, 40, 41, 0, 157, 0, 0, 0,
	89, 90, 0, 76, 249, 78, 79, 74, 81, 82,
	83, 74, 85, 164, 0, 0, 165, 0, 254, 262,
	263, 0, 0, 0, 0, 0, 136, 134, 0, 0,
	98, 0, 0, 0, 0, 289, 291, 213, 0, 0,
	0, 218, 219, 221, 222, 225, 0, 0, 240, 236,
	237, 238, 0, 0, 101, 246, 148, 0, 0, 0,
	0, 155, 0, 0, 280, 281, 80, 84, 162, 0,
	65, 50, 51, 0, 0, 0, 48, 0, 46, 47,
	0, 168, 0, 256, 0, 273, 0, 113, 0, 116,
	135, 0, 97, 0, 279, 279, 270, 0, 290, 285,
	287, 288, 0, 214, 215, 0, 220, 223, 224, 0,
	0, 0, 239, 101, 245, 0, 100, 0, 152, 0,
	0, 42, 0, 154, 0, 128, 118, 235, 124, 0,
	228, 229, 230, 169, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 52, 53, 63, 0, 166,
	251, 257, 0, 0, 0, 115, 0, 0, 0, 0,
	106, 108, 0, 0, 0, 0, 276, 278, 277, 271,
	286, 0, 226, 217, 0, 241, 0, 244, 247, 0,
	146, 0, 127, 130, 133, 0, 128, 0, 0, 123,
	234, 232, 0, 0, 163, 45, 43, 54, 55, 56,
	-2, -2, 59, 60, 61, 62, 49, 258, 259, 260,
	0, 261, 0, 0, 138, 0, 105, 0, 109, 110,
	111, 104, 284, 0, 156, 0, 102, 147, 0, 131,
	0, 0, 125, 117, 126, 0, 231, 0, 120, 0,
	160, 0, 255, 0, 137, 0, 107, 156, 38, 39,
	243, 99, 0, 129, 132, 0, 233, 0, 122, 119,
	161, 158, 159, 44, 272, 0, 242, 103, 153, 121,
	0, 139,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]uint8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
	102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
	112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
	122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
	132, 133, 134, 135, 136,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:336
		{
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:337
		{
		}
	case 4:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:341
		{
			yyVAL.statement = nil
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:346
		{
			setParseTree(yylex, yyDollar[1].create)
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:350
		{
			setParseTree(yylex, yyDollar[1].create)
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:354
		{
			setParseTree(yylex, yyDollar[1].trace)
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:358
		{
			setParseTree(yylex, yyDollar[1].stoptrace)
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:362
		{
			setParseTree(yylex, yyDollar[1].drop)
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:366
		{
			setParseTree(yylex, yyDollar[1].lock)
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:370
		{
			setParseTree(yylex, yyDollar[1].unlock)
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:374
		{
			setParseTree(yylex, yyDollar[1].show)
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:378
		{
			setParseTree(yylex, yyDollar[1].help)
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:382
		{
			setParseTree(yylex, yyDollar[1].kill)
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:386
		{
			setParseTree(yylex, yyDollar[1].listen)
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:390
		{
			setParseTree(yylex, yyDollar[1].shutdown)
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:394
		{
			setParseTree(yylex, yyDollar[1].split)
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:398
		{
			setParseTree(yylex, yyDollar[1].move)
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:402
		{
			setParseTree(yylex, yyDollar[1].redistribute)
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:406
		{
			setParseTree(yylex, yyDollar[1].unite)
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:410
		{
			setParseTree(yylex, yyDollar[1].register_router)
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:414
		{
			setParseTree(yylex, yyDollar[1].unregister_router)
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:418
		{
			setParseTree(yylex, yyDollar[1].alter)
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:422
		{
			setParseTree(yylex, yyDollar[1].invalidate)
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:426
		{
			setParseTree(yylex, yyDollar[1].retryMoveTaskGroup)
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:430
		{
			setParseTree(yylex, yyDollar[1].stopMoveTaskGroup)
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:434
		{
			setParseTree(yylex, yyDollar[1].sync_reference_tables)
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:438
		{
			setParseTree(yylex, yyDollar[1].alter_reference_table_storage)
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:442
		{
			setParseTree(yylex, yyDollar[1].alter)
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:445
		{
			setParseTree(yylex, yyDollar[1].icp)
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:450
		{
			yyVAL.uinteger = uint(yyDollar[1].uinteger)
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:455
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:459
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:461
		{
			if yyDollar[1].uinteger > uint(math.MaxInt64) {
				yylex.Error(SIGNED_INT_RANGE_ERROR)
				return 1
			} else {
				buf := make([]byte, binary.MaxVarintLen64)
				binary.PutVarint(buf, int64(yyDollar[1].uinteger))
				yyVAL.str = string(buf)
			}
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:470
		{
			if yyDollar[2].uinteger > uint(-math.MinInt64) {
				yylex.Error(SIGNED_INT_RANGE_ERROR)
				return 1
			} else {
				buf := make([]byte, binary.MaxVarintLen64)
				binary.PutVarint(buf, int64(-yyDollar[2].uinteger))
				yyVAL.str = string(buf)
			}
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:482
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:485
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:491
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:494
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:500
		{
			yyVAL.qname = &rfqn.RelationFQN{RelationName: yyDollar[1].str}
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:504
		{
			yyVAL.qname = &rfqn.RelationFQN{RelationName: yyDollar[1].str}
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:508
		{
			yyVAL.qname = &rfqn.RelationFQN{RelationName: yyDollar[3].str, SchemaName: yyDollar[1].str}
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:513
		{
			yyVAL.colref = &lyx.ColumnRef{
				ColName: yyDollar[1].str,
			}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:521
		{
			yyVAL.colreflist = append(yyDollar[1].colreflist, yyDollar[3].colref)
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:523
		{
			yyVAL.colreflist = []*lyx.ColumnRef{
				yyDollar[1].colref,
			}
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:534
		{
			yyVAL.expr = &lyx.AExprSConst{
				Value: yyDollar[1].str,
			}
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:539
		{
			yyVAL.expr = &lyx.AExprSConst{
				Value: fmt.Sprintf("%+v", yyDollar[1].uinteger),
			}
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:555
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:556
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:561
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:563
		{
			/* column ref */
			yyVAL.expr = &lyx.ColumnRef{
				TableAlias: "",
				ColName:    yyDollar[1].str,
			}
		}
	case 52:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:582
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 53:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:584
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:586
		{
			yyVAL.expr = &lyx.AExprOp{
				Left:  yyDollar[1].expr,
				Right: yyDollar[3].expr,
				Op:    yyDollar[2].str,
			}
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:594
		{
			yyVAL.expr = &lyx.AExprOp{
				Left:  yyDollar[1].expr,
				Right: yyDollar[3].expr,
				Op:    yyDollar[2].str,
			}
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:602
		{
			yyVAL.expr = &lyx.AExprOp{
				Left:  yyDollar[1].expr,
				Right: yyDollar[3].expr,
				Op:    yyDollar[2].str,
			}
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:611
		{
			yyVAL.expr = &lyx.AExprOp{
				Left:  yyDollar[1].expr,
				Right: yyDollar[3].expr,
				Op:    yyDollar[2].str,
			}
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:619
		{
			yyVAL.expr = &lyx.AExprOp{
				Left:  yyDollar[1].expr,
				Right: yyDollar[3].expr,
				Op:    yyDollar[2].str,
			}
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:627
		{
			yyVAL.expr = &lyx.AExprOp{
				Left:  yyDollar[1].expr,
				Right: yyDollar[3].expr,
				Op:    yyDollar[2].str,
			}
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:643
		{
			yyVAL.expr = &lyx.AExprOp{
				Left:  yyDollar[1].expr,
				Right: yyDollar[3].expr,
				Op:    yyDollar[2].str,
			}
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:652
		{
			yyVAL.expr = &lyx.AExprOp{
				Left:  yyDollar[1].expr,
				Right: yyDollar[3].expr,
				Op:    yyDollar[2].str,
			}
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:660
		{
			yyVAL.expr = &lyx.AExprOp{
				Left:  yyDollar[1].expr,
				Right: yyDollar[3].expr,
				Op:    yyDollar[2].str,
			}
		}
	case 63:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:668
		{
			yyVAL.expr = &lyx.AExprNot{Arg: yyDollar[2].expr}
		}
	case 64:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:675
		{
			yyVAL.where = &lyx.AExprEmpty{}
		}
	case 65:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:679
		{
			yyVAL.where = yyDollar[2].expr
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:686
		{
			switch v := strings.ToLower(string(yyDollar[1].str)); v {
			case DatabasesStr, RoutersStr, PoolsStr,
				InstanceStr, ShardsStr, BackendConnectionsStr,
				KeyRangesStr, KeyRangesExtendedStr, StatusStr,
				DistributionsStr, CoordinatorAddrStr, VersionStr,
				ReferenceRelationsStr, TaskGroupStr, TaskGroupsStr,
				PreparedStatementsStr, QuantilesStr, SequencesStr,
				IsReadOnlyStr, MoveStatsStr, TsaCacheStr, Users,
				MoveTaskStr, MoveTasksStr, UniqueIndexesStr,
				TaskGroupExtendedStr, TaskGroupsExtendedStr, RedistributeTasksStr,
				ErrorStr, StartupFinishedStr, TwoPhaseTXStr, TwoPhaseTXStorageStr,
				FileSettingsStr:
				yyVAL.str = v
			default:
				yyVAL.str = UnsupportedStr
			}
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:703
		{
			yyVAL.str = yyDollar[1].str
		}
	case 68:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:705
		{
			yyVAL.str = yyDollar[1].str
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:707
		{
			yyVAL.str = yyDollar[1].str
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:709
		{
			yyVAL.str = yyDollar[1].str
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:715
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:719
		{
			switch v := string(yyDollar[1].str); v {
			case BackendStr:
				yyVAL.str = v
			default:
				yyVAL.str = UnsupportedStr
			}
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:729
		{
			yyVAL.bool = true
		}
	case 74:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:729
		{
			yyVAL.bool = false
		}
	case 75:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:733
		{
			yyVAL.drop = &Drop{Element: yyDollar[2].key_range_selector}
		}
	case 76:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:737
		{
			yyVAL.drop = &Drop{Element: &KeyRangeSelector{KeyRangeID: `*`}}
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:741
		{
			yyVAL.drop = &Drop{Element: yyDollar[2].distribution_selector, CascadeDelete: yyDollar[3].bool}
		}
	case 78:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:745
		{
			yyVAL.drop = &Drop{Element: &DistributionSelector{ID: `*`}, CascadeDelete: yyDollar[4].bool}
		}
	case 79:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:749
		{
			yyVAL.drop = &Drop{Element: &ShardSelector{ID: yyDollar[3].str}, CascadeDelete: yyDollar[4].bool}
		}
	case 80:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:753
		{
			yyVAL.drop = &Drop{Element: &TaskGroupSelector{ID: yyDollar[4].str}, CascadeDelete: yyDollar[5].bool}
		}
	case 81:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:757
		{
			yyVAL.drop = &Drop{Element: &SequenceSelector{Name: yyDollar[3].str}, CascadeDelete: yyDollar[4].bool}
		}
	case 82:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:761
		{
			yyVAL.drop = &Drop{
				Element: &ReferenceRelationSelector{
					ID: yyDollar[4].str,
				},
			}
		}
	case 83:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:769
		{
			yyVAL.drop = &Drop{
				Element: &UniqueIndexSelector{
					ID: yyDollar[4].str,
				},
			}
		}
	case 84:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:777
		{
			yyVAL.drop = &Drop{
				Element: &RedistributeTaskSelector{
					ID: yyDollar[4].str,
				},
				CascadeDelete: yyDollar[5].bool,
			}
		}
	case 85:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:786
		{
			yyVAL.drop = &Drop{
				Element: &MoveTaskSelector{
					ID: yyDollar[4].str,
				},
			}
		}
	case 86:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:797
		{
			yyVAL.create = &Create{Element: yyDollar[2].ds}
		}
	case 87:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:802
		{
			yyVAL.create = &Create{Element: yyDollar[2].kr}
		}
	case 88:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:806
		{
			yyVAL.create = &Create{Element: yyDollar[2].shard}
		}
	case 89:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:812
		{
			yyVAL.trace = &TraceStmt{All: true}
		}
	case 90:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:815
		{
			yyVAL.trace = &TraceStmt{
				Client: yyDollar[4].uinteger,
			}
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:823
		{
			yyVAL.stoptrace = &StopTraceStmt{}
		}
	case 92:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:829
		{
			yyVAL.statement = &System{
				Reload: true,
			}
		}
	case 93:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:833
		{
			yyVAL.statement = &System{
				Restart: true,
			}
		}
	case 94:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:841
		{
			yyVAL.alter = &Alter{Element: yyDollar[2].alter_distribution}
		}
	case 95:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:845
		{
			yyVAL.alter = &Alter{Element: yyDollar[2].statement}
		}
	case 96:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:850
		{
			yyVAL.alter = &Alter{Element: yyDollar[2].alter_shard}
		}
	case 97:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:856
		{
			yyVAL.alter_shard = &AlterShard{
				Shard: &ShardSelector{ID: yyDollar[2].str},
				Element: &AlterShardHosts{
					Hosts: yyDollar[4].strlist,
				},
			}
		}
	case 98:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:866
		{
			yyVAL.alter_shard = &AlterShard{
				Shard: &ShardSelector{ID: yyDollar[2].str},
				Element: &AlterShardOptions{
					Options: yyDollar[3].options,
				},
			}
		}
	case 99:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:876
		{
			yyVAL.options = yyDollar[3].options
		}
	case 100:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:880
		{
			yyVAL.options = yyDollar[1].options
		}
	case 101:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:883
		{
			yyVAL.options = nil
		}
	case 102:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:887
		{
			yyVAL.options = []GenericOption{yyDollar[1].option}
		}
	case 103:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:891
		{
			yyVAL.options = append(yyDollar[1].options, yyDollar[3].option)
		}
	case 104:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:897
		{
			yyVAL.option = GenericOption{Name: yyDollar[1].str, Arg: string(yyDollar[2].str)}
		}
	case 105:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:902
		{
			yyVAL.options = yyDollar[3].options
		}
	case 106:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:906
		{
			yyVAL.options = []GenericOption{yyDollar[1].option}
		}
	case 107:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:910
		{
			yyVAL.options = append(yyDollar[1].options, yyDollar[3].option)
		}
	case 108:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:916
		{
			yyVAL.option = yyDollar[1].option
		}
	case 109:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:920
		{
			yyVAL.option = yyDollar[2].option
			yyVAL.option.Action = OptionActionSet
		}
	case 110:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:925
		{
			yyVAL.option = yyDollar[2].option
			yyVAL.option.Action = OptionActionAdd
		}
	case 111:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:930
		{
			yyVAL.option = GenericOption{Name: yyDollar[2].str}
			yyVAL.option.Action = OptionActionDrop
		}
	case 112:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:937
		{
			yyVAL.alter_distribution = &AlterDistribution{
				Distribution: yyDollar[1].distribution_selector,
				Element: &AttachRelation{
					Relations: yyDollar[2].relations,
				},
			}
		}
	case 113:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:946
		{
			yyVAL.alter_distribution = &AlterDistribution{
				Distribution: yyDollar[1].distribution_selector,
				Element: &DetachRelation{
					RelationName: yyDollar[4].qname,
				},
			}
		}
	case 114:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:955
		{
			yyVAL.alter_distribution = &AlterDistribution{
				Distribution: yyDollar[1].distribution_selector,
				Element:      yyDollar[2].alter_relation,
			}
		}
	case 115:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:962
		{
			yyVAL.alter_distribution = &AlterDistribution{
				Distribution: yyDollar[1].distribution_selector,
				Element: &AlterDefaultShard{
					Shard: yyDollar[5].str,
				},
			}
		}
	case 116:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:971
		{
			yyVAL.alter_distribution = &AlterDistribution{
				Distribution: yyDollar[1].distribution_selector,
				Element:      &DropDefaultShard{},
			}
		}
	case 117:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:981
		{
			yyVAL.dEntrieslist = append(yyDollar[1].dEntrieslist, yyDollar[3].distrKeyEntry)
		}
	case 118:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:983
		{
			yyVAL.dEntrieslist = []DistributionKeyEntry{
				yyDollar[1].distrKeyEntry,
			}
		}
	case 119:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:990
		{
			yyVAL.typedColRef = TypedColRef{
				Column: yyDollar[1].str,
				Type:   yyDollar[2].str,
			}
		}
	case 120:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:999
		{
			yyVAL.routingExpr = []TypedColRef{yyDollar[1].typedColRef}
		}
	case 121:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1001
		{
			yyVAL.routingExpr = append(yyDollar[1].routingExpr, yyDollar[3].typedColRef)
		}
	case 122:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:1006
		{
			yyVAL.distrKeyEntry = DistributionKeyEntry{
				HashFunction: yyDollar[1].str,
				Expr:         yyDollar[3].routingExpr,
			}
		}
	case 123:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1015
		{
			yyVAL.distrKeyEntry = DistributionKeyEntry{
				Column:       yyDollar[1].str,
				HashFunction: yyDollar[2].str,
			}
		}
	case 124:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1020
		{
			yyVAL.distrKeyEntry = yyDollar[1].distrKeyEntry
		}
	case 125:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:1026
		{
			yyVAL.distributed_relation = &DistributedRelation{
				Relation:             yyDollar[2].qname,
				DistributionKey:      yyDollar[5].dEntrieslist,
				AutoIncrementEntries: yyDollar[6].aiEntrieslist,
			}
		}
	case 126:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:1034
		{
			yyVAL.distributed_relation = &DistributedRelation{
				Relation:             yyDollar[2].qname,
				DistributionKey:      yyDollar[4].dEntrieslist,
				AutoIncrementEntries: yyDollar[5].aiEntrieslist,
			}
		}
	case 127:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1043
		{
			yyVAL.aiEntrieslist = yyDollar[3].aiEntrieslist
		}
	case 128:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1045
		{
			yyVAL.aiEntrieslist = nil
		}
	case 129:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1051
		{
			yyVAL.aiEntrieslist = append(yyDollar[1].aiEntrieslist, yyDollar[3].aiEntry)
		}
	case 130:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1053
		{
			yyVAL.aiEntrieslist = []*AutoIncrementEntry{
				yyDollar[1].aiEntry,
			}
		}
	case 131:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1061
		{
			yyVAL.aiEntry = &AutoIncrementEntry{
				Column: yyDollar[1].str,
				Start:  uint64(yyDollar[2].uinteger),
			}
		}
	case 132:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1070
		{
			yyVAL.uinteger = yyDollar[2].uinteger
		}
	case 133:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1072
		{
			yyVAL.uinteger = 0
		}
	case 134:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1078
		{
			yyVAL.relations = []*DistributedRelation{yyDollar[1].distributed_relation}
		}
	case 135:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1080
		{
			yyVAL.relations = append(yyDollar[1].relations, yyDollar[2].distributed_relation)
		}
	case 136:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1085
		{
			yyVAL.relations = yyDollar[2].relations
		}
	case 137:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:1090
		{
			yyVAL.alter_relation = &AlterRelationV2{
				RelationName: yyDollar[3].qname,
				Element: &AlterRelationDistributionKey{
					DistributionKey: yyDollar[6].dEntrieslist,
				},
			}
		}
	case 138:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:1098
		{
			yyVAL.alter_relation = &AlterRelationV2{
				RelationName: yyDollar[3].qname,
				Element: &AlterRelationSchema{
					SchemaName: yyDollar[5].str,
				},
			}
		}
	case 139:
		yyDollar = yyS[yypt-9 : yypt+1]
//line gram.y:1106
		{
			yyVAL.alter_relation = &AlterRelationV2{
				RelationName: yyDollar[3].qname,
				Element: &RenameDistributionColumn{
					OldName: yyDollar[7].str,
					NewName: yyDollar[9].str,
				},
			}
		}
	case 141:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1117
		{
		}
	case 142:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1120
		{
		}
	case 143:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1120
		{
		}
	case 144:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1123
		{
		}
	case 145:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1123
		{
		}
	case 146:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1127
		{
			yyVAL.strlist = yyDollar[2].strlist
		}
	case 147:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1128
		{
			yyVAL.strlist = yyDollar[3].strlist
		}
	case 148:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1128
		{
		}
	case 149:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1132
		{
			yyVAL.create = &Create{Element: yyDollar[2].ds}
		}
	case 150:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1137
		{
			yyVAL.create = &Create{Element: yyDollar[2].kr}
		}
	case 151:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1142
		{
			yyVAL.create = &Create{Element: yyDollar[2].shard}
		}
	case 152:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:1147
		{
			yyVAL.create = &Create{
				Element: &ReferenceRelationDefinition{
					TableName:            yyDollar[4].qname,
					AutoIncrementEntries: yyDollar[5].aiEntrieslist,
					ShardIds:             yyDollar[6].strlist,
				},
			}
		}
	case 153:
		yyDollar = yyS[yypt-10 : yypt+1]
//line gram.y:1158
		{
			yyVAL.create = &Create{
				Element: &UniqueIndexDefinition{
					ID:        yyDollar[4].str,
					TableName: yyDollar[6].qname,
					Columns:   yyDollar[9].routingExpr,
				},
			}
		}
	case 154:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1169
		{
			yyVAL.distribution_selector = &DistributionSelector{ID: yyDollar[3].str}
		}
	case 155:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1172
		{
			yyVAL.distribution_selector = &DistributionSelector{ID: yyDollar[2].str}
		}
	case 156:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1174
		{
			yyVAL.distribution_selector = &DistributionSelector{ID: "default"}
		}
	case 157:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:1180
		{
			yyVAL.alter = &Alter{
				Element: &AlterDistribution{
					Distribution: yyDollar[4].distribution_selector,
					Element: &AttachRelation{
						Relations: []*DistributedRelation{yyDollar[3].distributed_relation},
					},
				},
			}
		}
	case 158:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1192
		{
			yyVAL.opt_asc_desc = lyx.SORTBY_ASC
		}
	case 159:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1193
		{
			yyVAL.opt_asc_desc = lyx.SORTBY_DESC
		}
	case 160:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1194
		{
			yyVAL.opt_asc_desc = lyx.SORTBY_DEFAULT
		}
	case 161:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:1198
		{
			yyVAL.order_clause = &lyx.SortBy{
				Node:      yyDollar[3].colref,
				SortbyDir: yyDollar[4].opt_asc_desc,
			}
		}
	case 162:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1204
		{
			yyVAL.order_clause = nil
		}
	case 163:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1209
		{
			yyVAL.group_clause = GroupBy{Col: yyDollar[3].colreflist}
		}
	case 164:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1212
		{
			yyVAL.group_clause = GroupByClauseEmpty{}
		}
	case 165:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1216
		{
			yyVAL.strlist = []string{yyDollar[1].str}
		}
	case 166:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1216
		{
			yyVAL.strlist = append(yyDollar[1].strlist, yyDollar[3].str)
		}
	case 167:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1219
		{
			yyVAL.strlist = nil
		}
	case 168:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1220
		{
			yyVAL.strlist = yyDollar[2].strlist
		}
	case 169:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:1224
		{
			yyVAL.show = &Show{Cmd: yyDollar[2].str, Columns: yyDollar[3].strlist, Where: yyDollar[4].where, GroupBy: yyDollar[5].group_clause, Order: yyDollar[6].order_clause}
		}
	case 170:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1230
		{
			yyVAL.help = &Help{CommandName: ""}
		}
	case 171:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1234
		{
			yyVAL.help = &Help{CommandName: yyDollar[2].str}
		}
	case 172:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1242
		{
			yyVAL.str = yyDollar[1].str
		}
	case 173:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1246
		{
			yyVAL.str = yyDollar[1].str + " " + yyDollar[2].str
		}
	case 174:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1252
		{
			yyVAL.str = yyDollar[1].str
		}
	case 175:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1253
		{
			yyVAL.str = "CREATE"
		}
	case 176:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1254
		{
			yyVAL.str = "DROP"
		}
	case 177:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1255
		{
			yyVAL.str = "ALTER"
		}
	case 178:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1256
		{
			yyVAL.str = "SHOW"
		}
	case 179:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1257
		{
			yyVAL.str = "KEY"
		}
	case 180:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1258
		{
			yyVAL.str = "RANGE"
		}
	case 181:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1259
		{
			yyVAL.str = "DISTRIBUTION"
		}
	case 182:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1260
		{
			yyVAL.str = "SHARD"
		}
	case 183:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1261
		{
			yyVAL.str = "SHARDS"
		}
	case 184:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1262
		{
			yyVAL.str = "LOCK"
		}
	case 185:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1263
		{
			yyVAL.str = "UNLOCK"
		}
	case 186:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1264
		{
			yyVAL.str = "SPLIT"
		}
	case 187:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1265
		{
			yyVAL.str = "UNITE"
		}
	case 188:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1266
		{
			yyVAL.str = "MOVE"
		}
	case 189:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1267
		{
			yyVAL.str = "REDISTRIBUTE"
		}
	case 190:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1268
		{
			yyVAL.str = "ROUTER"
		}
	case 191:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1269
		{
			yyVAL.str = "REGISTER"
		}
	case 192:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1270
		{
			yyVAL.str = "UNREGISTER"
		}
	case 193:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1271
		{
			yyVAL.str = "TABLE"
		}
	case 194:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1272
		{
			yyVAL.str = "TABLES"
		}
	case 195:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1273
		{
			yyVAL.str = "RELATION"
		}
	case 196:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1274
		{
			yyVAL.str = "RELATIONS"
		}
	case 197:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1275
		{
			yyVAL.str = "REFERENCE"
		}
	case 198:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1276
		{
			yyVAL.str = "ATTACH"
		}
	case 199:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1277
		{
			yyVAL.str = "DETACH"
		}
	case 200:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1278
		{
			yyVAL.str = "SEQUENCE"
		}
	case 201:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1279
		{
			yyVAL.str = "CLIENT"
		}
	case 202:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1280
		{
			yyVAL.str = "CLIENTS"
		}
	case 203:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1281
		{
			yyVAL.str = "CACHE"
		}
	case 204:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1282
		{
			yyVAL.str = "INVALIDATE"
		}
	case 205:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1283
		{
			yyVAL.str = "SYNC"
		}
	case 206:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1284
		{
			yyVAL.str = "TASK"
		}
	case 207:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1285
		{
			yyVAL.str = "GROUP"
		}
	case 208:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1286
		{
			yyVAL.str = "INDEX"
		}
	case 209:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1287
		{
			yyVAL.str = "UNIQUE"
		}
	case 210:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1288
		{
			yyVAL.str = "DEFAULT"
		}
	case 211:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1289
		{
			yyVAL.str = "ALL"
		}
	case 212:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1293
		{
			yyVAL.lock = &Lock{KeyRangeID: yyDollar[2].key_range_selector.KeyRangeID}
		}
	case 213:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:1301
		{
			yyVAL.ds = &DistributionDefinition{
				ID:           yyDollar[2].str,
				ColTypes:     yyDollar[3].strlist,
				DefaultShard: yyDollar[4].str,
			}
		}
	case 214:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1310
		{
			yyVAL.strlist = yyDollar[3].strlist
		}
	case 215:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1312
		{
			/* modern variant */
			yyVAL.strlist = yyDollar[2].strlist
		}
	case 216:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1315
		{
			/* empty column types should be prohibited */
			yyVAL.strlist = nil
		}
	case 217:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1321
		{
			yyVAL.strlist = append(yyDollar[1].strlist, yyDollar[3].str)
		}
	case 218:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1323
		{
			yyVAL.strlist = []string{
				yyDollar[1].str,
			}
		}
	case 219:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1330
		{
			yyVAL.str = qdb.ColumnTypeVarchar
		}
	case 220:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1332
		{
			yyVAL.str = qdb.ColumnTypeVarcharHashed
		}
	case 221:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1334
		{
			yyVAL.str = qdb.ColumnTypeInteger
		}
	case 222:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1336
		{
			yyVAL.str = qdb.ColumnTypeInteger
		}
	case 223:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1338
		{
			yyVAL.str = qdb.ColumnTypeUinteger
		}
	case 224:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1340
		{
			yyVAL.str = qdb.ColumnTypeUinteger
		}
	case 225:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1342
		{
			yyVAL.str = qdb.ColumnTypeUUID
		}
	case 226:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1347
		{
			yyVAL.str = yyDollar[3].str
		}
	case 227:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1349
		{
			yyVAL.str = ""
		}
	case 228:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1354
		{
			yyVAL.str = "identity"
		}
	case 229:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1356
		{
			yyVAL.str = "murmur"
		}
	case 230:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1358
		{
			yyVAL.str = "city"
		}
	case 231:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1363
		{
		}
	case 232:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1363
		{
		}
	case 233:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1367
		{
			yyVAL.str = yyDollar[3].str
		}
	case 234:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1372
		{
			yyVAL.str = yyDollar[1].str
		}
	case 235:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1374
		{
			yyVAL.str = ""
		}
	case 236:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1380
		{
			yyVAL.bytes = []byte(yyDollar[1].str)
		}
	case 237:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1384
		{
			yyVAL.bytes = []byte(yyDollar[1].str)
		}
	case 238:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1386
		{
			if yyDollar[1].uinteger > uint(math.MaxInt64) {
				yylex.Error(SIGNED_INT_RANGE_ERROR)
				return 1
			} else {
				buf := make([]byte, binary.MaxVarintLen64)
				binary.PutVarint(buf, int64(yyDollar[1].uinteger))
				yyVAL.bytes = buf
			}
		}
	case 239:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1395
		{
			if yyDollar[2].uinteger > uint(-math.MinInt64) {
				yylex.Error(SIGNED_INT_RANGE_ERROR)
				return 1
			} else {
				buf := make([]byte, binary.MaxVarintLen64)
				binary.PutVarint(buf, int64(-yyDollar[2].uinteger))
				yyVAL.bytes = buf
			}
		}
	case 240:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1407
		{
			yyVAL.krbound = &KeyRangeBound{
				Pivots: [][]byte{
					yyDollar[1].bytes,
				},
			}
		}
	case 241:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1414
		{
			yyVAL.krbound = &KeyRangeBound{
				Pivots: append(yyDollar[1].krbound.Pivots, yyDollar[3].bytes),
			}
		}
	case 242:
		yyDollar = yyS[yypt-9 : yypt+1]
//line gram.y:1423
		{
			yyVAL.kr = &KeyRangeDefinition{
				KeyRangeID:   yyDollar[3].str,
				LowerBound:   yyDollar[5].krbound,
				ShardID:      yyDollar[8].str,
				Distribution: yyDollar[9].distribution_selector,
			}
		}
	case 243:
		yyDollar = yyS[yypt-8 : yypt+1]
//line gram.y:1432
		{
			str, err := randomHex(6)
			if err != nil {
				panic(err)
			}
			yyVAL.kr = &KeyRangeDefinition{
				LowerBound:   yyDollar[4].krbound,
				ShardID:      yyDollar[7].str,
				Distribution: yyDollar[8].distribution_selector,
				KeyRangeID:   "kr" + str,
			}
		}
	case 244:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:1447
		{
			yyVAL.shard = &ShardDefinition{Id: yyDollar[2].str, Hosts: yyDollar[5].strlist, Options: yyDollar[6].options}
		}
	case 245:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:1452
		{
			str, err := randomHex(6)
			if err != nil {
				panic(err)
			}
			yyVAL.shard = &ShardDefinition{Id: "shard" + str, Hosts: yyDollar[4].strlist, Options: yyDollar[5].options}
		}
	case 246:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1462
		{
			yyVAL.strlist = []string{yyDollar[1].str}
		}
	case 247:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1467
		{
			yyVAL.strlist = append(yyDollar[1].strlist, yyDollar[3].str)
		}
	case 248:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1473
		{
			yyVAL.unlock = &Unlock{KeyRangeID: yyDollar[2].key_range_selector.KeyRangeID}
		}
	case 249:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1479
		{
			yyVAL.key_range_selector = &KeyRangeSelector{KeyRangeID: yyDollar[3].str}
		}
	case 250:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1485
		{
			yyVAL.distribution_selector = &DistributionSelector{ID: yyDollar[2].str}
		}
	case 251:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:1491
		{
			yyVAL.split = &SplitKeyRange{KeyRangeID: yyDollar[2].key_range_selector.KeyRangeID, KeyRangeFromID: yyDollar[4].str, Border: yyDollar[6].krbound}
		}
	case 252:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1497
		{
			yyVAL.kill = &Kill{Cmd: yyDollar[2].str, Target: yyDollar[3].uinteger}
		}
	case 253:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1500
		{
			n, err := strconv.ParseUint(yyDollar[3].str, 10, 64)
			if err == nil {
				yyVAL.kill = &Kill{Cmd: yyDollar[2].str, Target: uint(n)}
			}
		}
	case 254:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:1510
		{
			yyVAL.move = &MoveKeyRange{KeyRangeID: yyDollar[2].key_range_selector.KeyRangeID, DestShardID: yyDollar[4].str}
		}
	case 255:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1515
		{
			yyVAL.str = yyDollar[3].str
		}
	case 256:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1515
		{
			yyVAL.str = ""
		}
	case 257:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:1520
		{
			yyVAL.redistribute = &RedistributeKeyRange{
				KeyRangeID:  yyDollar[2].key_range_selector.KeyRangeID,
				DestShardID: yyDollar[4].str,
				BatchSize:   yyDollar[5].integer,
				Id:          yyDollar[6].str,
				Check:       true,
				Apply:       true,
			}
		}
	case 258:
		yyDollar = yyS[yypt-7 : yypt+1]
//line gram.y:1529
		{
			yyVAL.redistribute = &RedistributeKeyRange{
				KeyRangeID:  yyDollar[2].key_range_selector.KeyRangeID,
				DestShardID: yyDollar[4].str,
				BatchSize:   yyDollar[5].integer,
				Id:          yyDollar[6].str,
				Check:       true,
			}
		}
	case 259:
		yyDollar = yyS[yypt-7 : yypt+1]
//line gram.y:1537
		{
			yyVAL.redistribute = &RedistributeKeyRange{
				KeyRangeID:  yyDollar[2].key_range_selector.KeyRangeID,
				DestShardID: yyDollar[4].str,
				BatchSize:   yyDollar[5].integer,
				Id:          yyDollar[6].str,
				Apply:       true,
			}
		}
	case 260:
		yyDollar = yyS[yypt-7 : yypt+1]
//line gram.y:1545
		{
			yyVAL.redistribute = &RedistributeKeyRange{
				KeyRangeID:  yyDollar[2].key_range_selector.KeyRangeID,
				DestShardID: yyDollar[4].str,
				BatchSize:   yyDollar[5].integer,
				Id:          yyDollar[6].str,
				Check:       false, /* or true, doesnt matter */
				Apply:       true,
				NoWait:      true,
			}
		}
	case 261:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1557
		{
			yyVAL.integer = int(yyDollar[3].uinteger)
		}
	case 262:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1558
		{
			yyVAL.integer = -1
		}
	case 263:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:1562
		{
			yyVAL.unite = &UniteKeyRange{KeyRangeIDL: yyDollar[2].key_range_selector.KeyRangeID, KeyRangeIDR: yyDollar[4].str}
		}
	case 264:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1568
		{
			yyVAL.listen = &Listen{addr: yyDollar[2].str}
		}
	case 265:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1574
		{
			yyVAL.shutdown = &Shutdown{}
		}
	case 266:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1580
		{
			yyVAL.invalidate = &Invalidate{
				Target: SchemaCacheInvalidateTarget,
			}
		}
	case 267:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1585
		{
			yyVAL.invalidate = &Invalidate{
				Target: SchemaCacheInvalidateTarget,
			}
		}
	case 268:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1590
		{
			yyVAL.invalidate = &Invalidate{
				Target: BackendConnectionsInvalidateTarget,
			}
		}
	case 269:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1595
		{
			yyVAL.invalidate = &Invalidate{
				Target: StaleClientsInvalidateTarget,
			}
		}
	case 270:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:1603
		{
			yyVAL.sync_reference_tables = &SyncReferenceTables{
				ShardID:          yyDollar[5].str,
				RelationSelector: "*",
			}
		}
	case 271:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:1609
		{
			yyVAL.sync_reference_tables = &SyncReferenceTables{
				ShardID:          yyDollar[6].str,
				RelationSelector: yyDollar[4].str,
			}
		}
	case 272:
		yyDollar = yyS[yypt-9 : yypt+1]
//line gram.y:1618
		{
			yyVAL.alter_reference_table_storage = &AlterReferenceTableStorage{
				RelationSelector: yyDollar[4].qname,
				Shards:           yyDollar[8].strlist,
			}
		}
	case 273:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:1629
		{
			yyVAL.register_router = &RegisterRouter{ID: yyDollar[3].str, Addr: yyDollar[5].str}
		}
	case 274:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1635
		{
			yyVAL.unregister_router = &UnregisterRouter{ID: yyDollar[3].str}
		}
	case 275:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:1640
		{
			yyVAL.unregister_router = &UnregisterRouter{ID: `*`}
		}
	case 276:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:1648
		{
			yyVAL.retryMoveTaskGroup = &RetryMoveTaskGroup{ID: yyDollar[5].str, NoWait: yyDollar[6].bool}
		}
	case 277:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:1653
		{
			yyVAL.retryMoveTaskGroup = &RetryMoveTaskGroup{ID: "*", NoWait: yyDollar[6].bool}
		}
	case 278:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1659
		{
			yyVAL.bool = true
		}
	case 279:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1661
		{
			yyVAL.bool = false
		}
	case 280:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:1668
		{
			yyVAL.stopMoveTaskGroup = &StopMoveTaskGroup{ID: yyDollar[5].str}
		}
	case 281:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:1673
		{
			yyVAL.stopMoveTaskGroup = &StopMoveTaskGroup{ID: "*"}
		}
	case 282:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1678
		{
		}
	case 283:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1678
		{
		}
	case 284:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1684
		{
			yyVAL.duration = time.Duration(time.Duration(yyDollar[1].uinteger) * time.Second)
		}
	case 285:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1686
		{
			yyVAL.duration = time.Duration(1 * time.Minute)
		}
	case 286:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:1691
		{
			yyVAL.icpAction = &ICPointAction{
				Act:     "sleep",
				Timeout: yyDollar[2].duration,
			}
		}
	case 287:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1696
		{
			yyVAL.icpAction = &ICPointAction{
				Act: "wait",
			}
		}
	case 288:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:1700
		{
			yyVAL.icpAction = &ICPointAction{
				Act: "panic",
			}
		}
	case 289:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:1704
		{
			yyVAL.icpAction = &ICPointAction{
				Act: "panic",
			}
		}
	case 290:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:1711
		{
			yyVAL.icp = &InstanceControlPoint{
				Name:   string(yyDollar[4].str),
				Enable: true,
				A:      yyDollar[5].icpAction,
			}
		}
	case 291:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:1718
		{
			yyVAL.icp = &InstanceControlPoint{
				Name:   string(yyDollar[4].str),
				Enable: false,
			}
		}
	}
	goto yystack /* stack new state and value */
}
