// Code generated by goyacc -o yacc/console/sql.go -p yy yacc/console/sql.y. DO NOT EDIT.

//line yacc/console/sql.y:3

package spqrparser

import __yyfmt__ "fmt"

//line yacc/console/sql.y:4

//line yacc/console/sql.y:11
type yySymType struct {
	yys   int
	str   string
	byte  byte
	bytes []byte
	int   int
	bool  bool
	empty struct{}

	statement Statement
	show      *Show

	drop   *Drop
	create *Create

	ds            *DataspaceDefinition
	kr            *KeyRangeDefinition
	shard         *ShardDefinition
	sharding_rule *ShardingRuleDefinition

	register_router *RegisterRouter

	unregister_router *UnregisterRouter
	kill              *Kill
	dropAll           *DropAll
	lock              *Lock
	shutdown          *Shutdown
	listen            *Listen
	unlock            *Unlock
	split             *SplitKeyRange
	move              *MoveKeyRange
	unite             *UniteKeyRange

	entrieslist []ShardingRuleEntry
	shruleEntry ShardingRuleEntry

	sharding_rule_selector *ShardingRuleSelector
	key_range_selector     *KeyRangeSelector
}

const STRING = 57346
const COMMAND = 57347
const SHOW = 57348
const KILL = 57349
const POOLS = 57350
const STATS = 57351
const LISTS = 57352
const SERVERS = 57353
const CLIENTS = 57354
const DATABASES = 57355
const SHUTDOWN = 57356
const LISTEN = 57357
const REGISTER = 57358
const UNREGISTER = 57359
const ROUTER = 57360
const ROUTE = 57361
const CREATE = 57362
const ADD = 57363
const DROP = 57364
const LOCK = 57365
const UNLOCK = 57366
const SPLIT = 57367
const MOVE = 57368
const COMPOSE = 57369
const SHARDING = 57370
const COLUMN = 57371
const TABLE = 57372
const HASH = 57373
const FUNCTION = 57374
const KEY = 57375
const RANGE = 57376
const DATASPACE = 57377
const SHARDS = 57378
const KEY_RANGES = 57379
const ROUTERS = 57380
const SHARD = 57381
const HOST = 57382
const SHARDING_RULES = 57383
const RULE = 57384
const COLUMNS = 57385
const BY = 57386
const FROM = 57387
const TO = 57388
const WITH = 57389
const UNITE = 57390
const ALL = 57391
const ADDRESS = 57392

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"STRING",
	"COMMAND",
	"SHOW",
	"KILL",
	"POOLS",
	"STATS",
	"LISTS",
	"SERVERS",
	"CLIENTS",
	"DATABASES",
	"SHUTDOWN",
	"LISTEN",
	"REGISTER",
	"UNREGISTER",
	"ROUTER",
	"ROUTE",
	"CREATE",
	"ADD",
	"DROP",
	"LOCK",
	"UNLOCK",
	"SPLIT",
	"MOVE",
	"COMPOSE",
	"SHARDING",
	"COLUMN",
	"TABLE",
	"HASH",
	"FUNCTION",
	"KEY",
	"RANGE",
	"DATASPACE",
	"SHARDS",
	"KEY_RANGES",
	"ROUTERS",
	"SHARD",
	"HOST",
	"SHARDING_RULES",
	"RULE",
	"COLUMNS",
	"BY",
	"FROM",
	"TO",
	"WITH",
	"UNITE",
	"ALL",
	"ADDRESS",
	"';'",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacc/console/sql.y:517

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 138

var yyAct = [...]int{

	93, 115, 122, 109, 67, 26, 27, 37, 100, 92,
	79, 79, 79, 29, 28, 33, 23, 88, 131, 21,
	20, 22, 34, 35, 30, 31, 125, 87, 103, 85,
	56, 61, 111, 59, 58, 57, 105, 82, 76, 86,
	41, 104, 126, 81, 78, 42, 112, 32, 77, 80,
	70, 43, 121, 102, 84, 96, 94, 83, 60, 62,
	63, 41, 49, 64, 52, 40, 42, 130, 48, 51,
	39, 55, 43, 73, 89, 53, 79, 90, 91, 38,
	129, 116, 123, 95, 68, 114, 97, 47, 98, 99,
	107, 36, 46, 69, 71, 72, 1, 74, 75, 66,
	128, 45, 113, 106, 19, 18, 17, 118, 16, 117,
	15, 13, 119, 14, 24, 124, 9, 25, 10, 120,
	110, 101, 108, 8, 7, 6, 44, 127, 4, 3,
	5, 12, 132, 11, 65, 54, 50, 2,
}
var yyPact = [...]int{

	-1, -1000, -44, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	12, 33, 36, 57, -1000, -1000, 22, 22, 80, -1000,
	17, 17, 17, 55, 17, 17, -1000, -1000, -1000, -1000,
	-1000, -4, 14, 72, -1000, -1000, -1000, -1000, 72, -1000,
	-1000, 9, -5, 8, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -16,
	5, -19, -30, 72, -1000, -1000, 72, 72, -38, -1000,
	-1000, 7, 6, -1000, -1000, 72, 72, 72, 72, -42,
	23, -17, 1, -1000, -1000, -1000, -1000, -8, -1000, -1000,
	86, 3, 81, 77, 80, 77, -1000, -1000, 3, -1000,
	21, 78, 78, -1000, -1000, -20, -1000, -1000, -1000, -1000,
	-1000, 10, -1000, -1000, -1000, 77, 76, 48, -1000, -1000,
	-28, 72, -1000,
}
var yyPgo = [...]int{

	0, 137, 136, 62, 135, 134, 133, 131, 130, 129,
	128, 126, 79, 70, 65, 125, 124, 123, 122, 3,
	121, 120, 119, 118, 117, 116, 114, 113, 111, 110,
	108, 106, 105, 104, 71, 4, 1, 0, 103, 2,
	102, 100, 96, 91,
}
var yyR1 = [...]int{

	0, 42, 43, 43, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 34, 34, 34, 34, 34, 34, 34, 34, 34,
	4, 5, 8, 8, 9, 9, 9, 10, 10, 10,
	10, 6, 39, 40, 41, 36, 37, 35, 25, 11,
	12, 18, 18, 19, 20, 20, 21, 21, 22, 22,
	13, 14, 23, 2, 3, 26, 24, 29, 7, 30,
	31, 28, 27, 38, 32, 15, 16, 17, 33,
}
var yyR2 = [...]int{

	0, 2, 0, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 1, 1, 1, 1, 1, 1, 1, 2,
	5, 1, 2, 2, 2, 0, 2, 2, 3, 0,
	10, 5, 1, 3, 3, 2, 2, 6, 2, 4,
	4, 2, 1, 1, 5, 4, 4, 3, 3,
}
var yyChk = [...]int{

	-1000, -42, -1, -9, -10, -8, -15, -16, -17, -25,
	-23, -6, -7, -28, -27, -29, -30, -31, -32, -33,
	21, 20, 22, 17, -26, -24, 6, 7, 15, 14,
	25, 26, 48, 16, 23, 24, -43, 51, -12, -13,
	-14, 28, 33, 39, -11, -12, -13, -14, 35, -3,
	-2, 33, 28, 18, -4, -34, 8, 13, 12, 11,
	36, 9, 37, 38, 41, -5, -34, -35, 4, -3,
	33, -3, -3, 18, -3, -3, 42, 34, -37, 4,
	-37, 34, 42, 49, -37, 45, 34, 46, 47, -37,
	-37, -37, 47, -37, 49, -37, 49, -37, -37, -37,
	50, -20, 30, 45, 40, 44, -38, 4, -18, -19,
	-21, 29, 43, -40, 4, -36, 4, -35, -36, -19,
	-22, 31, -39, 4, -39, 46, 32, -36, -41, 4,
	19, 46, -37,
}
var yyDef = [...]int{

	0, -2, 2, 4, 5, 6, 7, 8, 9, 10,
	11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
	0, 0, 0, 0, 48, 62, 0, 0, 0, 72,
	0, 0, 0, 0, 0, 0, 1, 3, 34, 35,
	36, 0, 0, 0, 37, 38, 39, 40, 0, 32,
	33, 0, 0, 0, 41, 30, 21, 22, 23, 24,
	25, 26, 27, 28, 29, 68, 31, 71, 47, 0,
	0, 0, 0, 0, 65, 66, 0, 0, 0, 46,
	49, 0, 0, 77, 78, 0, 0, 0, 0, 0,
	55, 0, 0, 64, 75, 63, 76, 0, 69, 70,
	0, 0, 0, 0, 0, 0, 74, 73, 50, 51,
	59, 0, 0, 54, 43, 0, 45, 61, 67, 52,
	53, 0, 56, 42, 57, 0, 0, 0, 58, 44,
	0, 0, 60,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 51,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yacc/console/sql.y:133
		{
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:134
		{
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:139
		{
			setParseTree(yylex, yyDollar[1].create)
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:143
		{
			setParseTree(yylex, yyDollar[1].create)
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:147
		{
			setParseTree(yylex, yyDollar[1].drop)
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:151
		{
			setParseTree(yylex, yyDollar[1].dropAll)
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:155
		{
			setParseTree(yylex, yyDollar[1].dropAll)
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:159
		{
			setParseTree(yylex, yyDollar[1].dropAll)
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:163
		{
			setParseTree(yylex, yyDollar[1].lock)
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:167
		{
			setParseTree(yylex, yyDollar[1].unlock)
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:171
		{
			setParseTree(yylex, yyDollar[1].show)
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:175
		{
			setParseTree(yylex, yyDollar[1].kill)
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:179
		{
			setParseTree(yylex, yyDollar[1].listen)
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:183
		{
			setParseTree(yylex, yyDollar[1].shutdown)
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:187
		{
			setParseTree(yylex, yyDollar[1].split)
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:191
		{
			setParseTree(yylex, yyDollar[1].move)
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:195
		{
			setParseTree(yylex, yyDollar[1].unite)
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:199
		{
			setParseTree(yylex, yyDollar[1].register_router)
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:203
		{
			setParseTree(yylex, yyDollar[1].unregister_router)
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:220
		{
			switch v := string(yyDollar[1].str); v {
			case ShowDatabasesStr, ShowRoutersStr, ShowPoolsStr, ShowShardsStr, ShowKeyRangesStr, ShowShardingRules:
				yyVAL.str = v
			default:
				yyVAL.str = ShowUnsupportedStr
			}
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:231
		{
			switch v := string(yyDollar[1].str); v {
			case KillClientsStr:
				yyVAL.str = v
			default:
				yyVAL.str = "unsupp"
			}
		}
	case 32:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc/console/sql.y:242
		{
			yyVAL.drop = &Drop{Element: yyDollar[2].key_range_selector}
		}
	case 33:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc/console/sql.y:246
		{
			yyVAL.drop = &Drop{Element: yyDollar[2].sharding_rule_selector}
		}
	case 34:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc/console/sql.y:252
		{
			yyVAL.create = &Create{Element: yyDollar[2].sharding_rule}
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc/console/sql.y:257
		{
			yyVAL.create = &Create{Element: yyDollar[2].kr}
		}
	case 36:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc/console/sql.y:261
		{
			yyVAL.create = &Create{Element: yyDollar[2].shard}
		}
	case 37:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc/console/sql.y:268
		{
			yyVAL.create = &Create{Element: yyDollar[2].ds}
		}
	case 38:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc/console/sql.y:273
		{
			yyVAL.create = &Create{Element: yyDollar[2].sharding_rule}
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc/console/sql.y:278
		{
			yyVAL.create = &Create{Element: yyDollar[2].kr}
		}
	case 40:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc/console/sql.y:282
		{
			yyVAL.create = &Create{Element: yyDollar[2].shard}
		}
	case 41:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc/console/sql.y:289
		{
			yyVAL.show = &Show{Cmd: yyDollar[2].str}
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:295
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:301
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:307
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:313
		{
			yyVAL.bytes = []byte(yyDollar[1].str)
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:319
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:325
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 49:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc/console/sql.y:335
		{
			yyVAL.ds = &DataspaceDefinition{ID: yyDollar[2].str}
		}
	case 50:
		yyDollar = yyS[yypt-5 : yypt+1]
//line yacc/console/sql.y:347
		{
			yyVAL.sharding_rule = &ShardingRuleDefinition{ID: yyDollar[3].str, TableName: yyDollar[4].str, Entries: yyDollar[5].entrieslist}
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:352
		{
			yyVAL.entrieslist = make([]ShardingRuleEntry, 0)
			yyVAL.entrieslist = append(yyVAL.entrieslist, yyDollar[1].shruleEntry)
		}
	case 52:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc/console/sql.y:358
		{
			yyVAL.entrieslist = append(yyDollar[1].entrieslist, yyDollar[2].shruleEntry)
		}
	case 53:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc/console/sql.y:364
		{
			yyVAL.shruleEntry = ShardingRuleEntry{
				Column:       yyDollar[1].str,
				HashFunction: yyDollar[2].str,
			}
		}
	case 54:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc/console/sql.y:373
		{
			yyVAL.str = yyDollar[2].str
		}
	case 55:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yacc/console/sql.y:376
		{
			yyVAL.str = ""
		}
	case 56:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc/console/sql.y:380
		{
			yyVAL.str = yyDollar[2].str
		}
	case 57:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc/console/sql.y:385
		{
			yyVAL.str = yyDollar[2].str
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc/console/sql.y:391
		{
			yyVAL.str = yyDollar[3].str
		}
	case 59:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yacc/console/sql.y:394
		{
			yyVAL.str = ""
		}
	case 60:
		yyDollar = yyS[yypt-10 : yypt+1]
//line yacc/console/sql.y:399
		{
			yyVAL.kr = &KeyRangeDefinition{LowerBound: yyDollar[5].bytes, UpperBound: yyDollar[7].bytes, ShardID: yyDollar[10].str, KeyRangeID: yyDollar[3].str}
		}
	case 61:
		yyDollar = yyS[yypt-5 : yypt+1]
//line yacc/console/sql.y:406
		{
			yyVAL.shard = &ShardDefinition{Id: yyDollar[2].str, Hosts: []string{yyDollar[5].str}}
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc/console/sql.y:416
		{
			yyVAL.sharding_rule_selector = &ShardingRuleSelector{ID: yyDollar[3].str}
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc/console/sql.y:422
		{
			yyVAL.key_range_selector = &KeyRangeSelector{KeyRangeID: yyDollar[3].str}
		}
	case 65:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc/console/sql.y:428
		{
			yyVAL.lock = &Lock{KeyRangeID: yyDollar[2].key_range_selector.KeyRangeID}
		}
	case 66:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc/console/sql.y:434
		{
			yyVAL.unlock = &Unlock{KeyRangeID: yyDollar[2].key_range_selector.KeyRangeID}
		}
	case 67:
		yyDollar = yyS[yypt-6 : yypt+1]
//line yacc/console/sql.y:441
		{
			yyVAL.split = &SplitKeyRange{KeyRangeID: yyDollar[2].key_range_selector.KeyRangeID, KeyRangeFromID: yyDollar[4].str, Border: yyDollar[6].bytes}
		}
	case 68:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc/console/sql.y:447
		{
			yyVAL.kill = &Kill{Cmd: yyDollar[2].str}
		}
	case 69:
		yyDollar = yyS[yypt-4 : yypt+1]
//line yacc/console/sql.y:453
		{
			yyVAL.move = &MoveKeyRange{KeyRangeID: yyDollar[2].key_range_selector.KeyRangeID, DestShardID: yyDollar[4].str}
		}
	case 70:
		yyDollar = yyS[yypt-4 : yypt+1]
//line yacc/console/sql.y:459
		{
			yyVAL.unite = &UniteKeyRange{KeyRangeIDL: yyDollar[2].key_range_selector.KeyRangeID, KeyRangeIDR: yyDollar[4].str}
		}
	case 71:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc/console/sql.y:465
		{
			yyVAL.listen = &Listen{addr: yyDollar[2].str}
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:471
		{
			yyVAL.shutdown = &Shutdown{}
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc/console/sql.y:479
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 74:
		yyDollar = yyS[yypt-5 : yypt+1]
//line yacc/console/sql.y:486
		{
			yyVAL.register_router = &RegisterRouter{ID: yyDollar[3].str, Addr: yyDollar[5].str}
		}
	case 75:
		yyDollar = yyS[yypt-4 : yypt+1]
//line yacc/console/sql.y:492
		{
			yyVAL.dropAll = &DropAll{Entity: EntityKeyRanges}
		}
	case 76:
		yyDollar = yyS[yypt-4 : yypt+1]
//line yacc/console/sql.y:499
		{
			yyVAL.dropAll = &DropAll{Entity: EntityShardingRule}
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc/console/sql.y:506
		{
			yyVAL.dropAll = &DropAll{Entity: EntityRouters}
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc/console/sql.y:512
		{
			yyVAL.unregister_router = &UnregisterRouter{ID: yyDollar[3].str}
		}
	}
	goto yystack /* stack new state and value */
}
