CREATE DISTRIBUTION ds1 COLUMN TYPES integer; 
ADD SHARDING RULE rule1 COLUMNS id FOR DISTRIBUTION ds1;
ADD SHARDING RULE rule2 TABLE test COLUMNS idx FOR DISTRIBUTION ds1;
ADD SHARDING RULE rule3 COLUMNS idy FOR DISTRIBUTION ds1;
ALTER DISTRIBUTION ds1 ATTACH RELATION test COLUMNS idx;