#!/bin/bash

set -e

GPADMIN=gpadmin
GPVER=6
GPHOME=/opt/greenplum-db-${GPVER}

case $1 in
    install|upgrade)
        id "${GPADMIN}" >> /dev/null 2>&1 || \
            useradd -r -m -d /home/${GPADMIN} -s /bin/bash ${GPADMIN}
     ;;
esac

