// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/datatransfers/data_transfers.go
//
// Generated by this command:
//
//	mockgen -source=pkg/datatransfers/data_transfers.go -destination=pkg/mock/pgx/mock_pgxconn_iface.go -package=mock
//

// Package mock is a generated GoMock package.
package mock
