create distribution ds1 column types integer;

alter distribution ds1 attach relation Comments distribution key hashslot;
CREATE KEY RANGE kr2 FROM 8192 ROUTE TO sh2 FOR DISTRIBUTION ds1;
CREATE KEY RANGE kr1 FROM 0 ROUTE TO sh1 FOR DISTRIBUTION ds1;

CREATE DISTRIBUTION ds2 COLUMN TYPES INTEGER HASH;
ADD KEY RANGE krid4 FROM 2147483648 ROUTE TO sh2 FOR DISTRIBUTION ds2;
ADD KEY RANGE krid5 FROM 1073741824 ROUTE TO sh1 FOR DISTRIBUTION ds2;
ADD KEY RANGE krid3 FROM 0 ROUTE TO sh1 FOR DISTRIBUTION ds2;
ALTER DISTRIBUTION ds2 ATTACH RELATION xMoveStr DISTRIBUTION KEY w_id HASH FUNCTION MURMUR;


