CREATE DISTRIBUTION ds1 COLUMN TYPES integer;

ALTER DISTRIBUTION ds1 ATTACH RELATION users DISTRIBUTION KEY id;
ALTER DISTRIBUTION ds1 ATTACH RELATION user_addresses DISTRIBUTION KEY user_id;
ALTER DISTRIBUTION ds1 ATTACH RELATION orders DISTRIBUTION KEY user_id;
ALTER DISTRIBUTION ds1 ATTACH RELATION order_items DISTRIBUTION KEY user_id;
ALTER DISTRIBUTION ds1 ATTACH RELATION payments DISTRIBUTION KEY user_id;
ALTER DISTRIBUTION ds1 ATTACH RELATION shopping_carts DISTRIBUTION KEY user_id;

CREATE REFERENCE TABLE countries;
CREATE REFERENCE TABLE product_categories;
CREATE REFERENCE TABLE products;
CREATE REFERENCE TABLE currencies;

CREATE KEY RANGE kr1 FROM 0     ROUTE TO sh1 FOR DISTRIBUTION ds1;
CREATE KEY RANGE kr2 FROM 50000 ROUTE TO sh2 FOR DISTRIBUTION ds1;
