CREATE DISTRIBUTION ds1 COLUMN TYPES integer;
CREATE DISTRIBUTION compositeds COLUMN TYPES integer, integer;
CREATE DISTRIBUTION varchards COLUMN TYPES varchar;

-- create key ranges for all shards
CREATE KEY RANGES FOR DISTRIBUTION ds1 USING ALL SHARDS;
SHOW key_ranges;
DROP KEY RANGE ALL;

-- create key range for some shards
CREATE KEY RANGES FOR DISTRIBUTION ds1 USING SHARDS sh1, sh2;
SHOW key_ranges;
DROP KEY RANGE ALL;

-- check if there is intersecting key range
CREATE KEY RANGE kr1 FROM -100000 ROUTE TO sh1 FOR DISTRIBUTION ds1;
CREATE KEY RANGES FOR DISTRIBUTION ds1 USING ALL SHARDS;
SHOW key_ranges;
DROP KEY RANGE ALL;

CREATE KEY RANGES FOR DISTRIBUTION ds1 BETWEEN 0 AND 1000 USING ALL SHARDS;
SHOW key_ranges;
DROP KEY RANGE ALL;

CREATE KEY RANGES FOR DISTRIBUTION ds1 BETWEEN 0 AND 1000 USING SHARDS sh1, sh2;
SHOW key_ranges;
DROP KEY RANGE ALL;

CREATE KEY RANGE kr1 FROM 100 ROUTE TO sh4 FOR DISTRIBUTION ds1;
CREATE KEY RANGES FOR DISTRIBUTION ds1 BETWEEN 0 AND 1000 USING ALL SHARDS;
SHOW key_ranges;
DROP KEY RANGE ALL;

CREATE KEY RANGES FOR DISTRIBUTION compositeds USING ALL SHARDS;
CREATE KEY RANGES FOR DISTRIBUTION varchards USING ALL SHARDS;

DROP DISTRIBUTION ALL CASCADE;
