CREATE DISTRIBUTION ds1 COLUMN TYPES integer;

-- create key range works
CREATE KEY RANGE krid2 FROM 11 ROUTE TO sh2 FOR DISTRIBUTION ds1;
CREATE KEY RANGE krid1 FROM 0 ROUTE TO sh1 FOR DISTRIBUTION ds1;

-- intersecting key range
CREATE KEY RANGE krid3 FROM 50 ROUTE TO sh1 FOR DISTRIBUTION ds1;

SHOW key_ranges;

DROP KEY RANGE ALL;

-- intersecting key range
CREATE KEY RANGE krid3 FROM -50 ROUTE TO sh1 FOR DISTRIBUTION ds1;

SHOW key_ranges;

DROP DISTRIBUTION ALL CASCADE;
