CREATE DISTRIBUTION ds1 COLUMN TYPES integer;
CREATE KEY RANGE krid2 FROM 11 ROUTE TO sh2 FOR DISTRIBUTION ds1;
CREATE KEY RANGE krid1 FROM 0 ROUTE TO sh1 FOR DISTRIBUTION ds1;
ALTER DISTRIBUTION ds1 ATTACH RELATION test DISTRIBUTION KEY id;

SPLIT KEY RANGE krid3 FROM krid1 BY 5;
SHOW key_ranges;

LOCK KEY RANGE krid1;
SPLIT KEY RANGE krid4 FROM krid1 BY 5;
UNLOCK KEY RANGE krid1;

SPLIT KEY RANGE krid4 FROM krid1 BY 50;

SPLIT KEY RANGE krid4 FROM krid2 BY 5;

DROP DISTRIBUTION ALL CASCADE;
DROP KEY RANGE ALL;
