DROP DISTRIBUTION ALL CASCADE;

CREATE DISTRIBUTION ds1 COLUMN TYPES integer;

CREATE KEY RANGE kr2 FROM 11 ROUTE TO sh2 FOR DISTRIBUTION ds1;
CREATE KEY RANGE kr1 FROM 0 ROUTE TO sh1 FOR DISTRIBUTION ds1;

ALTER DISTRIBUTION ds1 ATTACH RELATION test_tls DISTRIBUTION KEY id;
