REGISTER ROUTER r1 ADDRESS "[regress_router]:7000";

CREATE DISTRIBUTION ds1 COLUMN TYPES integer;
CREATE KEY RANGE krid1 FROM 100 ROUTE TO sh1 FOR DISTRIBUTION ds1;
CREATE KEY RANGE krid2 FROM 200 ROUTE TO sh3 FOR DISTRIBUTION ds1;
CREATE KEY RANGE krid3 FROM 600 ROUTE TO sh2 FOR DISTRIBUTION ds1;
CREATE KEY RANGE krid1 FROM 900 ROUTE TO sh4 FOR DISTRIBUTION ds1;

SHOW key_ranges;

REBALANCE DISTRIBUTION ds1 USING ALL SHARDS;

SHOW key_ranges;

SHOW TASK GROUPS;

DROP DISTRIBUTION ALL CASCADE;
UNREGISTER ROUTER ALL;
