REGISTER ROUTER r1 ADDRESS "[regress_router]:7000";

DROP SHARD sh1;
SHOW SHARDS;
CREATE SHARD sh1 OPTIONS (HOST 'spqr_shard_1:6432', HOST 'spqr_shard_1_replica:6432');
SHOW SHARDS;
ALTER SHARD sh1 OPTIONS (SSLMODE 'require', ADD user 'test_user');
SHOW SHARDS;
ALTER SHARD sh1 OPTIONS (DROP HOST 'spqr_shard_1_replica:6432');
SHOW SHARDS;

UNREGISTER ROUTER ALL;
