SHOW shards;

ADD SHARDING RULE r1 COLUMNS w_id;
ADD KEY RANGE krid1 FROM 1 TO 10 ROUTE TO sh1;
ADD KEY RANGE krid2 FROM 11 TO 20 ROUTE TO sh2;

SHOW key_ranges;
SHOW sharding_rules;

DROP KEY RANGE ALL;
DROP SHARDING RULE ALL;

ADD KEY RANGE krid1 FROM 1  TO 10 ROUTE TO sh1;
ADD KEY RANGE krid1 FROM 1  TO 10 ROUTE TO sh1;
ADD KEY RANGE krid2 FROM 11 TO 20 ROUTE TO sh2;
ADD KEY RANGE krid3 FROM 1 TO 20 ROUTE TO sh2;
ADD KEY RANGE krid3 FROM 19 TO 22 ROUTE TO sh2;

ADD SHARDING RULE rule1 COLUMNS id;
ADD SHARDING RULE rule1 COLUMNS id;
ADD SHARDING RULE rule1 COLUMNS w_id;
ADD SHARDING RULE rule1 COLUMNS bid;

DROP KEY RANGE ALL;
DROP SHARDING RULE ALL;

SHOW key_ranges;
SHOW sharding_rules;
