REGISTER ROUTER r1 ADDRESS spqr_router_1_1:7000;

DROP KEY RANGE ALL;
DROP SHARDING RULE ALL;

ADD KEY RANGE krid1 FROM 1  TO 10 ROUTE TO sh1;
ADD KEY RANGE krid1 FROM 1  TO 10 ROUTE TO sh1;
ADD KEY RANGE krid2 FROM 11 TO 20 ROUTE TO sh2;
ADD KEY RANGE krid3 FROM 1 TO 20 ROUTE TO sh2;
ADD KEY RANGE krid3 FROM 19 TO 22 ROUTE TO sh2;

ADD SHARDING RULE rule1 COLUMNS id;
ADD SHARDING RULE rule1 COLUMNS id;
ADD SHARDING RULE rule1 COLUMNS w_id;
ADD SHARDING RULE rule1 COLUMNS bid;

SHOW key_ranges;
SHOW sharding_rules;

DROP SHARDING RULE rule1;
