FROM spqr-base-image-debug
EXPOSE 2345

CMD /go/bin/dlv --listen=:2345 --headless=true --log=true --accept-multiclient --log-output=rpc,dap --check-go-version=true exec /spqr/spqr-coordinator -- -c ${COORDINATOR_CONFIG}